### ISSUE TITLE
Flickering on search

### ISSUE THREAD

**Issue by yasinuslu** [percolatestudio/atmosphere#100]
Left panel flickers when i open or close search view. 

```
userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1886.0 Safari/537.36
```

**Comment by domyen** [comment]
@yasinuslu, I can't seem to reproduce this, any tips?

**Comment by yasinuslu** [comment]
I'm on archlinux and using latest chromium. I just tested with chrome beta (34) without problems. Seems like the problem is specific for my current chromium build, sorry about that.

**Comment by domyen** [comment]
No worries. Thanks for the report!
