### ISSUE TITLE
Atmosphere login?

### ISSUE THREAD

**Issue by miraten** [percolatestudio/atmosphere#104]
I was going to publish my own package to the Atmosphere.
When the release done using 'mrt release ./' command, the prompt appears to input username/password.
I entered my Meteor account, and my GitHub account to get the message 'User not found'.
There is no sign up link in the Atmosphere Home.

What should I do?

**Comment by tmeasday** [comment]
Oh, sorry! I hadn't thought of this. You can sign up at http://atmosphere.meteor.com/accounts

**Comment by tmeasday** [comment]
I updated the documentation to explicitly mention this but I think we need to make it clearer.

**Comment by miraten** [comment]
Thanks, I released my package successfully.

It is a simple, but more featured i18n package inspired by Telescope source.

**Comment by dwlf** [comment]
@tmeasday> I updated the documentation to explicitly mention this but I think we need to make it clearer.

Right, the log in design pattern is to have a log in button in the menu bar. And I'd hope the accounts page would be in the new design (v2).

1.1 The PDF of your book Discover Meteor reads:
"Second Note: You'll need to login at http://atmosphere.meteor.com and create a username and password which you'll enter on the command line when you call mrt release .."
which I've file vs the book.
1. https://atmosphere.meteor.com/accounts instructions don't make sense to a new meteor.com developer.
   It reads "connect your meteor developer account to your atmosphere account", but using my https://www.meteor.com/account-settings account 'lloydde' results in "User not found". https://www.meteor.com/account-settings suggests there should be a way to "Authorized Apps"

So do I need to create an account specifically for atmosphere.meteor.com?
1. This also reveals either a bug or someone being a little too fancy with the redirects: you can visit https://atmosphere.meteor.com/accounts but visiting atmosphere.meteor.com automatically redirects you. Would it work better copying the atmosphere v1 to atmosphere1.meteor.com and having the accounts at atmosphere1.meteor.com/accounts for now? With atmosphere.meteor.com strictly being a redirector?

**Comment by tmeasday** [comment]
Hey @lloydde - I appreciate this is confusing and we'll do our best to make it clearer. It's a temporary situation while we await official packaging support.

For now, you need to just head to http://atmosphere.meteor.com/accounts, create an account (with the login buttons on the top right), [1], and then you should be good to use that for `mrt publish` & friends.

It's not possible to host v1 at any other URL as due to the fact that it's a *.meteor.com app the database is outside of our control (ie. you can't link two *.meteor.com apps to the same db, AFAIK).

[1] you can link your MD account while you are at it, why not?

**Comment by tmeasday** [comment]
I've updated http://atmosphere.meteor.com/accounts to be more informative, and it should hopefully be less confusing to people. Comments appreciated.

@dominicnguyen - in the devel branch I put some simple extra text at the top of the publishing page. Can you emphasise it please

**Comment by domyen** [comment]
Done. Ready for release

**Comment by dwlf** [comment]
Verified resolved.... it definitely is much improved, but I hope packaging is better part of Meteor Development soon as there is still a gap between account creation (for atmosphere.meteor.com) and "Don't worry, it's simple. Just Sign in ▾"

**Comment by tmeasday** [comment]
@lloydde - maybe this will whet your whistle a little: https://www.youtube.com/watch?v=RWhbjQ7GeQw&list=UU3fBiJrFFMhKlsWM46AsAYw#t=2798

**Comment by dwlf** [comment]
Just read "You can add support in your app with meteor add accounts-meteor-developer. If you then include {{loginButtons}} somewhere in your template, you'll see a configuration wizard, which will guide you to www.meteor.com/account-settings to set up an OAuth application. You can expect to see community sites like Discover Meteor, Atmosphere, and EventedMind using accounts-meteor-developer soon."
https://www.meteor.com/blog/2014/02/25/meteor-developer-accounts

Will check that youtube link now.

**Comment by dwlf** [comment]
@tmeasday things are making much more sense to me in that context. Thank you.
