### ISSUE TITLE
don't limit recent items to 10

### ISSUE THREAD

**Issue by serkandurusoy** [percolatestudio/atmosphere#106]
The recent items section on the home page limits the item count to 10. Well, there are days when more than 20 items are released/updated. Especially those days when CFS gets some update :)

Well, We should have some means to expand that list.

While at it, why not provide means to expand other sections (trending, most used ...)

**Comment by Lauricio** [comment]
+1

**Comment by shaneseaton** [comment]
The limit is..well...limiting!!

**Comment by willemx** [comment]
Yes!
I miss this feature as much as I like the new layout...

**Comment by tmeasday** [comment]
@dominicnguyen - I've implemented a first version of this for the package search landing pages as we discussed, in the `infinite-scroll` branch.

Passing over to you for comment + styling.

**Comment by domyen** [comment]
@tmeasday For infinite scrolling and package loading in general there are 3 states that I'd like to represent:
1. **Searching**: Loading indicator 
2. **Results found**: Counting the set of incoming items & rendering the placeholders  
3. **Results displayed**: Populating those placeholders with content

I think we have coverage on 1 & 3 but not 2. I'll style 1, let's figure out if 2 is feasible.

**Proposed Flow**
![atmosphere-v0 3-loading1](https://cloud.githubusercontent.com/assets/263385/2541092/decc9c34-b5d9-11e3-8273-b7661274d3d1.jpg)
![atmosphere-v0 3-loading2](https://cloud.githubusercontent.com/assets/263385/2541090/decaef92-b5d9-11e3-807a-418b36c26a91.jpg)
![atmosphere-v0 3-loading3](https://cloud.githubusercontent.com/assets/263385/2541091/decb3b8c-b5d9-11e3-8cd6-6cf875235db8.jpg)
![atmosphere-v0 3-loading4](https://cloud.githubusercontent.com/assets/263385/2541089/dec9372e-b5d9-11e3-8013-cf9cd63f3a03.jpg)
![atmosphere-v0 3-loading5](https://cloud.githubusercontent.com/assets/263385/2541088/dec8b452-b5d9-11e3-9f33-a22db745e4a2.jpg)
![atmosphere-v0 3-loading6](https://cloud.githubusercontent.com/assets/263385/2541087/dec73726-b5d9-11e3-9273-1f99cb39c6b3.jpg)

**Comment by tmeasday** [comment]
OK, cool. Getting closer to this. 

I think I pretty much implemented what you want on that page, apart from the redundant "spinner below packages" (image no 4). We already know how many packages there are to match the query, so there's no reason no to go straight to step 5.

**Comment by tmeasday** [comment]
Please have a play and let me know what you think @dominicnguyen

**Comment by domyen** [comment]
I've adjusted the styles a bit and added a new state for the package modules. '.module-loading' is a placeholder state (the grey box) for the module. When the module loads it should populate the empty '.module-loading' with content and remove the class. 

The loading experience for infinite scroll modules would be:
1. Trigger scroll
2. Get expected # of incoming packages
3. Create empty modules for # of incoming packages < div class="module module-loading">
4. Populate empty modules with content and remove class .module-loading

Have a few questions and requests:
- Should we limit the # of times we trigger infinite scroll? I could foresee this becoming quite resource intensive for servers & may affect browser performance. e.g., automatically trigger infinite scroll 3x and then have a 'load more' button?
- Should we turn the package module into components to support the new 'placeholder' states like .module-loading (see commit).
- I think the scroll position trigger for infinite-scroll may be too aggressive. Perhaps we can tweak to within 200px of the bottom of the viewport and limit the returned results to ~16?

**Comment by tmeasday** [comment]
I think it's getting closer. I added two temporary 1s timeouts to the search publication so we can see the intermediate scrolling state.

Regarding your notes:
1. I'm not sure there's much point. The only times there'll be enough results to need to IS more than 3 times, it'll be for something like the recent packages where it's not very server resource intensive to fetch them. Let's not prematurely optimize.
2. It may end up becoming a component but a package list rather than a package item (the placeholders are rendered separately to the eventual package grid item).
3. I'm not really understanding your last point. Can you elaborate?

**Comment by domyen** [comment]
@tmeasday push your changes :)
1. I want to prevent premature scrolling by adjusting the point where we would trigger the scroll closer to the very end of the list. (ignore what I said about viewport, i misspoke)

**Comment by tmeasday** [comment]
Sorry! Done.

Ahh, ok, so remove a bit of the offset. Check.

**Comment by tmeasday** [comment]
- [x] Reduce offset
- [x] Should stop triggering callback when loading
- [x] Stop at 100 packages
- [x] Add `.module-loading` to package lockup, then remove.

**Comment by tmeasday** [comment]
Alright, check it again.

**Comment by domyen** [comment]
Cheers!  At the moment is seems like we wait till the entire group has received information before we remove .module-loading en mass; is it possible to do it on a per-package basis? I find that it feels slower because we wait for 20 some packages to load before animating.

i.e., if we see that a package has rendered all necessary content, the .module-loading is removed for that package.

**Comment by tmeasday** [comment]
Unfortunately, it's not technically possible to do that. If we place packages in the list as they arrive then we can't control the order and they'll flicker as they re-order.

I have some ideas about how to transmit the order as well as the package list (which we'll need when we transition to a more robust search index on the server). When we implement that we can revisit this.

**Comment by tmeasday** [comment]
@dominicnguyen - so are we good with the functionality as it stands? I need to:
- [x] Generalize the behaviour into a component
- [x] Use it on the search overlay
- [x] Add recent items page
- [ ] Don't track secondary searches
- [ ] Get rid of search delay.

**Comment by domyen** [comment]
Sounds good.

**Comment by tmeasday** [comment]
OK, @dominicnguyen - can you please check out the search overlay and recent packages page. We are almost done here..

**Comment by domyen** [comment]
@tmeasday here are the 2 refinements we discussed in chat:
1. Option to hide page spinner. We don't want 2 spinners on search
2. Load more button should appear after the packages have loaded (i.e., it appears at the same time as the spinner right now)

The infinite scroll seems to hiccup and stall the scrollbar in between rendering the greyed out package (.module-loading) and animating the package into view. 
Any ideas? Could this be a factor of asking the browser/gpu to render it all at once?
I noticed that it does this whether we animate it in or not. @zol has more details.

**Comment by zol** [comment]
Capturing profiling info during scrolling shows that there is major work being done in `deps.js` that's blocking the UI thread. This is inline with what i'd expect: @tmeasday we should talk about whether it's possible to mitigate this someway.

**Comment by tmeasday** [comment]
@dom - done.

re: perf -- could be drawing the SVGs? would like to hear your thoughts @zol

**Comment by tmeasday** [comment]
Ok. Removed infinite scroll for now. Will revisit perf problems when we have time.

@dominicnguyen I am good to deploy if you are (merged to devel). Do you want to double check the styling (specifically the "More" button under "Recent Packages" and the "Load More" button on search overlay), and give me the green light.

**Comment by tmeasday** [comment]
Still need to get other sections and proper infinite scroll going but I'm going to close this one now..
