### ISSUE TITLE
Flag or remove from public view orphan / redirect packages

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#108]
Some packages are duplicates of existing packages. Right now this isn't transparent, inflates the search results artificially, and the user will land at the same package twice.

To reproduce:
1. Search for "admin"
2. Click on `houston` and `z-mongo-admin`.

The latter is https://atmospherejs.com/package/z-mongo-admin, but it redirects to `houston`.

**Comment by tmeasday** [comment]
Hey @dandv - perhaps you can ask @gterrono to remove the package, following these instructions https://atmosphere.meteor.com/wtf/maintain

**Comment by domyen** [comment]
@dandv Percolate is developing a flagging feature to address a similar concern of warning folks that packages are deprecated or otherwise not working. As far as removing from the packaging index, Meteor is managing that feature.
