### ISSUE TITLE
Remove dead package - admin

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#109]
https://atmospherejs.com/package/admin

**Comment by particle4dev** [comment]
https://atmospherejs.com/package/upload-avatar => remove this package, please. I can't remove it from atmosphere.meteor.com

**Comment by tmeasday** [comment]
Both packages marked deleted.

**Comment by dandv** [comment]
I still see https://atmospherejs.com/package/admin, and Atmosphere searches for "admin" continue to find it.
