### ISSUE TITLE
Styleguide: Allow for anchor-links on styleguide

### ISSUE THREAD

**Issue by domyen** [percolatestudio/atmosphere#112]
Enable anchor-links for /styleguide. As we add more to the styleguide it'd be good to bookmark anchor links and also to share it with the community!

**Comment by tmeasday** [comment]
Already working I think dude. Just put down an `<a name="something">`

**Comment by domyen** [comment]
Not sure what that means.

Do I add: name="typography" to href="#typography" class="nochrome"?

**Comment by tmeasday** [comment]
The link to the anchor looks like `<a href="/styleguide#typography">Go To Typography</a>`. The anchor itself looks like `<a name="typeography>Typography</a>`.
