### ISSUE TITLE
Going back loses scroll position

### ISSUE THREAD

**Issue by SachaG** [percolatestudio/atmosphere#113]
Going back with the browser's back button always brings you back to the top of the page. Maybe scroll position should be stored somewhere instead?

**Comment by domyen** [comment]
I think we're having a look at this one with the Iron Transitioner integration (https://github.com/percolatestudio/atmosphere-beta/issues/103). 
@tmeasday can you confirm?

**Comment by tmeasday** [comment]
Yes, exactly. When we have a transitioner working, we can scroll each page separately - then we can look at storing the scroll position in the history and re-using it.

**Comment by zol** [comment]
Bring fix over from new ps.com

**Comment by tmeasday** [comment]
Look into this: https://atmospherejs.com/okgrow/iron-router-autoscroll

**Comment by tmeasday** [comment]
Not sure if this solution is satisfactory. But it seems to work.

**Comment by zol** [comment]
Deployed.
