### ISSUE TITLE
Simple issue with rendering title

### ISSUE THREAD

**Issue by pwujek** [percolatestudio/atmosphere#114]
for the page https://atmospherejs.com/packages/File%2520Upload
the title displays on the page  as:
'File$20Upload'
rather than:
'File Upload'

**Comment by tmeasday** [comment]
Is that an error? Can I ask how you came by that link?

**Comment by pwujek** [comment]
I did that earlier in the day and now when I try to re-create it I can't get there.
I believe I got there by doing a search, but the main search doesn't do that.

**Comment by tmeasday** [comment]
Ok, well let me know if you are able to reproduce it.
