### ISSUE TITLE
Relatively linked pictures don't load on atmosphere

### ISSUE THREAD

**Issue by mizzao** [percolatestudio/atmosphere#116]
For example, compare the PNG image in

> https://github.com/mizzao/meteor-partitioner

with

> https://atmospherejs.com/package/partitioner

These broken links also occur with

> https://github.com/mizzao/meteor-tutorials

**Comment by tmeasday** [comment]
Can you just use absolute URLs for the images? It's going to be tricky for us to fix this I would have thought.

**Comment by mizzao** [comment]
I actually switched from absolute to relative URLs because I read a GitHub article about how linking to absolute URLs made it harder for users who fork the repo to have the link working, etc.: https://help.github.com/articles/relative-links-in-readmes

So I'll just accept the broken pics for now and wait for whenever you guys manage to get this fixed.

**Comment by mizzao** [comment]
The relative links to History.md and docs on iron-router don't load: 

https://atmospherejs.com/package/iron-router

It's impossible for everyone to use absolute links. So we'll need to fix this at some point :)

**Comment by tmeasday** [comment]
Any idea how to set the base url on a section of the DOM? As far as I can tell it's impossible.

Sadly the next best idea is probably using an iframe for this..

**Comment by mizzao** [comment]
Is rewriting the links not a possibility? What is being used to generate the page from Markdown; could you hook into that?

**Comment by tmeasday** [comment]
Rewriting links (and images) is possible but feels like the kind of thing that tends to have a lot of edge cases and ends up causing issues.

@zol - any thoughts about this? My idea was to include an iframe that served up something like http://atmospherejs.com/package/foo/README -- which would render the README with the correct CSS but sets the `<base>` element to point to the github page for the package.

**Comment by zol** [comment]
@tmeasday sounds like a good plan re: the iFrame.

**Comment by mizzao** [comment]
It looks like this has been fixed!

**Comment by mizzao** [comment]
Eh, just kidding. I was looking at an absolute link accidentally.

**Comment by tmeasday** [comment]
@mizzao - heh :) Well I'm glad you got excited for a sec there.

**Comment by dandv** [comment]
+1. New Meteor users are being [confused about this on SO](http://stackoverflow.com/questions/26684493/rendered-event-not-firing-in-meteor?noredirect=1#comment42028862_26684493).

**Comment by udondan** [comment]
> Rewriting links (and images) is possible but feels like the kind of thing that tends to have a lot of edge cases and ends up causing issues. 

I understand the concerns, but I suggest to take a look at how npm is doing it: https://github.com/npm/npm-www/blob/master/models/package.js#L13

They use [sanitizer](https://www.npmjs.org/package/sanitizer) and pass a custom urlPolicy as 2nd parameter to it.

What works for npm with 104k packages should work for 2,5k on Meteor/Atmosphere as well. :)

**Comment by numtel** [comment]
+1 Still affecting readme with links to relative markdown files. Please fix this!

```
if(url.indexOf('//') === -1) url=prependGithub(url);
```

**Comment by zol** [comment]
This will be fixed by #339

**Comment by zol** [comment]
This is (finally) fixed. Thanks for your patience.

**Comment by mizzao** [comment]
Thank you!
