### ISSUE TITLE
I wish I could save my favorite packages here

### ISSUE THREAD

**Issue by timbrandin** [percolatestudio/atmosphere#117]
That would be epic!

**Comment by domyen** [comment]
@timbrandin I think it'd be cool as well! 

I'm curious, in what situations would you use it and what would you like to do with it?

**Comment by timbrandin** [comment]
Hi Dominic,

It would be nice for them to show up as starred in the search result or why not always show them directly when no search has been done yet and the search window is open. I can't always remember which module I've used you know, especially the machine name for it to add it to my projects.

And it would be a nice way of promoting content I guess. :)

Best regards,
// Tim, Sweden

Skickat från min iPhone

**Comment by timbrandin** [comment]
Oh and one more thing,

let's say I found this package which looks promising but not yet ready for
production.
I would love for a feature like star on this one, then one could get
notifications to updates on that package.
Or why not a summary of the changes to the packages I've starred when one
is logged in on atmosphere.

Best regards
// Tim

2014-04-10 14:32 GMT+02:00 Tim Brandin tim.brandin@gmail.com:

> Hi Dominic,
> 
> It would be nice for them to show up as starred in the search result or
> why not always show them directly when no search has been done yet and the
> search window is open. I can't always remember which module I've used you
> know, especially the machine name for it to add it to my projects.
> 
> And it would be a nice way of promoting content I guess. :)
> 
> Best regards,
> // Tim, Sweden
> 
> Skickat från min iPhone
> 
> 9 apr 2014 kl. 19:25 skrev Dominic Nguyen notifications@github.com:
> 
> @timbrandin https://github.com/timbrandin I think it'd be cool as well!
> 
> I'm curious, in what situations would you use it and what would you like
> to do with it?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/percolatestudio/atmosphere-beta/issues/117#issuecomment-39991825
> .

## 

Med vänliga hälsningar
// Tim Brandin @timbrandin https://twitter.com/#!/timbrandin
http://sypreme.se

**Comment by domyen** [comment]
Closing this. We're tracking this issue on: https://github.com/percolatestudio/atmosphere-beta/issues/57
