### ISSUE TITLE
Use FastRender to avoid "undefined" in the title

### ISSUE THREAD

**Issue by rynti** [percolatestudio/atmosphere#118]
#### Problem

Whenever you refresh a page or load an Atmosphere page for the first time, the title is kind of messed up, saying for instance _undefined_ on package detail pages, where instead the package name should be. This is due to the fact that the client does not yet have any package data loaded during the initial page load, this will only happen after the page loaded and the client subscribes to published data.
#### Solution

The problem of no collection data being available on the client upon the initial page load can be easily avoided by using [FastRender](http://meteorhacks.com/fast-render/) ([GitHub repository](https://github.com/arunoda/meteor-fast-render)).

FastRender seems to be stable and is well integrated with IronRouter. It works by not only defining the routes on the client-side, but on the server-side as well. You can then specify which subscriptions are needed on given routes, which allows FastRender to send the necessary collection data directly with the initial page request.

Please give FastRender a try, the user experience of Atmosphere would definitely benefit from it, and setting the routes up is something that should only take a few minutes.

**Comment by dburles** [comment]
Hey @rynti thanks for the suggestions, since you posted this issue I'm pretty sure that the 'undefined' problem has now been resolved with the loading animation.

**Comment by dburles** [comment]
Sorry, realised you were talking specifically about the page title! reopening..

**Comment by dburles** [comment]
Fixed
