### ISSUE TITLE
Keyboard shortcuts inactive on page load

### ISSUE THREAD

**Issue by domyen** [percolatestudio/atmosphere#12]
Reproduce by navigating to Atmosphere and pressing 'a'[menu] or 's'[search]. If you click on a blank area of the page and then press these keys the intended functionality works.

**Comment by tmeasday** [comment]
Not seeing this. Which browser? I'm doing:
1. Open new window in chrome
2. Type localhost:3000 in url bar, hit enter
3. Wait a moment, then hit 's'

It appears to work fine.

**Comment by domyen** [comment]
Turns out that this can't be reproduced.

**Comment by domyen** [comment]
Ok this can be reproduced in Saf, Chrome, and FF. 
1. login to github via the feedback form
2. reload page
3. type 's' or 'a' via the keyboard
4. open up the feedback form to see that you've just typed into the title field of the feedback form

Should we blur inputs?

**Comment by domyen** [comment]
Fixed as of d122a616bb8dac8dcc8f43cb2ca82efe58d6e1d8
