### ISSUE TITLE
packages appearing more than once on recent items

### ISSUE THREAD

**Issue by serkandurusoy** [percolatestudio/atmosphere#121]
I don't know if consistently https://atmospherejs.com/package/jquery-smart-wizard this one or if it happens to others as well, but it seems some packages appear twice (not necessarily side by side) in the recent items list.

**Comment by tmeasday** [comment]
Hmm.. not seeing it here.. how odd.. Perhaps the order changed while you were looking through it?

**Comment by serkandurusoy** [comment]
I think there is another problem here. Or maybe that, but certainly reproducible. For example, I can now see the user-stream package twice. (and this time side by side).
![image](https://cloud.githubusercontent.com/assets/4649948/2679366/7bac14ce-c171-11e3-89ba-7731b7a771d5.png)

**Comment by tmeasday** [comment]
Ok, there are two version of user-stream, same problem as #131. Not sure about the other one.

Will remove dupes when I get a second. I'll close this and track it there.

**Comment by serkandurusoy** [comment]
Bump! Here's a screenshot from just now:

![screenshot from 2014-05-27 19 01 19](https://cloud.githubusercontent.com/assets/4649948/3094078/805ff3bc-e5b8-11e3-8cc1-a64e4df7e644.png)

Could this be a _slow connection_ problem, perhaps?
