### ISSUE TITLE
We should have case insensitive package naming

### ISSUE THREAD

**Issue by serkandurusoy** [percolatestudio/atmosphere#122]
There are packages with the same name but different case, which makes it confusing to track packages.

For example: https://atmospherejs.com/package/Famous and https://atmospherejs.com/package/famous

**Comment by tmeasday** [comment]
Oh! As it turns out both of those packages are deleted but we aren't hiding them..

**Comment by serkandurusoy** [comment]
I don't see them any more.

**Comment by mizzao** [comment]
Have you accidentally hidden a billion other packages as well?

https://atmospherejs.com/package/sharejs -> https://github.com/mizzao/meteor-sharejs
https://atmospherejs.com/package/fast-render -> https://github.com/arunoda/meteor-fast-render
https://atmospherejs.com/package/partitioner -> https://github.com/mizzao/meteor-partitioner

Methinks whatever fix was attempted here caused #129 and #130.

**Comment by tmeasday** [comment]
No it was unrelated, but it's a reasonable theory.

@serkandurusoy to your original point -- you'll need to take this up with MDG :)
