### ISSUE TITLE
missing dates on recent list

### ISSUE THREAD

**Issue by serkandurusoy** [percolatestudio/atmosphere#123]
On the new recent view, there is no indicator about when the package was released/updated until it is opened

**Comment by tmeasday** [comment]
Good point @serkandurusoy !

**Comment by dburles** [comment]
close?

**Comment by tmeasday** [comment]
Just wanted @dominicnguyen to take a look..

**Comment by domyen** [comment]
Yes, we should be displaying the recent package-type on the recent page. So the time should render next to the author like so:
![screenshot 2014-05-12 09 50 49](https://cloud.githubusercontent.com/assets/263385/2947367/992cc088-d9f5-11e3-9002-fa476cec8549.png)

**Comment by serkandurusoy** [comment]
Nope! Still not visible on https://atmospherejs.com/recent

Sent from my iPhone

On Jul 16, 2014, at 19:37, Dominic Nguyen notifications@github.com wrote:

Closed #123.

**Comment by domyen** [comment]
We haven't deployed this fix yet.
