### ISSUE TITLE
Meteor Twitter Api Fixed

### ISSUE THREAD

**Issue by jamesfebin** [percolatestudio/atmosphere#126]
I have fixed the Meteor Twitter Api .. 
Here is the fixed git repo.
https://github.com/jamesfebin/meteor-twitter-api

**Comment by tmeasday** [comment]
Hey @jamesfebin - you'll need to wait for the author to accept your PR or publish your own version of the package I guess.

The official package solution as of 0.9.0 will have a better way to deal with this problem.
