### ISSUE TITLE
Guidelines for repackaging 3rd party packages

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#127]
The [Publishing docs](https://atmospherejs.com/docs/publishing) should have a section on Packaging existing libraries, linking to http://www.meteorpedia.com/read/Packaging_existing_Libraries

Thanks!

**Comment by tmeasday** [comment]
@dandv I think [this](https://meteor.hackpad.com/Getting-Started-With-Unipackage-IOckQBQgXaQ) is the right place to take this conversation.

**Comment by dandv** [comment]
Updated the OP - we just need to link to Meteorpedia.
