### ISSUE TITLE
mrt publish problem from repo cloned

### ISSUE THREAD

**Issue by stefanocudini** [percolatestudio/atmosphere#128]
"mrt publish ." not work by clone of my repo: 
https://atmospherejs.com/package/leaflet-search

```
$ mrt publish .
Error: That ain't yr package son!
```

My pkg files is right? Why not work publish action..? O.o
First time I'm using mrt publish from source directory.. afterwards I'm cloning from github and the next publish.. not work!

**smart.json**

```
{
    "name": "leaflet-search",
    "description": "Leaflet Control for searching markers/features by attribute on map or remote searching in jsonp/ajax",
    "homepage": "http://labs.easyblog.it/maps/leaflet-search/",
    "author": "Stefano Cudini <stefano.cudini@gmail.com>",
    "version": "1.5.0",
    "git": "https://github.com/stefanocudini/leaflet-search.git"
}
```

**package.json**

```
{
  "name": "leaflet-search",
  "version": "1.5.0",
  "description": "Leaflet Control for searching markers/features by attribute on map or remote searching in jsonp/ajax",
  "repository": {
    "type": "git",
    "url": "git@github.com:stefanocudini/leaflet-search.git"
  },
  "homepage": "http://labs.easyblog.it/maps/leaflet-search/",
  "author": {
    "name": "Stefano Cudini",
    "email": "stefano.cudini@gmail.com",
    "url": "http://labs.easyblog.it/"
  },
  "license": "MIT",
  "keywords": [
    "gis",
    "map",
    "leaflet"
  ],
  "dependencies": {
    "leaflet": "*"
  },
  "devDependencies": {
    "grunt": "~0.4.2"
  }
}
```

**Comment by tmeasday** [comment]
Are you logged into atmosphere as the right user on the command line?

**Comment by stefanocudini** [comment]
In the new layout atmospherejs.com I do not see any button to login, I'm looking from some time..

**Comment by stefanocudini** [comment]
and..

```
$ mrt login
/opt/node/lib/node_modules/meteorite/bin/mrt.js:21
  throw("Subcommand " + subCommandName + " does not exist!");
                                       ^
Subcommand login does not exist!
```

I don't understand how works auth system in atmosphere...
First time remember that I'm signup by Github my account

**Comment by tmeasday** [comment]
Hey @stefanocudini - sorry the situation is a bit confusing right now.

You can login [here](http://atmosphere.meteor.com/accounts) to your Meteorite account. 

If you are logged in to the wrong account on the command line, you'll need to delete your `~/.mrt.cfg` file. Let me know if that helps.

**Comment by stefanocudini** [comment]
yes! Now publishing work!

I do not know if I just have not found it, but you should put a button to login in new layout

however congratulations it's beautiful!
