### ISSUE TITLE
package disappeared from atmosphere suddenly?

### ISSUE THREAD

**Issue by vectorselector** [percolatestudio/atmosphere#130]
the meteor-partitioner package has disappeared from atmosphere, literally overnight.
https://github.com/mizzao/meteor-partitioner
showing a 404 at https://atmospherejs.com/package/partitioner

that and this new, unbrowseable atmosphere is a PITAS and useless generally, unless you like playing the lottery. There is no way to explore the trove. Do you folks own mad google stock or something, because that's the only way i can find any packages these days. 

Thanks

**Comment by mizzao** [comment]
Actually, if you look at https://atmospherejs.com/ right now, it would seem that nothing has been updated since April 11th. Must be some backend problem.

It also seems that the code for the atmosphere site itself has been removed from GitHub...

**Comment by tmeasday** [comment]
Yes, the metadata syncing got out of whack there for a bit. Should be ok now.

@vectorselector you can browse packages exactly as you did in the old site here: https://atmospherejs.com/recent

**Comment by tmeasday** [comment]
@vectorselector - are you saying that the built in search isn't finding what you need? Is that because you are searching for more generic terms rather than specific things that are mentioned in packages?
