### ISSUE TITLE
Duplicate search results

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#131]
https://atmospherejs.com/?q=getters shows the same package by @jonjamz twice:

![image](https://cloud.githubusercontent.com/assets/33569/2713936/79314b1c-c4ee-11e3-8e8c-1e02bf3d211a.png)

**Comment by tmeasday** [comment]
Whoa. Thanks @dandv - we seem to have synced a couple of dupes. Will get rid of them.
