### ISSUE TITLE
That ain't yr package son error

### ISSUE THREAD

**Issue by stephentcannon** [percolatestudio/atmosphere#135]
Trying to release a package upgrade of single-page-login that works with Meteor 0.8.0 and iron-router 0.7.1.

First attempt meteorite asked me for a  login and password and I don't remember that prior.  

I don't remember having an atmosphere/meteorite account prior.  So, I signed up on the https://atmosphere.meteor.com/accounts and then associated this new account with my Meteor Developer account.

Then I tried to release the updated package.  Term asked me for username...see below and then said that it isn't my package.

I do not remember having a login prior or associating this package with any login prior.  I might have.  So, I do apologize.

Please help so I can upgrade this package for people using latest Meteor and iron-router.

username:  steeve
password:  
Error: That ain't yr package son!

**Comment by tmeasday** [comment]
Hi @stephentcannon - the username that you've used for that package is `steevecannon`. Maybe try logging in with that account? Otherwise I can add your new account as a maintainer..

**Comment by tmeasday** [comment]
@stephentcannon - how did you go with this?

**Comment by stephentcannon** [comment]
Tom, will take a look at it later this week.  Sorry been distracted.

On Mon, Apr 28, 2014 at 12:56 AM, Tom Coleman notifications@github.comwrote:

> @stephentcannon https://github.com/stephentcannon - how did you go with
> this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/percolatestudio/atmosphere-beta/issues/135#issuecomment-41523014
> .

## 

Thanks
Stephen Cannon
Mobile: 727.386.6298
Fax: 727.608.4512
stephentcannon@gmail.com
http://www.debitelite.com/

**Comment by stephentcannon** [comment]
Tom,
1.  I do not remember the password for the account: steevecannon
2.  The old site where the login does not have a password reminder feature.

On Mon, Apr 28, 2014 at 1:14 AM, Stephen Cannon stephentcannon@gmail.comwrote:

> Tom, will take a look at it later this week.  Sorry been distracted.
> 
> On Mon, Apr 28, 2014 at 12:56 AM, Tom Coleman notifications@github.comwrote:
> 
> > @stephentcannon https://github.com/stephentcannon - how did you go
> > with this?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/percolatestudio/atmosphere-beta/issues/135#issuecomment-41523014
> > .
> 
> ## 
> 
> Thanks
> Stephen Cannon
> Mobile: 727.386.6298
> Fax: 727.608.4512
> stephentcannon@gmail.com
> http://www.debitelite.com/

## 

Thanks
Stephen Cannon
Mobile: 727.386.6298
Fax: 727.608.4512
stephentcannon@gmail.com
http://www.debitelite.com/

**Comment by tmeasday** [comment]
Hey @steeve — I added your steeve account as a maintainer of that package, so you should be able to publish it now.

**Comment by steeve** [comment]
I think you guys got the wrong @steeve :)

**Comment by tmeasday** [comment]
Oh. My bad, sorry @steeve

**Comment by stephentcannon** [comment]
Tom

i am stephentcannon on gh

steeve on meteor.com accounts

On Wed, Apr 30, 2014 at 11:17 PM, Tom Coleman notifications@github.comwrote:

> Oh. My bad, sorry @steeve https://github.com/steeve
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/percolatestudio/atmosphere-beta/issues/135#issuecomment-41876171
> .

## 

Thanks
Stephen Cannon
Mobile: 727.386.6298
Fax: 727.608.4512
stephentcannon@gmail.com
http://www.debitelite.com/

**Comment by tmeasday** [comment]
@stephentcannon - did you sort out the package?

**Comment by stephentcannon** [comment]
Seems that way.  I can publish updates to it.

**Comment by jsep** [comment]
@tmeasday I have the same issue,  the package is [munit](http://atmospherejs.com/package/munit) i've published the package under the user `juan-lavaina` and also I don't remember the password, how I can reset it?

**Comment by tmeasday** [comment]
Hi @juan-spacejam - email me at tom@percolatestudio.com to work it out.
