### ISSUE TITLE
Search Overlay: Animation refinement

### ISSUE THREAD

**Issue by domyen** [percolatestudio/atmosphere#137]
Get to the bottom of the animation performance on the search overlay. When the search overlay has no results the animation is consistent and reliable.  When there are results the animation get's choppy.

Question: does the template re-render when triggering the overlay?

**Comment by tmeasday** [comment]
Ok, @dominicnguyen I think (read: hope) this is fixed in devel. Can you take a look, and make sure it's still behaving OK..

**Comment by domyen** [comment]
@tmeasday The overlay animates a lot better. I removed the scale from the animation to improve performance further. 

Bug: when trying to pull up the search results set again, the .module-loading class is not removed.
Repro: 
1. Search 'fa'
2. Click on search result
3. Pull up overlay again
4. see grey boxes in place of packages

![screenshot 2014-04-28 05 50 39](https://cloud.githubusercontent.com/assets/263385/2817063/c4b1906c-ced3-11e3-9c4c-6b58304b2c80.png)

**Comment by tmeasday** [comment]
OK, fixed I think @dominicnguyen

**Comment by domyen** [comment]
Confirmed. Ty @tmeasday
