### ISSUE TITLE
I'd love an admin panel for managing my packages

### ISSUE THREAD

**Issue by gjolund** [percolatestudio/atmosphere#138]
I have a ton of old packages that I'd like to remove, and it would be nice to see some more in depth analytics on the types of apps using my packages ( versions, environments, etc )

**Comment by tmeasday** [comment]
Sure would! ;)

**Comment by gjolund** [comment]
I'm planning on being at your SF talk on the 20th, maybe we can mind meld for a minute an come up with something that will work.

**Comment by domyen** [comment]
Sounds good @austinrivas. We're on standby for the official MDG package backend to do a user-accounts push.

**Comment by domyen** [comment]
Added to the [roadmap](https://trello.com/b/RDZR8YGF/atmosphere-flight-path) & closing.
