### ISSUE TITLE
remove private/non existent packages from atmosphere

### ISSUE THREAD

**Issue by rzymek** [percolatestudio/atmosphere#146]
I came across a package that probably was changed to private on github: ogno-cart. Github shows 404, mrt asks for github user/pass on install.

Automatic checking of repository urls would be nice. Alternatively  a way to mark a package as not longer available.

**Comment by tmeasday** [comment]
@matteodem - can you make the repo public or delete the package from atmosphere via atmosphere.meteor.com/wtf/maintain ?

**Comment by tmeasday** [comment]
ping @matteodem?

**Comment by domyen** [comment]
We're working on a flagging feature to address this challenge! It's being tracked against this [issue](https://github.com/percolatestudio/atmosphere-beta/issues/68). Closing this.

**Comment by matteodem** [comment]
I really don't know how I didn't notice this, sorry for that.
