### ISSUE TITLE
Make it possible to search from the addressbar

### ISSUE THREAD

**Issue by timbrandin** [percolatestudio/atmosphere#148]
For example if one types wikipedia.com[tab] on gets directly the possibility to search on wikipedia.

In chrome I can add it myself, but one should not need to.
chrome://settings/searchEngines

**Comment by timbrandin** [comment]
Here's some hints on this trail.. 
http://webmasters.stackexchange.com/questions/44452/making-a-site-searchable-via-chrome-search-bar

**Comment by timbrandin** [comment]
And even better, if I know the name of the package I wanted to read about it could go directly to that page. :+1: Like for example http://atmospherejs.com/package/iron-router

**Comment by SeriousM** [comment]
:+1:

**Comment by tmeasday** [comment]
Seems like a good idea to me :)

**Comment by tmeasday** [comment]
Done. @dominicnguyen to test: hit the devel site, then type "localhost<tab>" into the addressbar. It can be bit finicky as to when it comes up but it appears to work.

**Comment by timbrandin** [comment]
Can't wait to see this live. @tmeasday

**Comment by SeriousM** [comment]
Is http://beta.atmospherejs.com/ the testing site?

**Comment by domyen** [comment]
lgtm
