### ISSUE TITLE
Atmosphere down relatively often lately?

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#149]
Just saw this:

![image](https://cloud.githubusercontent.com/assets/33569/2897244/6852420e-d57b-11e3-99ac-18b0e9084113.png)

**Comment by domyen** [comment]
We've taken action to prevent Atmosphere outages in the future and are investigating possible causes.

**Comment by tmeasday** [comment]
Apologies for this. We identified a pretty low level issue with Meteor (https://github.com/meteor/meteor/issues/2299). It took some time to track it down to that.
