### ISSUE TITLE
Unable to publish new version of the package

### ISSUE THREAD

**Issue by ivanbrykov** [percolatestudio/atmosphere#152]
Hi!

I have created my <a href="https://github.com/brykov/meteor-multiple-callbacks">first Atmosphere package</a> and was able to publish its first version.

After few improvements I made new commit, pushed it, added new tag and pushed it, too:

```
git tag -a v0.1.1 -m "v0.1.1"
git push origin --tags
```

After that I tried to release my changes to Atmosphere:

```
mrt release multiple-callbacks
```

But I got the error:

```
Adding tag and pushing repo
Error: That's not a new version of the package!
```

Any chance to figure out why it happens?

**Comment by tmeasday** [comment]
Hi Ivan,  

You need to add the new version to `smart.json`.

Cheers,
Tom

**Comment by ivanbrykov** [comment]
oh.. damn it.
I killed nearly 2 hours on that.
I guess it would be nice to add a topic to this article https://atmospherejs.com/docs/publishing about releasing new version.
