### ISSUE TITLE
Downloads/hotness graph is not clear on what it's indicating

### ISSUE THREAD

**Issue by hharnisc** [percolatestudio/atmosphere#153]
I see a graph associated with every package but it's a mystery on what it's actually indicating.  The graph also seems to change scale for seemingly no reason.  It would be nice if we could get some idea of scale or even what figures into the calculation.  Right now it's at least as mysterious as a credit score.

**Comment by hharnisc** [comment]
Thank you guys for this: 

http://blog.percolatestudio.com/engineering/atmosphere-score/

Very enlightening!

**Comment by tmeasday** [comment]
Hey, no worries :)
