### ISSUE TITLE
Publishing and incorrect username/password combo soils current version number

### ISSUE THREAD

**Issue by davidworkman9** [percolatestudio/atmosphere#154]
I pushed a new version number to my package and did a `mrt release .` I was then prompted for my username/password which I got wrong my first try. Then when I went to try again it told me that tag had already been committed to the repo. Asking for username/password combo first would be really handy in preventing these kind of problems.

**Comment by tmeasday** [comment]
Hi @davidworkman9 - `mrt release` just does `mrt publish` plus pushing git tags. So if you get halfway through and it fails, you can try again with `mrt publish .`.

**Comment by davidworkman9** [comment]
Thanks!
