### ISSUE TITLE
rm nvd3 package

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#156]
https://atmospherejs.com/package/nvd3 - repor made private, as complained by [another package](https://atmospherejs.com/package/meteor_nvd3). Releasing the namespace would be nice.

**Comment by domyen** [comment]
Closing package index issues because Meteor 0.9.0 now manages the package index. 
Folks can request the ability to remove packages to the Meteor [roadmap](https://trello.com/b/hjBDflxp/meteor-roadmap) or [meteor-talk group](https://groups.google.com/forum/#!forum/meteor-talk).
