### ISSUE TITLE
Cannot publish new versions of older packages

### ISSUE THREAD

**Issue by gjolund** [percolatestudio/atmosphere#157]
I am locked out of several of my packages that were created over a year ago.

I am continuously receiving a message saying the package does not belong to me.

I've mentioned this a few other times on here and received no response, and without a way to delete old packages I'm kind of stuck.

The package that brought this issue to light again is `flot`, but I have atleast 3-4 other packages experiencing the same issue.

**Comment by tmeasday** [comment]
Hi @austinrivas 

That package (`flot`) is owned by a user w/ username `austinrivas@gmail.com`. Perhaps you are logged in as the wrong user? You can "log out" by removing the file `~/.mrt.cfg`.

**Comment by gjolund** [comment]
Hmm that's strange,

Do you mind checking if that is the same username as my `jquery-datatables` package?

`flot` is ancient, one of my first forays into writing packages over a year ago, but was developed on the same machine.

**Comment by tmeasday** [comment]
Hmm, no the jquery-datatables package is owned by “austinrivas"

**Comment by gjolund** [comment]
Yeah I think the issue is that I created those packages back before the
atmosphere users schema was solidified. Is there any way that you can
migrate the packages owned by austinrivas@gmail.com to austinrivas?

**Comment by tmeasday** [comment]
Ok. I’ve added `austinrivas` as an maintainer of all the packages that are owned by `austinrivas@gmail.com`. Let me know if that solves your problems.

**Comment by gjolund** [comment]
thanks a ton @tmeasday, I'll test this asap
