### ISSUE TITLE
Duplicate & unpublish packages

### ISSUE THREAD

**Issue by udondan** [percolatestudio/atmosphere#158]
I see there are several tickets for duplicate packages or the question how to unpublish a package. Instead of replying to one of those tickets let me create an umbrella ticket so we can get a general answer/solution.

**Duplicate packages:**
This happened for me for 3 of my 4 packages I created. So it seems this is a general problem recently. The one package where it didn't happen, was created a few days before the others.

I was able to remove those duplicates myself, by going to the old site and deleting the package:

``` js
 Meteor.call('deletePackage', 'mypackage');
```

Though my intend actually was to delete the package completely. Which brings us to:

**Delete/Unpublish package:**
How is it possible? Is it possible? `Meteor.call('deletePackage', 'mypackage');` does not work on the new site and on the old site it only deletes the duplicate. The packages I want to delete are not visible on the old page, since I already deleted them and running `Meteor.call('deletePackage', 'mypackage');` again doesn't do anything.

Is there a similar Meteor function availalbe on the new site?

And if it is currently not possible to unpublish myself, please someone can take care of these?:
- node-zip
- meteor-zipzap

My guess from outside what is happening here is, when you publish a package via `mrt release` it gets written to 2 different databases, the old and the new site. Both entries have a different `_id`. Then it looks like you have a sync, only from old to new site, which adds the duplicate. Deleting the entry on the old site gets synced to the new site, but since there is the duplicate entry with different `_id` that one can't be deleted via the old site.

**Comment by tmeasday** [comment]
Hi @udondan,

Thanks for reporting this.

The issue you are seeing is as follows:
1. You are correct that there are two databases -- the old site and the new one.
2. For some reason, occasionally packages that are added to the old site appear twice in the new one. This must be something stupid we are doing -- or possibly a problem with Meteor's upsert implementation.
3. When you delete the package on the old site, we only pick it up once, thus you end up never being able to delete both copies.

Anyway, we'll look at fixing up 2. In the meantime, let me know any packages you have that are duplicated.

**Comment by udondan** [comment]
Thanks @tmeasday, it didn't happen for me again yet. Any plans to implement a delete function in the new site as well? Seems like a small addition which could save you some time deleting packages :)

**Comment by tmeasday** [comment]
Hey @udondan - we'll hold out implementing features like this on the new site until we know if we'll be able to do it with the new MDG hosted packaging solution. We wouldn't want to add the feature and then have to take it away again :)

**Comment by udondan** [comment]
I see, that makes sense. Thanks for explaining!
