### ISSUE TITLE
Shared access to packages

### ISSUE THREAD

**Issue by alanning** [percolatestudio/atmosphere#159]
Let package owners add collaborators who can also push updates to atmosphere for that package.

We tried the method [suggested here](https://atmosphere.meteor.com/wtf/maintain) to add a maintainer but it doesn't work:  `Meteor.call('addPackageMaintainer', 'jasmine-unit', 'alanning');`

Any suggestions on what it would take to get this going?  I can help out with the implementation if needed.

**Comment by queso** [comment]
+1

**Comment by xolvio** [comment]
+1

**Comment by tmeasday** [comment]
@alanning - what went wrong? Try doing it with a callback (`function(err) { console.log(err); }`) and let me know if there was a specific error..

**Comment by xolvio** [comment]
I just tried this and I think it worked. A few hours ago the console was showing a 404 for both `addPackageMaintainer` and `deletePackage`, but now it shows undefined for addPackageMaintainer and 'Package removed' for deletePackage

**Comment by alanning** [comment]
Nice!  I successfully pushed the latest version of the `jasmine-unit` package to atmosphere.

Sam, I think before we were trying it from the old https://atmosphere.meteor.com site (where the instructions are).  This last time, did you do it on the new https://atmospherejs.com site?  Maybe that's the difference?

**Comment by tmeasday** [comment]
@alanning - you need to do it on the old site. But maybe you tried it on the new one?

**Comment by xolvio** [comment]
I'm pretty sure I tried it on both, but I'm willing to be corrected :)

So I deleted velocity-jasmine-unit like this:

```
Meteor.call('deletePackage', 'velocity-jasmine-unit', function() {console.log(arguments)})
[undefined, "Package removed"] 
```

But then going to https://atmospherejs.com/?q=velocity-jasmine-unit still shows it's there. Does it take time to be removed? I did this 4 hours or so ago

**Comment by tmeasday** [comment]
How odd. It must not have synced across properly. Anyway, it’s deleted now.
