### ISSUE TITLE
mrt release does not terminate

### ISSUE THREAD

**Issue by softwarerero** [percolatestudio/atmosphere#160]
```
meteor-accounts-t9n 555 $ mrt release .
Adding tag and pushing repo
```

This can run for hours without finishing. When I do Ctrl+C and try it again I get:

```
/usr/local/lib/node_modules/meteorite/lib/atmosphere.js:83
          throw "This tag has already been committed to the repo.";
```

I had this before and after some tries it worked but today I am incrementing versions all day but nothing lands on Atmosphere.
1. Is there a problem with Atmosphere or on my side?
2. How can I avoid producing so many versions because `release` was unsuccessful?

**Comment by tmeasday** [comment]
1. Yes, it was an issue with Atmosphere, resolved now.
2. You can use `mrt publish .` to allow you to try and publish the same release again. `mrt release` is just a convenience to do the git tagging for you.
