### ISSUE TITLE
Can't publish package

### ISSUE THREAD

**Issue by christianbundy** [percolatestudio/atmosphere#161]
I've tried `mrt publish` which looks like it works, but it doesn't actually show up on the new Atmosphere site (although it shows on the old site). What should I do to troubleshoot?

**Comment by tmeasday** [comment]
Metadata isn't syncing right at this moment due to some server issues. To check it worked, try `mrt add X` for your package into a brand new meteor project.

**Comment by christianbundy** [comment]
Totally worked, I just wanted to make sure I didn't have to do anything else to get it on the site. Thanks, I'll close this!
