### ISSUE TITLE
Atmosphere package version not updating

### ISSUE THREAD

**Issue by udondan** [percolatestudio/atmosphere#162]
I just pushed a new version of my package `contact`. No problems with that:

``` sh
~/meteor-contact$ mrt release .
Adding tag and pushing repo
```

Tag was created on github, as set in my `smart.json`: v0.2.0

On [Atmosphere](https://atmospherejs.com/package/contact) the current version is still listed as 0.1.6.

Though when installing the package via `mrt` it is using the recent version 0.2.0:

``` sh
~/meteor-contact-demo$ mrt add contact
✓ contact
    tag: https://github.com/udondan/meteor-contact.git#v0.2.0
```

I waited some time now and reloaded the page multiple times (yes, I know it's reactive and updates immediately :)) but nothing changes.

It's not a real problem to me for my tiny package but it could be a problem for people looking for updates for a(nother) package on the website, not seeing the new version and then not running `mrt update`.

**Comment by tmeasday** [comment]
Hey @udondan - syncing between the old and new site was down for a little bit. Should be good now.

**Comment by udondan** [comment]
Yep, looks good now. Thanks :)
