### ISSUE TITLE
Can't release package that I co-author

### ISSUE THREAD

**Issue by christianbundy** [percolatestudio/atmosphere#165]
I'm the co-author of the harmony package in smart.json, how do I release a new version of the package to Atmosphere? I'm getting:

```
Error: That ain't yr package son!
```

Thanks!

**Comment by tmeasday** [comment]
Hi @christianbundy - have you been added to the project as a maintainer as detailed here: https://atmosphere.meteor.com/wtf/maintain ?

**Comment by christianbundy** [comment]
I haven't, thanks! Is that supposed to be run in the console on atmospherejs.com by the current author?

**Comment by tmeasday** [comment]
On the old site. It's a bit janky but a short term solution.

**Comment by christianbundy** [comment]
Not a problem at all, thanks @tmeasday!
