### ISSUE TITLE
Multiple authors

### ISSUE THREAD

**Issue by mquandalle** [percolatestudio/atmosphere#166]
In harmony [smart.json](https://github.com/mquandalle/meteor-harmony/blob/master/smart.json), we define two (co-)authors, but there is only one displayed [on atmosphere](https://atmospherejs.com/package/harmony), so that's a bug :-)

Note that this field has been modified after the first release.

**Comment by tmeasday** [comment]
You are correct in guessing the problem is that the field changed since initial release. Not a great system right now.

**Comment by domyen** [comment]
This appears to be resolved. Closing.
