### ISSUE TITLE
Cannot sign in / reset password

### ISSUE THREAD

**Issue by subhog** [percolatestudio/atmosphere#167]
`mrt` asked me for a password when trying to update a package. I recall setting one up on atmosphere, but now there's no option to sign in / reset / change password.

**Comment by udondan** [comment]
Accounts are not yet in the new atmosphere. You an manage your account on the old page: https://atmosphere.meteor.com/accounts But take care where you click, most links redirect to the new page now.

**Comment by tmeasday** [comment]
Yes! Sorry about the confusion but it's (hopefully) a very short term situation.

**Comment by subhog** [comment]
Got it, thanks.
