### ISSUE TITLE
shows removed dependancies in the package listing

### ISSUE THREAD

**Issue by pahans** [percolatestudio/atmosphere#168]
I have removed `bootstrap-3` dependancy in `0.1.2` release in my  ['reactive-modal'](https://atmospherejs.com/package/reactive-modal) package. But in the Atmosphere page it is still showing that my package has a `bootstrap-3` dependancy.

**Comment by tmeasday** [comment]
Hi @pahans 

This is a bit of a bug with Meteorite/Atmosphere. I _think_ if you publish a version of the package with a _empty_ `packages: {}` declaration (as opposed to none at all), it'll clear this info from the package.

**Comment by tmeasday** [comment]
@pahans any luck?

**Comment by pahans** [comment]
@tmeasday  yes,  empty `packages: {}` worked for me.

**Comment by tmeasday** [comment]
Great!
