### ISSUE TITLE
I don't like I have to repair permissions every once a while

### ISSUE THREAD

**Issue by timbrandin** [percolatestudio/atmosphere#169]
For example when a package needs sudo to install it's npm dependencies, things gets screwed up. Sorry for the language, I love atm but this is important.

**Comment by tmeasday** [comment]
Hey @timbrandin -- it sounds like perhaps you have problems with permissions on your machine? Two things:
1. I never need to use sudo to run `mrt` or `meteor`
2. If a package installs an npm package, that's Meteor, not anything to do with Meteorite. You can confirm this by just using `mrt install`, and actually running `meteor` when you want to start your app.

**Comment by udondan** [comment]
I think this is a general npm problem. I used to have an account w/o admin role on OS X and I constantly had problems with npm. I think I first had to install it with `sudo` and then constantly had to call npm with `sudo` when updating or installing a package. I struggled a while with this until I jettison all security and upgraded my user account to admin. I think I then still had to completely delete npm and re-install to get everything working. Might be there are better options: http://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo

**Comment by timbrandin** [comment]
So it's an npm issue, thx. Looking into it.
@tmeasday, thx for your quick response! Will I see you at the next Devshop SFBay maybe? I'm coming over from Sweden.

**Comment by tmeasday** [comment]
@timbrandin / @udondan -- I think the better solution is to change permissions of various files and directories so you never need to run `npm` as sudo. I'm not sure exactly what those directories are but it works on my machine (OSX). Not sure if that helps too much :)

P.S. @timbrandin - I won't be there but enjoy it and say hi to @dominicnguyen and @zol for me :)

**Comment by timbrandin** [comment]
Thx will try that! Will do!
BR // T
