### ISSUE TITLE
Atmosphere down / Websocket problems?

### ISSUE THREAD

**Issue by DanielDornhardt** [percolatestudio/atmosphere#170]
Hello,

I don't get any results on atmosphere anymore. Nothing at all. I see the app, but it's "empty", eg. no data is loaded. Searches never return results.

In the console I get this message, repeated ad inifinitum:

WebSocket connection to 'ws://atmospherejs.com/sockjs/732/7iyvwnig/websocket' failed: One or more reserved bits are on: reserved1 = 1, reserved2 = 0, reserved3 = 0 

---

The same happens in an app I try to upload on my own server using meteor-up by the way. It's possible that it's my connection, but it could also be a problem with an incompatibility between meteor (in a specific version), node.js (in specific / newer versions) and possibly the websocket implementation used.

Is it available for everybody else? Is it just my machine? (Chrome 35.0.1916.153, Safari 7.0.3 (9537.75.14)), both latest, on Mac OSX 10.9.3 (all latest / current versions).

**Comment by udondan** [comment]
I have no problem accessing atmospherejs.com, content is loaded and there are no messages in the console. Looks like a problem on your end.

**Comment by tmeasday** [comment]
Sounds like a problem with your machine, I'd be interested to know what it is if you figure it out...

**Comment by yauh** [comment]
I am also seeing lots of 503s mixed with occasional 504s here as of late. Perhaps some kind of proxy/server issue for european users?

**Comment by udondan** [comment]
I had that too in the recent days, as well many timeouts. But that had not been Websocket problems as described here.

**Comment by DanielDornhardt** [comment]
Hey... I think it might have something to do with a tool I am using, K9 web protection: http://www1.k9webprotection.com/

which, if it is implemented as some kind of proxy, could break the websocket connection. At least that's my theory.

I contacted them and I'll see what they'll tell me about this.

For my own project, it seemed that it would still work, I guess meteor might fall back to an alternative to websockets in my case. That doesn't seem to happen on atmosphere.

But I didn't investigate further yet.

Maybe I'll uninstall K9 at some point if that's really the source of the problem.

What's kind of strange is that I _once_ hat atmosphere loaded again a day or two ago... but I don't know how that happened.

**Comment by tmeasday** [comment]
I think was just a performance issue. We've had some trouble. More info to come :)
