### ISSUE TITLE
codemirror package is missing

### ISSUE THREAD

**Issue by jbl2024** [percolatestudio/atmosphere#171]
Hi,
the codemirror package is missing (http://atmospherejs.com/package/codemirror) : the github repo has disappeared.

I have created another repo from a fork and updated package to latest codemirror stuff (because the fork was broken) : 

https://github.com/jbl2024/meteor-codemirror

is it possible to update atmosphere index to use this new repo ?

**Comment by tmeasday** [comment]
Hi @jbl2024 - perhaps try to get in touch with @digioak ?

**Comment by jbl2024** [comment]
You're right, this should have been the first step :)

**Comment by digioak-zz** [comment]
atmosphere.meteor.com now atmospherejs.com has changed quite a bit... how
do I unregister the package?​

**Comment by udondan** [comment]
It's the same process on the old page. There is no option to do the same at the new page yet. The accounts page of the old site does not redirect to the new site, you can unregister it there via console: https://atmosphere.meteor.com/accounts

```
Meteor.call('deletePackage', 'codemirror');
```

**Comment by digioak-zz** [comment]
I tried executing that command after logging, returned 'undefined'... not
sure if it takes a while?

http://screencast.com/t/vohzyoBulHu
