### ISSUE TITLE
Share button or favorite button

### ISSUE THREAD

**Issue by timbrandin** [percolatestudio/atmosphere#172]
Hi, once again I find something I would like to favorite, share or store for future reference once I have the opportunity to test it out. It would be a simple thing to implement! A sharebutton for Twitter or HackerNews. Once again - Good work with Atmosphere!

**Comment by tmeasday** [comment]
Good idea Tim.

**Comment by timbrandin** [comment]
@tmeasday thx

**Comment by domyen** [comment]
Going to push this back to the next next release. Twitter will likely be the first button. We're considering a 'watch' button that surfaces in a personal user feed.

**Comment by timbrandin** [comment]
Oh both sounds amazing. :+1:

**Comment by domyen** [comment]
Added to the product roadmap and closing
