### ISSUE TITLE
404: Search trigger does not open search overlay

### ISSUE THREAD

**Issue by domyen** [percolatestudio/atmosphere#174]
Reproduce: 
1. Navigate to the 404 page
2. Click on the search button in the center of the page or the search input in the menu
3. Search is supposed to appear but does not

**Comment by tmeasday** [comment]
Not seeing this on production or devel. Can you remember where you saw it @dominicnguyen ?

**Comment by domyen** [comment]
Still see it. 
1. Go to this page http://atmospherejs.com/kaflkejakfj
2. Click on the search button

**Comment by tmeasday** [comment]
Gotcha. Note that it didn't happen at e.g. /packages/asdfasdf
