### ISSUE TITLE
Testing your package link broken

### ISSUE THREAD

**Issue by alanning** [percolatestudio/atmosphere#177]
Page: https://atmospherejs.com/docs/publishing

Section: Testing your package

Where: Second sentence, "It helps if your package includes unit tests. See for example crypto-base64 and for more on the topic, Testing Packages with Tinytest."   <= the "Testing Packages with Tinytest" part.

Current link is broken, eventedmind changed its url structure.

Correct Link:
https://www.eventedmind.com/feed/meteor-testing-packages-with-tinytest

**Comment by tmeasday** [comment]
@cmather - FYI perhaps your old link should have redirected? Changing here anyway.

**Comment by tmeasday** [comment]
Thanks @alanning :)

**Comment by cmather** [comment]
Thanks Tom. Sorry! I need to get religion on redirects.

**Comment by domyen** [comment]
lgtm
