### ISSUE TITLE
Clickable authors?

### ISSUE THREAD

**Issue by vsivsi** [percolatestudio/atmosphere#178]
It would be great if you could click on the author(s) of a package and be taken to a list of other packages they've written. 

I understand that the "related" panel often shows other packages by the same authors, but it isn't comprehensive and "related" could mean many things (now or in the future).

**Comment by tmeasday** [comment]
@vsivsi yes it would! An authors page is a planned feature that's coming relatively soon :)

**Comment by timbrandin** [comment]
@tmeasday do you have a public roadmap or something? Would be great to vote on features like this.

**Comment by domyen** [comment]
@timbrandin We don't have a page where folks can vote on features but our public roadmap was referenced [here](http://us3.campaign-archive1.com/?u=4eaab348037bea8afae9acd5f&id=7077e6c631&e).

**Comment by timbrandin** [comment]
Perfect, I wish it was a Trello-board though. :)

2014-07-15 18:49 GMT+02:00 Dominic Nguyen notifications@github.com:

> @timbrandin https://github.com/timbrandin We don't have a page where
> folks can vote on features but our public roadmap was referenced here
> http://us3.campaign-archive1.com/?u=4eaab348037bea8afae9acd5f&id=7077e6c631&e:
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/percolatestudio/atmosphere-beta/issues/178#issuecomment-49060395
> .

## 

Cheers,
// Tim Brandin @timbrandin https://twitter.com/#!/timbrandin
http://timbrandin.com

**Comment by domyen** [comment]
This feature is 100% going to happen. Roadmap: https://trello.com/b/RDZR8YGF/atmosphere-product-roadmap

**Comment by timbrandin** [comment]
Yay! A produkt roadmap! ;)

Skickat från min iPhone
