### ISSUE TITLE
Doc is broken

### ISSUE THREAD

**Issue by Vadorequest** [percolatestudio/atmosphere#183]
This link is broken:
https://atmospherejs.com/package/DOCS.md

> 404
>  The content you were looking for has vanished

**Comment by tmeasday** [comment]
Hey. Where does that link come from? Is it internal to the IR readme?

If so, we are tracking this problem here: https://github.com/percolatestudio/atmosphere-beta/issues/116

**Comment by Vadorequest** [comment]
Yes it it!
