### ISSUE TITLE
Insecure content, https warning

### ISSUE THREAD

**Issue by albinekb** [percolatestudio/atmosphere#187]
The page at 'https://atmospherejs.com/' was loaded over HTTPS, but is submitting data to an insecure location at 'http://percolatestudio.us3.list-manage.com/subscribe/post': this content should also be submitted over HTTPS.

**This makes chrome show a warning triangle rather than the "green lock", simple fix.**

**Comment by domyen** [comment]
Thank you. We are looking into it!

**Comment by domyen** [comment]
Fixed and should be deployed by EOW.

**Comment by zol** [comment]
Looks good, leaving unconfirmed to test in production.

**Comment by tmeasday** [comment]
LGTM
