### ISSUE TITLE
Favicon is a smudge on my non-retinal display

### ISSUE THREAD

**Issue by zol** [percolatestudio/atmosphere#19]
![Uploading Screen Shot 2014-02-18 at 10.44.43 AM.png . . .]()

**Comment by zol** [comment]
![screen shot 2014-02-18 at 10 44 43 am](https://f.cloud.github.com/assets/81672/2198767/df9d64d8-98cc-11e3-9686-6631239489f3.png)

**Comment by domyen** [comment]
Updated to a slightly clearer version.  bef057d4dd81bc8c1e234346c9c26310c2886e40.

**Comment by zol** [comment]
Looks good, thanks.
