### ISSUE TITLE
Iron Router package missing docs information

### ISSUE THREAD

**Issue by frieds** [percolatestudio/atmosphere#192]
I try to click on More Info at the bottom to learn more about route controllers, but that leads to a 404 page. Can I find the documentation elsewhere?

**Comment by domyen** [comment]
Docs are here: https://github.com/EventedMind/iron-router/blob/devel/DOCS.md#route-controllers. We don't process relative URL's from the github readme's at this time.

**Comment by tmeasday** [comment]
See https://github.com/percolatestudio/atmosphere-beta/issues/116
