### ISSUE TITLE
README did not update upon `mrt publish .`

### ISSUE THREAD

**Issue by reywood** [percolatestudio/atmosphere#194]
Just published a new version of the publish-composite package, but the README displayed on atmospherejs.com did not update to the new version.

**Comment by tmeasday** [comment]
Hey @reywood - we just grab the readme from GitHub. Has it changed there?

**Comment by reywood** [comment]
Yup. Notice that on [GitHub](https://github.com/englue/meteor-publish-composite) there are two opening paragraphs, and on [Atmosphere](http://atmospherejs.com/package/publish-composite) there's only one.

**Comment by tmeasday** [comment]
Ahh, right. I think the problem is with the redirect (reywood -> englue) for the git URL. For some reason github does something weird when we try to fetch such a readme. 

I think the easiest fix is to change the readme in the package's metadata.

**Comment by reywood** [comment]
Ah, right. I forgot to update smart.json when I moved the repo. Thanks.
