### ISSUE TITLE
Zombie packages

### ISSUE THREAD

**Issue by udondan** [percolatestudio/atmosphere#195]
In #158 some old packages of mine have been removed. They can't be found by searching but I just noticed they are still accessible through the old URL and they are indexed in Google:
- http://atmospherejs.com/package/node-zip
- http://atmospherejs.com/package/meteor-zipzap

The packages had been re-submitted with new names, simply _zip_ and _zipzap_. Please don't delete those. ;)

**Comment by tmeasday** [comment]
Hey @udondan,

Yes, packages are never actually deleted, they just stop showing up in search :)

**Comment by udondan** [comment]
Oh, good to know! I guess then we can close this. Not worth looking into it before the big change.
