### ISSUE TITLE
rm package `robots.txt` (superseded by robots-txt)

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#196]
http://atmospherejs.com/package/robots.txt

CC @gadicc

**Comment by gadicc** [comment]
Hey, thanks @dandv!

Yeah, this was indeed superseded way way back... the name `robots.txt` was allowed but the dot caused problems in a few weird cases... not sure about package name rules for the new Meteor.  ANYWAYS!  Yeah, rm it :)   Thanks, guys.

**Comment by tmeasday** [comment]
Yeah it won't have made it into the new server I don't think.
