### ISSUE TITLE
mrt add not working

### ISSUE THREAD

**Issue by isAlmogK** [percolatestudio/atmosphere#197]
I'm trying to add new packages and I'm getting the following error 

mrt add jquery-validation   

smart.json changed.. installing from smart.json

/usr/local/lib/node_modules/meteorite/lib/dependencies/package.js:63
      throw('No version ' + version + ' of package ' + self.name + ' was found
                                                                 ^
No version 0.9.1 of package iron-router was found in the atmosphere database

and at the end it's not installing

**Comment by tmeasday** [comment]
Ahh, yes, @cmather accidentally published that incorrect version of IR and we broke the usual rule and deleted it. Try `mrt update`.

**Comment by isAlmogK** [comment]
Yea I just hardcode the correct iron-router version in my smart.json file I prefer not to do this way when I deploy I get the correct builds no matter what.
