### ISSUE TITLE
Mark Non-Vanilla JS/HTML Packages

### ISSUE THREAD

**Issue by sclausen** [percolatestudio/atmosphere#198]
Its a bit frustrating searching for cool stuff only to find out, its a package written in coffescript and/or with jade templates or whatever.
I don't want a discussion coffe/jade etc. vs vanilla js/html. Its just, when you're developing, you either stick to one of this methods and the other one is  out of the question.

**Comment by tmeasday** [comment]
I guess a more general concept would be tagging of packages -- tags like `coffeescript` / `jade` could potentially help you out here.

**Comment by domyen** [comment]
Tracking this as a feature on the [roadmap](https://trello.com/c/dKAFvLAk/14-tagging-packages-by-users)
