### ISSUE TITLE
Returns to percolatestudio.com after adding your email to the mailing list

### ISSUE THREAD

**Issue by zol** [percolatestudio/atmosphere#20]
When you add your email via the footer, the return link is to percolatestudio.com rather than atmosphere.

**Comment by zol** [comment]
Also, clicking the right arrow in the field does nothing.

**Comment by domyen** [comment]
Updated URL on Mailchimp. Fixed the right arrow doing nothing. 0a5715ebbd80702dc116c4bf1aa2d672700ae810
