### ISSUE TITLE
I owned a package that now does not exist by my ownage

### ISSUE THREAD

**Issue by cristiandley** [percolatestudio/atmosphere#200]
Hi i owned "Alertfy" package... 'https://github.com/cristiandley/Alertfy' now another user owns it

**Comment by tmeasday** [comment]
Hi @cristiandley - are you referring to http://atmospherejs.com/ovcharik/alertify ?

Perhaps @ovcharik just got impatient and released his own version on 0.9.0? I'm not sure, but in the new package system you can release your own version if you'd like.

**Comment by cristiandley** [comment]
Yeah, he released that like in less than 8 hours after 0.9.0 release.... well... is not a problem. I will use that package now. Thanks Tom!

**Comment by tmeasday** [comment]
I guess he was **really** impatient.
