### ISSUE TITLE
History Data lost or just bug?

### ISSUE THREAD

**Issue by nooitaf** [percolatestudio/atmosphere#201]
![screen shot 2014-08-27 at 4 17 05](https://cloud.githubusercontent.com/assets/1898194/4054488/74308884-2d90-11e4-9ee8-c499daebeec8.jpg)

**Comment by mizzao** [comment]
This was probably a migration issue. On my package it is all out of order too.

**Comment by tmeasday** [comment]
Yeah, we can't control the date that the package was created at MDG's end. It was the date of the migration.

**Comment by aldeed** [comment]
Maybe you could sort the list by version number instead?

**Comment by nooitaf** [comment]
This is very confusing, especially for newcomers. Besides sorting, even very old packages look like they are new. Sorting by version is a good quick fix, but perfect would be to recover those dates. Would it be possible to give the MDG a backup of the correct dates of publishing so they could fix it?

**Comment by tmeasday** [comment]
Should be better now (perhaps not perfect). Let me know.

**Comment by aldeed** [comment]
The packages I checked still look about the same, pretty much random.

**Comment by tmeasday** [comment]
Hmm, yeah fair call. I guess that makes sense, the dates are slightly
different even if they look the same.

**Comment by zol** [comment]
@tmeasday - Do you know if this is still an issue on the latest release?

**Comment by mizzao** [comment]
Are you guys supporting the `x.y.z_v` wrapper version syntax yet? Seems like that might be something that MDG supports but wouldn't work with vanilla semver.

**Comment by tmeasday** [comment]
@zol yes it's still an issue in the sense that the pre-0.9 versions have the wrong release date. Was hoping it would be fixed upstream but perhaps not. The longer we wait the less it matters of course :)

**Comment by tmeasday** [comment]
I'm guessing the root cause here isn't ever going to be fixed.
