### ISSUE TITLE
Why is tmeasday co-author on most of my packages?

### ISSUE THREAD

**Issue by timbrandin** [percolatestudio/atmosphere#202]
Tom Coleman is not a co-author on Github what I can see, I would love him to be, but it's strange he's there everywhere.

**Comment by mizzao** [comment]
See https://hackpad.com/Migrating-Packages-zN0we9sIjkH.

**Comment by tmeasday** [comment]
Haha. Get rid of me! I can't handle the responsibility.

**Comment by timbrandin** [comment]
I'll try to remove you @tmeasday ;), and yeah I should probably migrate my packages first @mizzao. Thx!

**Comment by dandv** [comment]
I still see all packages having @tmeasday as contributor, e.g. http://atmospherejs.com/dburles/factory

**Comment by tmeasday** [comment]
Well I am actually a contributor on that package :)

A lot of packages are still being claimed by people. One of the things I
ask them to do is remove me as a contributor as part of the process.

**Comment by mizzao** [comment]
Any word on fixing atmosphere to not show random download numbers and download graphs for each package?

Literally, if you refresh the page, the trending and most used packages are different.

**Comment by zol** [comment]
We're looking into it. We've prioritized next week's sprint for atmosphere.​

**Comment by tmeasday** [comment]
@mizzao -- is it better now? We confirmed that we weren't getting the proper download counts and fixed the problem.

**Comment by mizzao** [comment]
Yes, appears to be much more reasonable. Although I wouldn't be able to tell if the numbers are completely correct :)

I'm happy to see that the data was actually stored during the period it wasn't displayed properly.

I don't think the recent packages is working properly, though. I released a new version of `mizzao:autocomplete` 10 hours ago, and this is what shows up in recent packages:

![image](https://cloud.githubusercontent.com/assets/2080084/4189636/115d23f0-377e-11e4-9a6c-83eccf338a2e.png)

I don't know why the incompatible packages are even showing up in recent packages at all.

**Comment by tmeasday** [comment]
Heh, neither would I necessarily :)

**Comment by mizzao** [comment]
As you answered this via e-mail, I don't think you saw the edits to my post. Do you think recent packages is working as intended?

**Comment by tmeasday** [comment]
I'm not sure what you were seeing but I do see your package alongside some "0h" packages in Recent. So it seems to be working right at the moment anyway. Let me know if you catch this situation again.

**Comment by mizzao** [comment]
That's funny, I don't see it at all when I open Recent, even going back several days. Beats me why it would look different on your machine versus mine.
