### ISSUE TITLE
Cannot search again

### ISSUE THREAD

**Issue by timbrandin** [percolatestudio/atmosphere#203]
If you do a search, and then go in to a result from that search.

Then when later trying to search again from that page, one can't reset or submit the search field or result. Nothing hapens.

**Comment by tmeasday** [comment]
Works for me @timbrandin.

Which browser are you seeing the problem in?

**Comment by prasadKodeInCloud** [comment]
Cannot search my package 'client-debugger' published last week.

**Comment by timbrandin** [comment]
Seems like the problem is resolved now, was using Chrome.

**Comment by timbrandin** [comment]
@prasadKodeInCloud you should create a new issue for that.

**Comment by tmeasday** [comment]
@Prasad19sara -- I think maybe you published that to the old server (
old-atmosphere.meteor.com) ?

You'll need to publish the package in the new 0.9.0 style.

**Comment by prasadKodeInCloud** [comment]
Yea I did so. Thanks . Its not auto migrated I guess. still can download anyway
