### ISSUE TITLE
Download count reset?

### ISSUE THREAD

**Issue by timbrandin** [percolatestudio/atmosphere#204]
Why did we reset the count of the downloads?

**Comment by tmeasday** [comment]
Good question! 

I'll probably write something more definitive somewhere but this will do for now:

The download count on the old atmosphere count was a pretty wonky number -- a "download" was triggered by Meteorite fetching a package from Atmosphere, which sounds good on the surface, but actually for a variety of reasons could happen a bunch of times when you wouldn't expect it.

For instance, most deployment scripts would re-fetch the package and increase the count.

So the number was fairly meaningless quantitively (a package with a higher "download" count was still probably better though).

In the new system, the package server tracks package "usage" -- it writes a record each time a user starts up their app. This metric is interesting for scoring but isn't super meaningful to be displayed to a user.

However, it also adds a second element -- the Meteor app identifier (you'll have see `.meteor/.id`). So now we can say "how many unique apps have used this package?". This is a much better and clearer metric than anything that's come before.

But it's a totally different scale from the old count, so there's really no way to reconcile them. So we are going to start fresh.

**Comment by timbrandin** [comment]
Thx, @tmeasday, great explanation. This I can understand!

**Comment by dburles** [comment]
Reopening so others with the same question can find it

**Comment by serkandurusoy** [comment]
This is great news!

I'd also like to make a note of #62 which is pretty related.

**Comment by dandv** [comment]
Aha... that's why [my package with a download count of 3 (three)](http://atmospherejs.com/dandv/caret-position) is trending :)

![image](https://cloud.githubusercontent.com/assets/33569/4146323/b42e356a-3409-11e4-9b2c-3afa6817d4df.png)

**Comment by tmeasday** [comment]
@serkandurusoy - we are definitely thinking hard about the dependency issue now that all the core packages (which are in every project via dependencies) are in there.

@dandv - heh our download counts were wrong for a bit there. I think we fixed it.

**Comment by serkandurusoy** [comment]
@tmeasday I hope this http://crater.io/posts/CL2QWTTv4B7GjKf66/ has caught your attention.

**Comment by domyen** [comment]
Closing. The migration from mrt to meteor is a distant memory :)

**Comment by dandv** [comment]
A distant memory brought back often by `mrt` packages :)

https://atmospherejs.com/?q=editable
