### ISSUE TITLE
Meteor is winning!

### ISSUE THREAD

**Issue by mizzao** [percolatestudio/atmosphere#205]
On the 0.9 atmosphere, all of the most downloaded, top packages etc. are under Meteor.

This isn't super useful as it doesn't help people find good non-core packages.

**Comment by tmeasday** [comment]
Yes, very true. We need to workshop the best way to deal with this.

**Comment by tmeasday** [comment]
As a temporary work around for  deeper problem I've just filtered meteor owned packages from the trending and top lists.

**Comment by tmeasday** [comment]
Now we ignore "depedent installs", which should help for ever package apart from `standard-app-packages` I think.

**Comment by tmeasday** [comment]
We should include a blacklist of "standard packages" (insecure / autopublish / meteor-platform / standard-app-packages for now). 

Still trying to work out if they should penalized score wise, or just not show up in the "Most Used" list. I don't expect them to be "published" much (at all?) so it shouldn't be a problem for trending.

**Comment by Dsyko** [comment]
I'm still seeing a lot of Meteor core packages in the 'Most Used' section. Is the change mentioned above already on production? I'd also vote for the ability to see more than just the top 8 most used packages. I think this would be a great way to discover packages if we could see a longer list of them. Maybe add a 'see more' link that takes us to a page that lists a lot more (20 - 50+) packages ranked by how many projects use those packages?

**Comment by tmeasday** [comment]
Like I said, I think the four packages I mentioned should be hidden. I'm not sure about `accounts-ui` and `accounts-password` though --- they seem legitimate.

A Most Used page seems like a no brainer though. @dburles I thought you were going to do this? :)

**Comment by dburles** [comment]
@tmeasday  Will do :)

**Comment by domyen** [comment]
@tmeasday @dburles is this issue OK to close?

**Comment by tmeasday** [comment]
I think we should do something about the 4 packages that installed into each new project by default. 

Either penalise them or hide them simply from the most used list.

**Comment by domyen** [comment]
Hiding them makes sense to me. Automatically installed packages have an unfair advantage against community packages.

**Comment by tmeasday** [comment]
Well my question is whether they should be penalized or just hidden from certain lists.

I.e. if you search for "insec" -- should "insecure" come up first? (or some other package that has those characters in the name). If we penalized the package it would come up last.

OTOH if we just hide it from lists (probably just most used), it might be better. Whatcha think @dominicnguyen ?

**Comment by domyen** [comment]
Hiding from most used sgtm.
