### ISSUE TITLE
Allow right click to open packages in new tabs ;)

### ISSUE THREAD

**Issue by asaphk** [percolatestudio/atmosphere#206]
Right click > Open in new tab > Awesomeness.

**Comment by isAlmogK** [comment]
Yes this is a must

**Comment by dburles** [comment]
In the interim you can hold command and left click to open in a new tab, possibly ctrl on windows

**Comment by tmeasday** [comment]
Oh does this not work?

**Comment by domyen** [comment]
@tmeasday @dburles 
Let's revisit this week. This bug has to do with using javascript to route the package lockups. IIRC It was an early decision based on routing constraints that are no longer there.

Moving this to p1 because it's not good for indexing if we don't provide real URL's.

**Comment by domyen** [comment]
Fixed. Should be deployed next release.
