### ISSUE TITLE
Deleting packages, duplicates and deprecatations

### ISSUE THREAD

**Issue by ghost** [percolatestudio/atmosphere#207]
Sending another notice about the need to provide package maintainers the ability to delete packages. The migration to the new package system is creating tons of duplicates as package maintainers try to control the namespace of their packages, and make publishing mistakes.

**Comment by wedow** [comment]
Just want to +1 this.  Running into it as well.

**Comment by dburles** [comment]
Hey guys we're aware of this, perhaps in the future meteor may allow you to remove packages that have not yet had any installs. Also package renaming is coming. On top of this we're considering ways to hide or minimise the visibility of stale packages on atmosphere itself.

**Comment by wedow** [comment]
Hey David, that's great to hear. Thanks for the update!

**Comment by ghost** [comment]
Good to hear - thanks for the update.

**Comment by domyen** [comment]
Agree with the sentiments expressed here. 

Since Meteor 0.9.0 now manages the package index, folks can request the ability to delete packages to the Meteor [roadmap](https://trello.com/b/hjBDflxp/meteor-roadmap) or [meteor-talk group](https://groups.google.com/forum/#!forum/meteor-talk).

**Comment by tmeasday** [comment]
This has been addressed in Meteor 0.9.3 (soon to be released by the looks of it).

We're adding a flagging feature which should help in the case of the maintainer disappearing.

Leaving this unfixed for now until 0.9.3 and us supporting it.

**Comment by domyen** [comment]
As of 0.9.3 you can prevent packages from showing up in meteor search with meteor admin set-unmigrated. Checkout their blogpost [here](https://www.meteor.com/blog/2014/09/25/meteor-093-packaging-system-updates).

Closing.

**Comment by dandv** [comment]
Unfortunately flagging doesn't work that well. https://atmospherejs.com/urigo/ngmeteor has 3 stars already before I flagged it, and it's a package that [the author would like to delete](https://github.com/Urigo/angular-meteor/issues/32#issuecomment-60177305).

**Comment by dandv** [comment]
@dominicnguyen: how does one [request features on the roadmap](https://github.com/percolatestudio/atmosphere-beta/issues/207#issuecomment-55972370)?

**Comment by domyen** [comment]
If it's an Atmosphere feature checkout [Flight Path](https://trello.com/b/RDZR8YGF/atmosphere-flight-path). If it's a Meteor package backend or an oauth feature checkout [Meteor Roadmap](https://trello.com/b/hjBDflxp/meteor-roadmap).

**Comment by dandv** [comment]
I'm aware of the roadmaps, but all I can do is comment on existing cards. Can't add new ones.

**Comment by domyen** [comment]
Made a new triage card for feature requests [here](https://trello.com/c/ZUvr6ShR/15-feature-requests).
