### ISSUE TITLE
Missing readme files 

### ISSUE THREAD

**Issue by isAlmogK** [percolatestudio/atmosphere#209]
I'm seeing a number of packages that on atmosphere are missing the readme files but on github they have it here is an example - https://github.com/percolatestudio/meteor-mixpanel/

**Comment by tmeasday** [comment]
Some packages that were automigrated never got the `git` URL that was specified on Atmopshere. You can tell because there's no Git link on the RHS.

We'll need to republish this one I guess.

**Comment by domyen** [comment]
Closing this as the fix seems to be the author republishing. Please reopen if that's not the case.

**Comment by dandv** [comment]
No README for https://atmospherejs.com/copleykj/livestamp
