### ISSUE TITLE
lesshat.less - where is it?

### ISSUE THREAD

**Issue by matfin** [percolatestudio/atmosphere#213]
When installing the meteorite package, I always imported lesshat from @import "/packages/lesshat/lesshat.less";

I updated to Meteor 0.9.0 and ran mrt:install lesshat. There appears to be no documentation as to where the new lesshat.less file is. Any ideas?

**Comment by dburles** [comment]
I think that package  `mrt:lesshat` might be broken.

**Comment by tmeasday** [comment]
Hey @matfin - I guess the new package system doesn't make the files from packages easily available any more. I'm not sure what the solution to these kind of problems is. Perhaps you should ask about this on the meteor-talk mailing list?

**Comment by matfin** [comment]
Yep thats that I guessed. I ended up downloading the lesshat less file and adding it to my css/thirdparty directory, referencing it from main.less and that worked.

**Comment by tmeasday** [comment]
Yeah. It's not ideal though is it :/
