### ISSUE TITLE
Not working currently

### ISSUE THREAD

**Issue by udiedrichsen** [percolatestudio/atmosphere#214]
It seems that atmosphere today not working.

The search runs forever and the title page with trending etc. shows nothing.

**Comment by sclausen** [comment]
experienced this since around 24 hours ago

[Edit]: Sorry beeing impatient and pointing out the obvious. I did heavy coding that time and didn't knew I'm such dependent on atmosphere providing search and clear overview for packages ;)

**Comment by tmeasday** [comment]
Thanks guys. We were having some issues with our Mongo server being overloaded. Fixed now.
