### ISSUE TITLE
rm meteor-crypto-base from search result

### ISSUE THREAD

**Issue by p-j** [percolatestudio/atmosphere#215]
Made a mistake when releasing this one : [meteor-crypto-base](https://atmospherejs.com/jparker/meteor-crypto-base)

The working version is [crypto-core](https://atmospherejs.com/jparker/crypto-core)

Thanks

**Comment by domyen** [comment]
Closing package index issues because Meteor 0.9.0 now manages the package index. 
Folks can request the ability to remove packages to the Meteor [roadmap](https://trello.com/b/hjBDflxp/meteor-roadmap) or [meteor-talk group](https://groups.google.com/forum/#!forum/meteor-talk).
