### ISSUE TITLE
Do not know how how to 'require' or use mrt:natural 

### ISSUE THREAD

**Issue by typeofgraphic** [percolatestudio/atmosphere#216]
I have tried (from within the server folder and at the terminal) to call, find, use 'Natural', Meteor.require("Natural"), npm.require, NPM.require, require...

**Comment by zol** [comment]
In Meteor 0.9+ you add packages by typing `meteor add package`, in your case it would be `meteor add mrt:natural` from within your meteor project. If that's not working, please raise an issue on https://github.com/meteor/meteor
