### ISSUE TITLE
ServiceConfiguration is not defined in accounts-github

### ISSUE THREAD

**Issue by piyushcoader** [percolatestudio/atmosphere#217]
it was working fine in the previous version of accounts-github..
after i update to 0.9.1 it gives the error as 
ServiceConfiguration is not defined

**Comment by domyen** [comment]
Thanks for submitting an issue. This doesn't seem to be related to the functionality of Atmosphere. 

To report or discuss issues about Meteor or core packages:
1. [Meteor Talk Google Group](https://groups.google.com/forum/#!forum/meteor-talk)
2. [Meteor on GH](https://github.com/meteor/meteor/issues)
