### ISSUE TITLE
Avoiding dependency packages from cluttering trending

### ISSUE THREAD

**Issue by dfischer** [percolatestudio/atmosphere#218]
I like browsing trending every so often, but it's usually cluttered with a parent package and it's dependencies so it becomes less valuable. Like iron-router and all the iron sub packages.

**Comment by domyen** [comment]
Good timing; we are addressing this with the current sprint and will release next deploy.

**Comment by zol** [comment]
@tmeasday - how should we test this either on staging or when the code goes live?

**Comment by tmeasday** [comment]
This is difficult for staging because we aren't able to import usage properly (will explain why).

Once deployed to production, the test is simply to see if internal packages like "livedata" appear in the most used lists etc.

**Comment by tmeasday** [comment]
Apart from notes in #205
