### ISSUE TITLE
Open sourcing atmosphere?

### ISSUE THREAD

**Issue by dfischer** [percolatestudio/atmosphere#219]
It would be a great community package and system for education...

Ability to iterate faster too. I'm sure a ton of people would love to contribute back. This would be great for the meteor community as a way to give back and learn.

**Comment by domyen** [comment]
We plan to release some packages at the core of Atmosphere, we just haven't had the time :( 
Will report back when we have more of a timeline for this type of thing.

**Comment by mquandalle** [comment]
:+1:

**Comment by IstoraMandiri** [comment]
:+1:
