### ISSUE TITLE
Package search results count text is grey

### ISSUE THREAD

**Issue by dburles** [percolatestudio/atmosphere#224]
Just a styling issue @dominicnguyen

**Comment by domyen** [comment]
Screenshot & location?

**Comment by dburles** [comment]
![screen shot 2014-09-25 at 8 02 18 am](https://cloud.githubusercontent.com/assets/319567/4396597/8394bc84-4436-11e4-8504-0c8aabad3354.png)

On the search results overlay. See the barely visible text '35 packages'

**Comment by dburles** [comment]
lgtm!
