### ISSUE TITLE
URL for profile pages results in what seems like a page

### ISSUE THREAD

**Issue by domyen** [percolatestudio/atmosphere#226]
Random user names typed into the url string result in what seems like a real profile page. We should be 404ing this. http://localhost:3000/lifeafaffeafeaf

**Comment by tmeasday** [comment]
@dburles do you think we should send down a "psuedo" user in a publication (after doing the package check that we talked about yesterday?).

Maybe rather than the `Collaborators` collection, we should have a `Usernames` collection or something?

**Comment by dburles** [comment]
I wonder would it simplify everything if we sent down the pseudo user on the users collection, and also flag it with something which we can use to check against within our collection helpers? (instead of _id)

**Comment by tmeasday** [comment]
@dburles yes, and make the `user` publication return something that looks like a user too (if the user exists--in the sense of being a maintainer--of course)

**Comment by tmeasday** [comment]
@dburles - looks great. Still awaiting confirmation on whether to hide Org pages. @dominicnguyen ?

**Comment by domyen** [comment]
We'll likely be tackling Organizations in a later release. For now, we have no way to access them or verify which users are connected so we're hamstrung in that we cannot create a 'claim' organization flow for org members.

I lean towards hiding them for now to sidestep an unideal experience. @tmeasday want to reach out to MDG to see what's required?

**Comment by tmeasday** [comment]
Agreed. Hiding them is easy. 

I already asked ekate about getting org details and she said we can't. Possibly you guys can chat to them about it?

**Comment by tmeasday** [comment]
@dburles - we should treat orgs as "non" users.

**Comment by tmeasday** [comment]
LGTM, although annoyingly "iron" is not an org.
