### ISSUE TITLE
Footer links need reset scroll

### ISSUE THREAD

**Issue by guilhermedecampo** [percolatestudio/atmosphere#24]
add this filter:

resetScroll: function () {
    var scrollTo = window.currentScroll || 0;
    $('body').scrollTop(scrollTo);
    $('body').css("min-height", 0);
  },

=)

**Comment by Slava** [comment]
+1 after scrolling to the end, clicking "publish packages", I get teleported to the middle of the page.

**Comment by zol** [comment]
Thanks @guilhermedecampo  and @Slava - this will be fixed asap.
