### ISSUE TITLE
Contenteditable field validation and error states

### ISSUE THREAD

**Issue by domyen** [percolatestudio/atmosphere#240]
1. Set an .error class
2. Populate and show a tooltip with error message

**Comment by dburles** [comment]
Added error classes and tooltips, however the tooltip positioning is a little funky

**Comment by domyen** [comment]
@dburles I adjusted the tooltip positioning and added a red error color.

Can we show more than one tooltip at a time? If multiple fields are incorrect we should be able to see em all.

**Comment by dburles** [comment]
Hmm yeah they should be showing, will check

**Comment by domyen** [comment]
@dburles Re: limiting characters bug
We need to ensure that pasting in a long string respects the character limit. 

Repro:
1. Get within a few characters of the character limit on the description field
2. Copy some text that is greater than the remaining character allowance
3. Paste
4. It pastes the string and exceeds the character count, which doesn't allow you to save.
- Can we count the total characters in the plain text string and paste only the _n_ characters that are allowed?
- We should also have a form error state (which I'm working on now)

**Comment by dburles** [comment]
Thanks @dominicnguyen yeah this is something I've yet to look into solving. On it today :)

**Comment by domyen** [comment]
lgtm
