### ISSUE TITLE
URL to Github not working

### ISSUE THREAD

**Issue by Urigo** [percolatestudio/atmosphere#242]
Is here: https://atmospherejs.com/urigo/ngmeteor
I've updated the Github URL as specified and still it doesn't show the connection to the Github repository.
Thanks!

**Comment by dburles** [comment]
Hey Urigo, looks like your url is incorrect? https://github.com/Urigo/ngmeteor/blob/master/package.js#L4

**Comment by Urigo** [comment]
Yes, sorry about that!
Thank you so much
