### ISSUE TITLE
Flagging throws error

### ISSUE THREAD

**Issue by dburles** [percolatestudio/atmosphere#245]
Hitting the flag button returns `Version already flagged [422]` on packages that the user has not yet flagged

**Comment by tmeasday** [comment]
Might need to clear indices again

**Comment by tmeasday** [comment]
`db.flags.dropIndexes()`, then restart meteor. Probably need to do the same for `db.stars`.

**Comment by dburles** [comment]
looks like the package `latestVersion` doesn't contain the `upstreamId`

**Comment by tmeasday** [comment]
Ahh, sorry, you'll need to resync your packages. Sorry.

**Comment by tmeasday** [comment]
Fixed now?

**Comment by dburles** [comment]
All good!
