### ISSUE TITLE
Notifications: Connection notification should get a timeout of 1s before becoming visible

### ISSUE THREAD

**Issue by domyen** [percolatestudio/atmosphere#248]
On the first load of the page, the system connection notification appears immediately atop the content that is also loading. This is redundant because the page is already loading so we end up flashing the UI in and out. The connection notification should only appear when it's unable to connect, _not_ when it's starting to connect.

**Idea:**
We can address this with a 1s delay on a page refresh/load where we suppress the connection notification. 

Any other ideas?

**Comment by dburles** [comment]
Yeah I've figured a way around this but @tmeasday might have ideas

**Comment by dburles** [comment]
This seems to work quite well, @tmeasday can you confirm?

**Comment by tmeasday** [comment]
Seems pretty reasonable to me in the absence of appcache or something like that.
