### ISSUE TITLE
UX wierd for profile page link

### ISSUE THREAD

**Issue by zol** [percolatestudio/atmosphere#251]
When I click on the name in the top right, if flashes instantly then a split second later the drop down fades into view. This feels unintentional/buggy. I would expect the click target to not flash and the drop down to fade in immediately.

@dominicnguyen feel free to re-assign this to the appropriate person.

**Comment by zol** [comment]
@dominicnguyen This is better but still not ideal. Now, when I click on an item in the dropdown, the page changes but the dropdown remains. The dropdown should disappear once you click an item.

**Comment by domyen** [comment]
This is a recent regression, @dburles is taking a look at tooltips for form validation. Dave can you ensure that tooltips are cleared when routes change?
