### ISSUE TITLE
Package: Timeline layout is broken

### ISSUE THREAD

**Issue by domyen** [percolatestudio/atmosphere#259]
![screenshot 2014-10-06 17 47 38](https://cloud.githubusercontent.com/assets/263385/4535845/ccf9e1a4-4dbb-11e4-87b0-44b9f50d5d83.png)

**Comment by tmeasday** [comment]
See also #290

**Comment by domyen** [comment]
I've fixed the z-index issue. The bug present in the screenshot above has to do with `noMilestonesClass`. 

`noMilestonesClass` adds class .no-milestones if a package has no milestones. We style against this class to tweak the layout to accomodate milestones. It doesnt work in some [cases](https://atmospherejs.com/natestrauser/font-awesome).

@tmeasday can you have a look?

**Comment by tmeasday** [comment]
@dominicnguyen - are you saying that package _shouldn't_ have `.no-milestones` set?

**Comment by domyen** [comment]
Correct. `.no-milestones` should only be set when there are no milestones. ;)
