### ISSUE TITLE
Package summary, version and readme is missing

### ISSUE THREAD

**Issue by rbabayoff** [percolatestudio/atmosphere#260]
Don't know if it's an atmosphere bug or a meteor package server bug, but you can see it here (master is the version published to meteor):

https://github.com/spacejamio/meteor-loglevel

https://atmospherejs.com/spacejamio/loglevel

**Comment by tmeasday** [comment]
Yeah the missing versions are leading to the other problems. I think this is an example of #257. Still trying to sort it out upstream.
