### ISSUE TITLE
Don't show default gravatar image

### ISSUE THREAD

**Issue by dburles** [percolatestudio/atmosphere#265]
For users that sign up who do not have a gravatar associated with their email address, the default gravatar icon is shown.

**Comment by tmeasday** [comment]
I think we have a default icon -- @dburles did we discuss what to do here at some point?

**Comment by dburles** [comment]
Gravatar can send back a transparent image. So I think it was on @dominicnguyen's todo list to add a default icon as a  background image behind the avatar

**Comment by tmeasday** [comment]
Cool. Do you want to take care of the first part (so it's just blank for now) on devel?

**Comment by dburles** [comment]
Ya no prob

**Comment by dburles** [comment]
Gravatar will now send us a transparent image instead of their logo. @dominicnguyen will just need get the default icon to always show.
