### ISSUE TITLE
Styling updates for view all option on most used

### ISSUE THREAD

**Issue by dburles** [percolatestudio/atmosphere#266]
I've added a 'view more' link on the homepage and also added the select menu to the view more list.
- The 'view more' link isn't correctly aligning under the select menu on the homepage
- Small visual issue with the select menu on the 'view all' page

Find this stuff in the `view-more` branch

**Comment by tmeasday** [comment]
I'm seeing occasional weird issues with pagination. I'd suggest adding a secondary sort parameter (`latestVersion.published` I guess) as a tie breaker (probably the issue is that most packages have 0 usage on my machine)

**Comment by dburles** [comment]
Ah yeah. Just pushed the fix, can you confirm?

**Comment by tmeasday** [comment]
GJ, problem appears fixed.
