### ISSUE TITLE
Delete/hide packages

### ISSUE THREAD

**Issue by udondan** [percolatestudio/atmosphere#267]
Sorry I have to bring this topic up again. :-)

So after the big change, all my packages which had been ~~deleted~~ hidden showed up again on Atmosphere. They show up in searches, they show up as related packages and they show up at the package listing on my account page.

They are marked as incompatible to 0.9 which makes them invisible when you `meteor search` w/o `--show-old`. But on Atmosphere they're visible.

What is the problem with actually deleting packages? Why can't they simply be removed? (Of course I know now it's too late to address this in Atmosphere that they have been shipped over to meteor) I can only think of that you wanted to keep them so apps don't break which already use them. But the result is, there are packages online, which
- do have no readme (because of the migration, where all my packages ended up with no readme)
- are marked as incompatible, therefore won't work with >0.9.0
- are replaced by newer packages with different names, (which I can not even describe in the readme because I would be required to create a separate github repo for each broken package, that I simply would want to disappear)

What's the overall plan with this topic? (maybe not a question for the Atmosphere team any longer now that the packages are registered with meteor itself, but you guys probably know more about it than anyone else)

And finally: How do I at least again hide those packages on Atmosphere. Forever. ;-)

**Comment by domyen** [comment]
**Deleting**
Hey @udondan, folks can prevent packages from showing up in `meteor search` with `meteor admin set-unmigrated`. Checkout their [blogpost](https://www.meteor.com/blog/2014/09/25/meteor-093-packaging-system-updates). 

This only hides it from the index on both Atmosphere –which uses MDG's packaging backend– and `meteor search`. App creators who've previously used your package can still install a hidden package if they know the author and package name.

In terms of _why_ they can't be deleted altogether, that's a question best answered by Meteor Development Group. ;) Your points are well-heard by us. For now, the best thing Atmosphere users can do is login and **flag packages**. Flagging are affects a package's score which in turn affects the ranking in search. It also indicates to others that a package is not-working or broken. 

e.g., [Flagged React package](https://atmospherejs.com/mrt/react)

**Comment by udondan** [comment]
Thanks Dominic,

> This only hides it from the index on both Atmosphere –which uses MDG's
> packaging backend– and meteor search

ah, ok, now I see it really works on Atmosphere for the actual search too. That's cool. But the packages are still listed on my [account page](https://atmospherejs.com/udondan) and the "related packages" section of my other packages.

![account](https://cloud.githubusercontent.com/assets/6443408/4604977/6d49ad3c-51c3-11e4-8346-0a1345eb6739.png)

![related](https://cloud.githubusercontent.com/assets/6443408/4604982/fb1370e4-51c3-11e4-917d-32898083d650.png)

While it still _might_ make sense to list them on the account page, they should probably not be advertised in the "related packages" section, right? Can we have a filter there as well?

Cheers,
Daniel

**Comment by domyen** [comment]
Makes sense. I'll open a new ticket for this and close this issue.

**Comment by udondan** [comment]
Awesome, thanks! I'll close this one then.

**Comment by dandv** [comment]
@dominicnguyen: Unfortunately flagging doesn't work that well. https://atmospherejs.com/urigo/ngmeteor has 3 stars already before I flagged it, and it's a package that [the author would like to delete](https://github.com/Urigo/angular-meteor/issues/32#issuecomment-60177305).
