### ISSUE TITLE
Atmosphere Public API?

### ISSUE THREAD

**Issue by scottmcpherson** [percolatestudio/atmosphere#269]
Back on the old atmosphere, you guys had a public subscription that allowed me to get package meta data for an Atom package called [orbit](https://github.com/scott-mcpherson/orbit) that I built. The subscription was called "packageMetadata" and it returned all of the packages on atmosphere and their associated meta data. 

Do you guys have any similar public subscriptions with the new Atmosphere so that I can get orbit working again?

**Comment by zol** [comment]
We no longer provide such a publication as it doesn't make sense given that MDG is now hosting the backend. You should look into connecting directly to their package database. (They may need to probide you with an API key).
