### ISSUE TITLE
Clicking the username for a package should take you to their Github/bitbucket page

### ISSUE THREAD

**Issue by brentjanderson** [percolatestudio/atmosphere#27]
For packages based out of Github or Bitbucket, clicking the author username should take you to their profile on their respective service. Perhaps even better would be having a user profile which, when you click a user's name, you can see their repositories, links to github/bitbucket/other social media, etc.

**Comment by queso** [comment]
Actually,

I would love to see the link stay on atmosphere and show a collection of packages that user/org has published to Atmosphere.

**Comment by brentjanderson** [comment]
+1 - that's a better implementation, especially since they will undoubtedly have non-atmosphere projects as well. 
1. 2. 2014 v 14:26, Josh Owens notifications@github.com:

**Comment by domyen** [comment]
@queso @brentjanderson  This is next on the roadmap. Specifically we'll be adding Atmosphere accounts via Meteor oauth. Closing issue for now.
