### ISSUE TITLE
Ensure `lastVersion` is not `unmigrated` (if possible).

### ISSUE THREAD

**Issue by tmeasday** [percolatestudio/atmosphere#270]
- [x] Migrate existing packages
- [x] Add `unmigrated` field to versions
- [x] Update `Versions.import` to grab `unmigrated`
- [x] Update `package.denormLatestVersion()` to de-prioritze `unmigrated` versions.

**Comment by tmeasday** [comment]
Ok there were like 300 packages that just reappeared. We should get this fix out :)

**Comment by dburles** [comment]
LGTM!
