### ISSUE TITLE
Pages for organizations

### ISSUE THREAD

**Issue by udondan** [percolatestudio/atmosphere#273]
On meteor.com you can create organizations. This enables you to publish packages with the organization prefix instead of your user name prefix, `orgname:packagename`. Those packages are listed fine on Atmosphere.

Unfortunately the organization can not be accessed the same way a user can. On the user page you can see all packages of the user. It would be great if there was an organization page listing all packages of it too.

**Comment by tmeasday** [comment]
Yeah, the problem is that because we don't know who is in the org, the page is really boring (ie. it's purely a package list, we don't know who's in it, we can't allow anyone to edit it -- because we don't know who's in it).

Maybe the package list alone is interesting enough? In which case I'd suggest we need a different design for this page..

**Comment by domyen** [comment]
To expand on @tmeasday's comment. We currently have no way of accessing organizations with the current oauth system. As soon as the app can get access to organizations & their members, we'll definitely move forward on org pages. 

re:making a barebones org page
Seems like throwaway work.

**Comment by tmeasday** [comment]
@dominicnguyen I guess it depends on when we imagine (if ever) we'll have access from upstream. I'm not holding my breath.

**Comment by udondan** [comment]
> Maybe the package list alone is interesting enough? In which case I'd suggest we need a different design for this page..

Yes, I think It's interesting and useful. Instead of a separate page there could alternatively be an "Other packages in this organization" section between the package readme and the "Top searches" section. Though a separate organization page (even only if it is a plain package list) would be more handy because you could link to it, therefore the organization name can be linked in package listings (like search results).

**Comment by domyen** [comment]
We're looking into getting access to org members now. @udondan's right about having a URL for the org page, this is what we're hoping to achieve for the reasons mentioned.

**Comment by udondan** [comment]
Great, thanks @dominicnguyen !

**Comment by splendido** [comment]
+1 for organization pages!

**Comment by dandv** [comment]
The package list is great to begin with, and feel free to close my dupe issue!

**Comment by tmeasday** [comment]
Maybe the placeholder should be slightly different for "name" when you are editing an org?

**Comment by tmeasday** [comment]
Apart from that looks good.

**Comment by dburles** [comment]
ok, done @tmeasday

**Comment by dburles** [comment]
@tmeasday can you please look into the contenteditable bug
