### ISSUE TITLE
Replace the select element UX with a toggle button on Most Used Packages & Author pages

### ISSUE THREAD

**Issue by domyen** [percolatestudio/atmosphere#274]
![screenshot 2014-10-16 18 22 24](https://cloud.githubusercontent.com/assets/263385/4673077/5c008d98-559c-11e4-95ca-d2e88371c81a.png)

**Comment by tmeasday** [comment]
Also for the starred packages on author page, right?

**Comment by domyen** [comment]
Yes, there too. Will update title.

**Comment by dburles** [comment]
@dominicnguyen Changes are on branch `274-toggle`. Just needs styling.

**Comment by dburles** [comment]
@dominicnguyen merged into devel

**Comment by domyen** [comment]
Styled. @dburles Can you confirm that the data is getting updated? I was shown the same package list no matter which option.

https://github.com/percolatestudio/atmosphere-dev/commit/b5949173c81f153cc1bf4303a9a8550b26d56e1b

**Comment by dburles** [comment]
@dominicnguyen yep it's all good
