### ISSUE TITLE
Rename the repo to 'atmosphere'?

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#275]
Not beta any more, and since nobody's cloned it, there should be no problem to rename it.

**Comment by tmeasday** [comment]
Good idea.

**Comment by dandv** [comment]
Bump

**Comment by tmeasday** [comment]
Done. Thanks for the dump @dandv

**Comment by dandv** [comment]
Thanks. The repo description should also be updated (it says "Beta").

GitHub doesn't display it to me (which is a bug, I guess), but it's picked up by Google and shown in the SERP.
