### ISSUE TITLE
No GithHub for joshowens:timeago

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#277]
https://atmospherejs.com/joshowens/timeago

CC @queso, @meteorclub

**Comment by udondan** [comment]
@dandv I believe you assume the username of the package is the same as the one on github. The name under which the package is published though is the name of the Meteor account. Might be the same, might not. :) 

Since all packages lost their github reference at migration, I'm sure there is a very high percentage of packages w/o github repo. It's too late now to fix this on atmosphere.

**Comment by dandv** [comment]
@udondan: I had edited my comment, see above :)

So what's the solution now for all these packages?

**Comment by udondan** [comment]
Ah, see now. :)

> So what's the solution now for all these packages?

Good question. Actually I thought the github info simply is lost and can not be restored. But then I did this:

```
$ mrt search timeago
✓ Found package timeago
{
  "author": {
    "name": "Josh Owens",
    "url": "http://differential.io"
  },
  "createdAt": 1379094356864,
  "description": "A Handlebars helper to easily do timeago from a date stamp",
  "git": "https://github.com/Differential/timeago.git",
  "homepage": "https://github.com/Differential/timeago",
  "installCount": 68,
  "latest": "0.0.4",
  "meteor": null,
  "name": "timeago",
  "packages": {},
  "updatedAt": 1399322718660,
  "userIds": [
    "iruW5MLWPs6ZmAyMK"
  ],
  "version": "0.0.4",
  "versions": [
    {
      "createdAt": 1379094356864,
      "git": "https://github.com/BeDifferential/timeago.git",
      "packages": {},
      "troposphereIdentifier": "joshowens:timeago@0.0.1",
      "updatedAt": 1379094356864,
      "version": "0.0.1"
    },
    {
      "git": "https://github.com/BeDifferential/timeago.git",
      "version": "0.0.1",
      "packages": {},
      "createdAt": 1379094362871,
      "updatedAt": 1379094362871
    },
    {
      "createdAt": 1379952104039,
      "git": "https://github.com/BeDifferential/timeago.git",
      "installCount": 23,
      "packages": {},
      "troposphereIdentifier": "joshowens:timeago@0.0.2",
      "updatedAt": 1379952104039,
      "version": "0.0.2"
    },
    {
      "git": "https://github.com/BeDifferential/timeago.git",
      "version": "0.0.2",
      "packages": {},
      "createdAt": 1379952111667,
      "updatedAt": 1379952111667
    },
    {
      "createdAt": 1390503011017,
      "git": "https://github.com/BeDifferential/timeago.git",
      "installCount": 45,
      "packages": {},
      "troposphereIdentifier": "joshowens:timeago@0.0.3",
      "updatedAt": 1390503011017,
      "version": "0.0.3"
    },
    {
      "createdAt": 1399322718660,
      "git": "https://github.com/Differential/timeago.git",
      "packages": {},
      "troposphereIdentifier": "joshowens:timeago@0.0.4",
      "updatedAt": 1399322718660,
      "version": "0.0.4"
    }
  ],
  "visible": true
}
```

So github/homepage should be known to Atmosphere, even if it is not in the package.js.

I checked some other packages which are disaplayed w/o github (and therefore readme) on Atmosphere and they all have a github parameter available with `mrt search`.
- mrt:flash-messages
- mrt:jquery-ui-sortable
- mrt:google-contacts
- ...

Can we have a fallback to this info when there is no github param in the `package.js`?

An interesting find was [dsyko:bootstrap-slider-touch](https://atmospherejs.com/dsyko/bootstrap-slider-touch) which has no github link on the website. But it has a readme. While I can somehow explain myself the other things, this one is a mystery to me. :)

**Comment by queso** [comment]
I can update the package, I guess. I should really switch it to use moment.

It really is too bad all this info just 'disappeared' with the migration when it was already there...

**Comment by tmeasday** [comment]
Hey guys,

> Since all packages lost their github reference at migration

This isn't true. We actually ported this information across when we had it. 

I'm not sure what's happening with this specific package -- I can see that `mrt search` is returning the imported readme, but our db doesn't have that info. It's odd.

> An interesting find was dsyko:bootstrap-slider-touch which has no github link on the website. But it has a readme. While I can somehow explain myself the other things, this one is a mystery to me. :)

You can set a `readme` directly on the version now. I'm not sure if it's documented anywhere (it's pretty brittle) but MDG are using it to set READMEs for core packages that don't have their own git URLs

**Comment by dandv** [comment]
@queso: there is already a package using Moment for live timestamps: https://atmospherejs.com/copleykj/livestamp. Maybe that makes things easier, i.e. rm the timeago package?

**Comment by udondan** [comment]
@tmeasday

> This isn't true. We actually ported this information across when we had it.

I do not understand this statement. With `mrt` you HAD to have a github param in your `smart.json`, so there should have been no way you did not have this info for any package. What am I missing? :)

Let me again point your attention to https://github.com/lezed1/meteor-bootstrap-errors/blob/master/smart.json#L7 which has the github reference in the smart.json, the github repo has a [Readme](https://github.com/lezed1/meteor-bootstrap-errors/blob/master/README.md) and the [Atmosphere page](https://atmospherejs.com/lezed1/bootstrap-errors) is empty. This is not the exception with one or two packages. It was true for every single package of mine (like 10 or so) and a billion others I have found.

The reason why I thought/think this info got generally lost during migration was/is that the `mrt migrate-package` command does not copy the git url from `smart.json` to `package.js`. And I assumed you were using somehow the same process when you migrated all packages.

**Comment by tmeasday** [comment]
Hey @udondan,

Your detective work is good but not quite perfect :)

> I do not understand this statement. With mrt you HAD to have a github param in your smart.json, so there should have been no way you did not have this info for any package. What am I missing? :)

Sorry I probably phrased that badly. I should have said "we tried" -- as you've noticed (for a while [1]) `mrt migrate-package` wasn't setting the `git` on the version. However, I only fixed that after the migration was done and we attempted to set the git URLs after the fact. I guess we did a worse job than I thought, but it definitely did work for a bunch of packages, for example:
- https://atmospherejs.com/tmeasday/router
- https://atmospherejs.com/tmeasday/deps-extensions

Two old packages that haven't had new versions released since the migration.

Anyway, it should clean itself up as people release new versions of packages. We're starting to get far enough in now that any package that hasn't been released since August is probably out of date anyway.

[1] Not any more, you should update mrt! https://github.com/oortcloud/meteorite/blob/master/lib/atmosphere.js#L62-L67

**Comment by tmeasday** [comment]
Re my above comment:

> I'm not sure what's happening with this specific package -- I can see that mrt search is returning the imported readme, but our db doesn't have that info. It's odd.

Ok, that was just dumb. Ignore that comment. The issue here is that we didn't pass across as many git URLs as I thought.

**Comment by udondan** [comment]
Thanks for clarification. :) There's one more thing I don't get though. Sorry for bothering! ;)

From my understanding `mrt` uses Atmosphere as the backend.

``` sh
$ mrt search whatever --verbose
Connecting to atmosphere.meteor.com:443...
...
```

So I don't understand why `mrt search` is returning the git url but you say you do not have it in the DB.

Maybe this info is stored in a different collection? Isn't there a way to port it to the correct collection then?

**Comment by tmeasday** [comment]
Meteorite talks to atmosphere.meteor.com (which is it's own server, even if the web front end redirects to atmospherejs.com). You can even see the old package list at old-atmosphere.meteor.com.

Atmosphere talks to packages.meteor.com. We don't have any control over that data.

**Comment by udondan** [comment]
I see, now it makes sense. Thanks again for clarification! :)
