### ISSUE TITLE
Deprecate/un-migrate/hide/remove bootstrap package

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#278]
https://atmospherejs.com/meteor/bootstrap - I've flagged it but has 3 stars. Per the [release notes](https://github.com/meteor/meteor/blob/devel/History.md#api-changes), it's deprecated in favor of community alternatives.

CC @ekatek

**Comment by domyen** [comment]
Would you mind requesting un-migration on meteor/meteor issues instead of Atmosphere issues? It's up to the author to be proactive about removing their packages from the index.
