### ISSUE TITLE
Hide/un-migrate accounts-entry clones

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#279]
Flagged:
https://atmospherejs.com/stevenhornung/accounts-entry
https://atmospherejs.com/rnosov/accounts-entry

Original:
https://atmospherejs.com/joshowens/accounts-entry

CC @queso

**Comment by domyen** [comment]
While it is strange to me to fork an open source package and republish it to the package index, it doesn't seem like we're the right people to make the judgement on whether folks can/can't republish nor do we have the ability to remove them from the Meteor's package index.

v1 of the flagging feature is intended to show that a developers mileage may vary with certain community-flagged packages however I'm wary of being a censor.

**Comment by dandv** [comment]
Hey @rnosov, @stevenhornung, was there a mistaken publishing of `accounts-entry` from your Meteor dev accounts?

**Comment by stevenhornung** [comment]
I accidentally published a couple of forked packages that we were using to atmosphere but had no way to remove/hide them until now.  They don't need to be in atmosphere.
