### ISSUE TITLE
any plans to open source the code for atmospherejs.com?

### ISSUE THREAD

**Issue by shankardevy** [percolatestudio/atmosphere#280]
Hi
atmospherejs.com is a beautiful site. Just wanted to check if there is any plans to release the code for the site?

https://github.com/oortcloud/atmosphere/issues/106#issuecomment-60354520

Thanks

**Comment by domyen** [comment]
Hey there, check this issue out: https://github.com/percolatestudio/atmosphere-beta/issues/219. We're in pretty much the same circumstance as we were then. Our team is building a suite of high-quality open source apps to ship with the Meteor framework. Check the first of them out with `meteor create todos`.
