### ISSUE TITLE
Getting download counts in search results

### ISSUE THREAD

**Issue by reel** [percolatestudio/atmosphere#281]
Great job with atmospherejs website!

To easily pick a package on search, would it be possible to add the number of downloads beside the star counts?

The not much people star packages at the moment and two insights are really critical:
- Number of downloads (community adoptions) -- We always have to open the package page to see this.
- Code frequency -- last update on GitHub (is the maintainer active and keeping up to date?)

Having this information on search results would be awesome and enable us to make faster decisions.

Thank's!

**Comment by domyen** [comment]
Thanks @reel, sounds like showing download counts earlier on in the search flow could be a good idea. Let's see what other folks think.

**Comment by tmeasday** [comment]
I'm inclined to agree with this.

**Comment by reel** [comment]
The small sparklines are nice but irrelevant in the search result as they don't compare on the same Y-axis with the other results.

**Comment by domyen** [comment]
Let's do it next Atmosphere sprint! Please print the app install count and reassign to me.

**Comment by dburles** [comment]
@dominicnguyen please check the visuals :)

**Comment by dburles** [comment]
@tmeasday you may want to eyeball this one

**Comment by tmeasday** [comment]
Can we go with the denormed version please @dburles

**Comment by dburles** [comment]
@tmeasday done

**Comment by tmeasday** [comment]
Good stuff, thanks @dburles
