### ISSUE TITLE
Travis instructions refer to mrt

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#282]
At https://atmospherejs.com/i/publishing . Leftover or intended? I've been meaning to add CI to one of my packages.

**Comment by tmeasday** [comment]
Hey @dandv - are you referring to within the meteor hacks article? I guess it's a little out of date, but probably still works. Perhaps @arunoda can say more?

**Comment by dandv** [comment]
Before the meteorhacks article, there's a `curl -L http://git.io/ejPSng`, which resolves to https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh, which uses mrt.

BTW another use of `mrt` on the page: 

"Alternatively, you can use `mrt link-package /path/to/my:package` to make that slightly easier."

**Comment by tmeasday** [comment]
That second use is legimate. Let's wait to see what @arunoda's comment is.

**Comment by arunoda** [comment]
Hi dan,

I'm planning to use meteor as the default command. See this PR: https://github.com/arunoda/travis-ci-meteor-packages/pull/30

But still there are some people who uses mrt to use custom meteor installations and do tests for older versions. No need mrt.

BTW: I'm going to accept above PR now. So default will be meteor.

**Comment by domyen** [comment]
Seems like we're all good here. Closing.
