### ISSUE TITLE
How are flags handled when a new package version is published?

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#283]
Will a package that has "earned" a flag have it removed when the author pushes a new version, or will the flag stay there forever, even if the author has addressed the issue?

It seems a little too easy, and anonymous, to flag packages. For example, I wonder if [this package](https://atmospherejs.com/timtch/flash-messages-plus) was flagged by mistake.

Maybe adding a "flagged by" field would increase the responsibility that a flagger should take before they flag?

**Comment by dburles** [comment]
Flags are reset once a new version is published.

> How does flagging work?
> Flags are hidden by default. When the number of flags is more than 10% of the downloads per version a warning flag is shown. The flag count is reset every version.

**Comment by dandv** [comment]
Awesome, thanks @dburles! That writeup was in the tooltip for flag icon. CC @timtch.
