### ISSUE TITLE
Please rm contributor `mrt` from dandv:caret-position

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#287]
https://atmospherejs.com/dandv/caret-position

Package is a wrapping of a `component`. `mrt` was never involved.

**Comment by udondan** [comment]
That originates from the migration. Tom migrated all packages and originally he then was listed as a contributor. Later that changed somehow to `mrt`. I think there is no way for Tom to fix this, as only you (and `mrt`?) should now have administrative access to that package. You can fix this easily yourself though with `meteor admin maintainers dandv:caret-position --remove mrt`

Source: https://hackpad.com/ep/pad/static/zN0we9sIjkH

**Comment by dandv** [comment]
Awesome @udondan, that worked!

**Comment by tmeasday** [comment]
Heh @udondan actually I am mrt too -- I just decided it was less confusing to have "mrt" as the migrator. Plus it made my profile page more interesting.
