### ISSUE TITLE
Slow performance while loading "See more" packages

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#288]
I'm searching for [schema form](https://atmospherejs.com/?q=schema%20form). After returning the first set of packages, Atmosphere takes a surprisingly long while to spit out a few more.

Screencast at http://screencast.com/t/wc3lmjKxZD missed the first slowness, but it's there every time you click "See more".

**Comment by domyen** [comment]
Will take a look next sprint. Really appreciate the screencasts btw, really helps us diagnose problems.

**Comment by splendido** [comment]
It also happens that already loaded packages changes their position...
You can grasp it searching for 'accounts' and then pressing on 'see more' two or three times...

**Comment by tmeasday** [comment]
I think this was a performance issue? It seems good for me now...

**Comment by tmeasday** [comment]
Going to close this for now. Let me know if you are still seeing it.
