### ISSUE TITLE
Please make a way to flag "broken" or "doesn't work with Meteor 1.0" packages

### ISSUE THREAD

**Issue by ssteinerx** [percolatestudio/atmosphere#289]
I've just tried a few packages only to find the Github link either missing or broken, along with the package not working with Meteor 1.0.x.

Please make a way for users to vote to flag/remove these packages.

Steve

**Comment by udondan** [comment]
You can already do that. There is a flag button next to the package name.

**Comment by ssteinerx** [comment]
Sorry, I should have been more clear.  I'm asking for better granularity. 

"Not working" doesn't mean "won't install" or "github link broken or missing."

Steve

**Comment by tmeasday** [comment]
I think this is what flagging is intended for really.

**Comment by ssteinerx** [comment]
Personally, I think flagging should allow comments.  An ambiguous flag without context is kind of an ambiguous flag without context.

S

**Comment by timbrandin** [comment]
+1

**Comment by udondan** [comment]
I think only a general commenting feature makes sense. I'm happy with the flagging as it is. A flag tells something is wrong. If flags are respected in order of search results and visible right there, that's ok. A user then would chose a package with no (or less) flags. If there is no package w/o flags the user can check the details in the comments. If you introduce flags with context, where would you start and stop? In the end you could have various flags for browser support for frontend features, os-compatibility, node-, meteor-version-compatibility... you can get really granular... but what's the point?

Comments are on the [roadmap](https://trello.com/b/RDZR8YGF/atmosphere-flight-path).

**Comment by ssteinerx** [comment]
General comments would be great!  (and would render the flag superfluous)

**Comment by tmeasday** [comment]
Well said @udondan. I don't think comments would make flags superfluous as they _do_ affect search ranking and are clearly indicated in search results.
