### ISSUE TITLE
Cannot execute package search from website

### ISSUE THREAD

**Issue by kevinchiu** [percolatestudio/atmosphere#291]
System:
Chrome (38.0.2125.111 - latest public release)
OS X 10.10

Repro:
1. Go to https://atmospherejs.com/
2. Type "blog" into the search field.
3. Press enter. (nothing happens)

Current workaround:
1. Copy and paste search term into URL after "?q="

**Comment by udondan** [comment]
Works for me. You not even need to press enter, it is updating live while you type.

Which browser do you use? Do you have any JS error messages on the console?

**Comment by kevinchiu** [comment]
Actually, speed seems to matter. If I enter my search query right when the page begins loading, it gets into a bad state. I'm on Chrome.

I'll try to record a video.

**Comment by kevinchiu** [comment]
Ok, it seems like if you enter a term and press enter quickly, it doesn't load any results.

Here is a video: https://www.youtube.com/watch?v=J2uERVZnR4A

Here is the error in the console: Failed to load resource: net::ERR_CACHE_MISS https://atmospherejs.com/?q=

**Comment by zol** [comment]
I can confirm this problem. Thanks @kevinchiu
