### ISSUE TITLE
I love Stars, Stars don't love me :(

### ISSUE THREAD

**Issue by benstr** [percolatestudio/atmosphere#293]
I am a crazy about stars. I have over 60 packages starred. When I go to my profile I am unable to load all the stars. Only the initial find of 20 starred packages show. When I select "See More" the page blinks then reverts back to the initial 20. How can I get a list of all my stars?

**Comment by dburles** [comment]
Hey thanks @benstr hmm it sounds like the pagination is broken there, I will investigate

**Comment by pandark** [comment]
Same here.

**Comment by benstr** [comment]
Confirmed. Thanks guys!
