### ISSUE TITLE
Search: performance & clarity

### ISSUE THREAD

**Issue by domyen** [percolatestudio/atmosphere#295]
Text pasted from Mat Lorica

> Your search feature doesn't work consistently. I type "redis" in the text field, hit return, and it just sits there and does nothing. It starts working as I delete characters from the search text, but then when I retype the missing characters it again just sits there with the wrong results.
> 
> I've attached screenshots. This is on the latest Ubuntu/Firefox.

I can't confirm that the results or the order of operations are a bug – _the correct results do eventually load_, rather there is some uncertainty because the results are taking some time to load (sometimes seconds for longer queries).

**Comment by domyen** [comment]
I notice some sluggish behavior when loading package data elsewhere as well (i.e., profile page). Anything happening upstream that might cause this?

**Comment by tmeasday** [comment]
@dominicnguyen our syncing server is suffering a bit, could be that you were connected to that one. We should probably move that server out of the web stack.

On the subject of unresponsiveness, can you be a bit more precise about the behaviour you've observed? I see from one of Mat's screenshots that he's typed "redis" without _any_ visual feedback -- I wasn't able to reproduce this, the best I can do is see the _number_ of packages loaded (without a spinner) and it hangs for a bit while it gets the package data.

I think it should show the spinner until the packages completely load, but I'm concerned about the other behaviour. I haven't been able to reproduce even with timing out the search publication.

**Comment by tmeasday** [comment]
![screenshot from 2014-11-11 05 26 03](https://cloud.githubusercontent.com/assets/132554/5005802/8b297aa0-6a8a-11e4-8c43-50bf274a4957.png)

In fact if you look closely at this screenshot you'll see "redis" is typed in but the URL hasn't picked it up. This seems like a client side bug. I'll try FF here, I guess ubuntu if I can't get it to happen.

**Comment by domyen** [comment]
Eagle eyes @tmeasday :)

Agree that we should fix the spinner. I can't reproduce Mat's initial report, I only experienced slowness but eventually the search did resolve.

**Comment by tmeasday** [comment]
It's not as trivial as it should be to fix the issue with the spinner (if you look at the code you'll see it was an explicit "this is easier than doing it properly" type move). I'll get to in on the next round.

**Comment by tmeasday** [comment]
I think the URL issue is probably https://github.com/percolatestudio/atmosphere/issues/291

**Comment by Slava** [comment]
Happens to me on Chrome Mac OS X as well.

**Comment by tmeasday** [comment]
@Slava Are you seeing #291 (hitting enter causes search to be cancelled)? That is a known bug that's fixed and soon to be deployed.

Or are you referring to seeing the number of packages and no spinner for an extended period of time (which is what this bug is tracking?)

**Comment by Slava** [comment]
I am referring to seeing no results in the list and a url looking like "https://atmospherejs.com/?q="

**Comment by tmeasday** [comment]
Cool. And did you hit enter?

**Comment by zol** [comment]
Fixed by our recent solr search deployment.
