### ISSUE TITLE
"Publishing Packages" Page

### ISSUE THREAD

**Issue by maxnowack** [percolatestudio/atmosphere#296]
I think there is an error on the ["Publising Packages" Page](https://atmospherejs.com/i/publishing):
In the "Testing your package" section, the parameters of the "ln" command are swapped.

**Comment by mfpierre** [comment]
I confirm this issue :+1:

**Comment by nooitaf** [comment]
Me confirm too, it should be 

``` bash
ln -s /path/to/my:package packages/my:package
```

**Comment by domyen** [comment]
lgtm
