### ISSUE TITLE
If I flagged a package, show it as flagged in search results

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#298]
Makes sense, no?

Use case: I'm reviewing d3 packages, https://atmospherejs.com/?q=d3

As I go and flag the dead ones, the flags won't appear in the search result cards until enough users flag the same packages (right now https://atmospherejs.com/meteor/d3 doesn't show as flagged, but I have flagged it).

As far as I'm concerned, I won't ever want to use a package I've flagged, so I want to see it as flagged in the search results too, in addition to on its package page.

**Comment by domyen** [comment]
This is a good point. Will review when we rework the search cards next sprint. I'll add it to the next up milestone!

**Comment by dandv** [comment]
Sprints! Milestones! How about http://scottchacon.com/2011/08/31/github-flow.html ?

**Comment by zol** [comment]
We're a small team splitting our time between numerous projects. Continuous deployment works well when you're primarily working on one project and can respond swiftly to the inevitable fires that are often burning.

Splitting our development effort up into sprints allows us to multiplex our time between projects more efficiently. There is a significant amount of overhead that's incurred when context switching between projects and we aim to minimize that as much as possible by grouping issues and feature development into sprints.

**Comment by tmeasday** [comment]
@dominicnguyen - should we visually indicate the "self" flag differently to the "community" flag?

**Comment by domyen** [comment]
I'm in favor of keeping it the same. Although I agree with the intent, the distinction is very nuanced so I wouldn't expect users to hold onto the difference between red and, say, yellow flags (there may be added confusion as a different color flag might also indicate how close it was to being 'fully' flagged). 

I'd prefer we use the same behavior so I'm happy with what's here. I'll confirm it, if you think otherwise we can further brainstorm.

**Comment by tmeasday** [comment]
Nah, I'm good with it.

**Comment by dandv** [comment]
Agree with the same indication - but when a user unflags a package, the community flag may still be in effect; however, the user must not believe that their unflagging was ineffectual.

**Comment by dburles** [comment]
It'll be indicated on the package page, so that should be okay

**Comment by dandv** [comment]
Was this deployed? A [search for PDF](https://atmospherejs.com/?q=pdf) doesn't show any flags, even though I've flagged about half of the results.

![image](https://cloud.githubusercontent.com/assets/33569/6053383/766e06a8-ac93-11e4-9a4c-42cf45e95a30.png)

**Comment by tmeasday** [comment]
I think this is a regression @dandv -- it still works on e.g. the homepage but no longer inside search. Will have something to do with our migration to solr. Thanks.

**Comment by tmeasday** [comment]
@zol the flags are published but I guess not being used to render the package lockup on this page?
