### ISSUE TITLE
Renaming / Deleting accounts

### ISSUE THREAD

**Issue by silkentrance** [percolatestudio/atmosphere#300]
I have a problem with my current account name. The name I took is already used on npm as either a prefix for or actual package name. As i want to publish my packages both on npmjs.org and atmosphere, I am currently stranded as I cannot use the same email address twice for multiple accounts.

Would it be possible to rename an existing account or delete it altogether including the published packages and start from scratch?

I have solved the issue by creating a new email address and a new account on atmosphere, but now I would like to have the old account removed ;-)

**Comment by silkentrance** [comment]
found a way to remove the published packages from the index, however, how would I delete the account altogether?

**Comment by domyen** [comment]
There's no way to 'delete' accounts at this time. Meteors oauth service handles most of the accounting so we haven't focussed much on building out a full account management system. That's probably down the track.

What's your account name/email?

**Comment by silkentrance** [comment]
The account name is vibe and the email is trancesilken@gmail.com.

The account can be readily deleted including also the packages published there as no one is actually using these packages but me :D

**Comment by tmeasday** [comment]
I think the issue is that you need to delete your Meteor Developer account. We don't control those, please contact the MDG (try meteor-talk?)

**Comment by silkentrance** [comment]
Thanks for the input. Will try.
