### ISSUE TITLE
Syntax highlight busted?

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#301]
Syntax highlight at https://atmospherejs.com/rubaxa/sortable is off:

![image](https://cloud.githubusercontent.com/assets/33569/5161694/78fba1f4-7364-11e4-8ee0-2a3ed0ba373e.png)

[On GitHub](https://github.com/RubaXa/Sortable/blob/master/README.md) it shows up just fine.

**Comment by tmeasday** [comment]
I don't think we even had syntax highlighting @dominicnguyen ?

**Comment by dburles** [comment]
@tmeasday See also #36

**Comment by tmeasday** [comment]
Although the classes are there if we want to create a theme.

**Comment by tmeasday** [comment]
Oh, OK I see, thanks @dburles. It looks like GH changed engine for generating these things.

**Comment by domyen** [comment]
Updated the styling to use the new format.
