### ISSUE TITLE
Show MD organization packages at /org/

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#302]
https://atmospherejs.com/?q=cfs - OK

https://atmospherejs.com/cfs/ui - OK

https://atmospherejs.com/cfs/ - 404. Would be nice to show all `cfs` packages there.

CC @raix ;)

**Comment by raix** [comment]
+1 btw. I'm getting 503 on https://atmospherejs.com/

**Comment by splendido** [comment]
Yeah, +1!

Btw this is a duplicate of #273 I guess.
Also tried to discuss about this [here](https://groups.google.com/forum/#!topic/meteor-talk/Vva1C-atOoo)

Luca

**Comment by dandv** [comment]
:cool: 

BTW why is https://atmospherejs.com/codemirror not working? It's an org I created.

![image](https://cloud.githubusercontent.com/assets/33569/5501235/d7dfbe52-870b-11e4-9305-1ee54403660e.png)

**Comment by tmeasday** [comment]
Perhaps you haven't yet published any packages?

**Comment by dandv** [comment]
I haven't published any packages under most of the orgs I've reserved, e.g. https://atmospherejs.com/echojs

**Comment by dburles** [comment]
hey @dandv have you signed into your `dandv` account on atmosphere since creating the org?

**Comment by dandv** [comment]
I hadn't signed into Atmosphere in a while, so I just logged out and back in. When I go to https://atmospherejs.com/codemirror I get a 404.

**Comment by tmeasday** [comment]
@dburles I thought we didn't create an org "account" until we saw a package for that org?

**Comment by dburles** [comment]
We get the users orgs in the login hook and that's where we call `ensureOrganization`
