### ISSUE TITLE
Increase weight of search keyword occurring in the package name

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#304]
https://atmospherejs.com/?q=fontawesome

![image](https://cloud.githubusercontent.com/assets/33569/5221980/a20a4132-763d-11e4-81a5-09ee9ac6273d.png)

As one can see, the second search result merely uses "fontawesome" in the description, while [the official Font Awesome](https://github.com/raix/Meteor-community-discussions/issues/14) package gets a lower ranking.

**Comment by tmeasday** [comment]
I think this is really a subset of what we were talking about here - #132

**Comment by tmeasday** [comment]
AFAIK this can't be done without a proper search service. Which is on the todo list (and covered by #132)
