### ISSUE TITLE
Git URL pointing to arbitrary path in the repo

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#307]
Is this possible? For [direct packages](https://github.com/raix/Meteor-community-discussions/issues/14), it would be great if the Atmosphere README was picked up from an arbitrary path, rather than the one in the root of the repo.

For instance, `git: 'https://github.com/dandv/Font-Awesome/tree/meteor-integration-5.0.0/meteor'` would show that Meteor-specific README when going to https://atmospherejs.com/fortawesome/fontawesome.

**Comment by tmeasday** [comment]
There is an undocumented `readme` field in `package.js` that should point to a raw markdown file (like https://raw.githubusercontent.com/percolatestudio/atmosphere/master/README.md).

Does that help?

**Comment by dandv** [comment]
I've just tested that with [twbs:bootstrap, pointing `readme`](https://github.com/MeteorPackaging/bootstrap/blob/meteor-integration/meteor/package.js#L14) to https://raw.githubusercontent.com/MeteorPackaging/bootstrap/meteor-integration/meteor/README.md, but I still see the README in the root of the repo at https://atmospherejs.com/twbs/bootstrap

**Comment by dandv** [comment]
`meteor admin change-homepage twbs:bootstrap https://github.com/MeteorPackaging/bootstrap/tree/meteor-integration/meteor` didn't change the README either.

**Comment by tmeasday** [comment]
Did you publish a new version of the package @dandv ?

**Comment by dandv** [comment]
Yep. Just published _2 again to make sure.

**Comment by tmeasday** [comment]
Hmm. I'm not seeing it:

```
{
        "packageName" : "twbs:bootstrap",
        "publishedBy" : {
            "username" : "dandv",
            "id" : "gwRKuoewrwi8MMbMB"
        },
        "version" : "3.3.1_2",
        "earliestCompatibleVersion" : "3.0.0",
        "containsPlugins" : false,
        "debugOnly" : false,
        "description" : "Bootstrap (official): the most popular HTML/CSS/JS framework for responsive, mobile first projects",
        "dependencies" : {
            "meteor" : {
                "constraint" : null,
                "references" : [
                    {
                        "arch" : "os"
                    },
                    {
                        "arch" : "web.browser"
                    },
                    {
                        "arch" : "web.cordova"
                    }
                ]
            },
            "jquery" : {
                "constraint" : "1.0.0",
                "references" : [
                    {
                        "arch" : "os"
                    },
                    {
                        "arch" : "web.browser"
                    },
                    {
                        "arch" : "web.cordova"
                    }
                ]
            }
        },
        "git" : "https://github.com/MeteorPackaging/bootstrap.git",
        "releaseName" : null,
        "compilerVersion" : "meteor/14",
        "ecRecordFormat" : "1.1",
        "source" : {
            "url" : "https://warehouse.meteor.com/sources/gwRKuoewrwi8MMbMB/1418339140070/znnPhcnJhH/twbs:bootstrap-3.3.1_2-source.tgz",
            "tarballHash" : "uwGTTpYSKGENs4pM65jsueKs6joRIOyKFroazh4aHr0=",
            "treeHash" : "ZFvf7g9e9yVZA7Ec7EBfFVDgQ8omUIDebFj96ypD9RY="
        },
        "lastUpdated" : ISODate("2014-12-11T23:05:40.609Z"),
        "published" : ISODate("2014-12-11T23:05:40.609Z"),
        "_id" : "Yfo9eSCHBp3kKpjay"
    }
```

I wonder if there's some special way you have to do it (only MDG have done it before). Will investigate.

**Comment by tmeasday** [comment]
Hmm. I'd guess they must be manually setting that field. @ekatek - is this something package authors can do themselves?

CF:
- https://atmospherejs.com/meteor/htmljs
- https://github.com/meteor/meteor/blob/devel/packages/htmljs/package.js
- https://github.com/meteor/meteor/blob/devel/packages/htmljs/README.md

**Comment by dandv** [comment]
Interesting... @estark37, how did you guys do that?

**Comment by zol** [comment]
@tmeasday Could you please follow up on this one.

**Comment by ekatek** [comment]
That wasn't actually a custom GIT path, but a custom README path. This has been deprecated in favor of the 1.0.3.1 changes that upload the README.md directly!

**Comment by tmeasday** [comment]
I guess we can close this right? Thanks @ekatek. @dandv let me know if there's a problem.

**Comment by dandv** [comment]
I've tried the README option and it works.
