### ISSUE TITLE
Atmosphere doesn't show anything special for unmigrated packages

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#308]
``` sh
$ meteor admin set-unmigrated summernote:summernote-compat
Setting summernote:summernote-compat@0.6.0 as unsuccessfully migrated ... done!
Setting summernote:summernote-compat@0.6.0_1 as unsuccessfully migrated ... done!
```

...wait 20 minutes...

https://atmospherejs.com/summernote/summernote-compat shows as any regular package.

Since `set-unmigrated` is currently our only mechanism of indicating that a package should not be used, I believe Atmosphere should reflect that in the package page in a more prominent manner than just displaying an empty History section.

**Comment by tmeasday** [comment]
You're right, it should show something. OTOH they don't come up in search results, so that's good.

**Comment by dburles** [comment]
@dominicnguyen I've added a placeholder on the packages page, up to you on how best to display it

**Comment by domyen** [comment]
Thanks dave. Packages now get auto-flagged if they're unmigrated.
