### ISSUE TITLE
Atmosphere API?

### ISSUE THREAD

**Issue by MiroHibler** [percolatestudio/atmosphere#309]
Are there any plans for API?

I'd like to get the list+descriptions (and more) of packages in my own app.

**Comment by dandv** [comment]
Check out the [DDP API](https://github.com/percolatestudio/atmosphere/issues/299#issue-48661932).

**Comment by gadicc** [comment]
As was [announced on Twitter](https://twitter.com/atmospherejs/status/558800047622455296), there is now a REST API, details in the https://atmospherejs.com/i/faq.  You get the full database in JSON.  @zol, guess you can close this now :)

**Comment by MiroHibler** [comment]
:+1: Thanks! :)
