### ISSUE TITLE
Search needs a loading indicator

### ISSUE THREAD

**Issue by serkandurusoy** [percolatestudio/atmosphere#31]
I had to do multiple searches thinking my keyword - collection :) - did not get a hit until I realized perhaps I should wait. Without a loading indicator, the search feels as if it is not working.

**Comment by dandv** [comment]
Search is so extremely fast for me, that I never felt the need for a loading indicator. In fact I was hoping to look in the source code to learn how they made it so fast, because the old Atmosphere was quite slow.

**Comment by serkandurusoy** [comment]
What about network lags? Those who are on mobile broadband or any other slow collection? I'm still experiencing slow search results.

**Comment by domyen** [comment]
@serkandurusoy good to design such allowances into the product.  We'll push this change with the next build.

**Comment by serkandurusoy** [comment]
Hi @dominicnguyen good to hear that, I'm working from a (_ehem_) sailboat and that's constantly reminding me of the 14.4 baud modem era.

**Comment by domyen** [comment]
@tmeasday reference 5b3fd2749b07d20f3caf3719a0127e3e4e77f18c. 
I've commented out the location where we add a 'search-loading' class when a search is...loading :)

**Comment by tmeasday** [comment]
Done.

**Comment by domyen** [comment]
Confirmed.
