### ISSUE TITLE
Search sometimes doesn't work

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/atmosphere#311]
https://www.dropbox.com/s/khrm6pjnj4ms8mf/Screenshot%202014-12-04%2012.13.14.png?dl=0

I went to the homepage, clicked in the search box, and typed "spiderable." You can see that the URL didn't update, as well.

**Comment by dburles** [comment]
hey @stubailo might the issue be similar to this one? https://github.com/percolatestudio/atmosphere/issues/291

this one I can reproduce and it's fixed, though not yet on production

**Comment by stubailo** [comment]
Yep, looks like a duplicate - sorry!
