### ISSUE TITLE
Unmigrated packages still show as dependants

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#314]
At https://atmospherejs.com/twbs/bootstrap, one can see summernote-compat, which I had set to unmigrated.

**Comment by dburles** [comment]
Thanks @dandv I'll check it out

**Comment by dburles** [comment]
@tmeasday I'm not sure whether it makes sense to be hiding them here if the package still depends on it

**Comment by tmeasday** [comment]
@dburles I guess we should filter out unmigrated packages from the _dependants_ and related packages (not the dependencies though!).
