### ISSUE TITLE
Minor graphical glitch

### ISSUE THREAD

**Issue by erasaur** [percolatestudio/atmosphere#315]
It's probably clearer to show a picture than explain with words:

![screen shot 2014-12-15 at 6 28 36 pm](https://cloud.githubusercontent.com/assets/8746334/5447814/d09ebc9a-8488-11e4-892c-94dd7d1fe4df.png)

**Comment by dburles** [comment]
Hey thanks @erasaur good catch

**Comment by dburles** [comment]
@dominicnguyen to reproduce just hover over a milestone

**Comment by domyen** [comment]
Cheers @erasaur. Fixed for next release  https://github.com/percolatestudio/atmosphere/issues/259.

**Comment by erasaur** [comment]
Awesome, thanks @dominicnguyen!
