### ISSUE TITLE
Long delay in reflecting new package version and README?

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#320]
Half an hour ago, I ran

```
$ meteor/publish.sh
Publishing rubaxa:sortable...
Reading package...
Bundling source...
Creating package version...
Uploading source...
Publishing package version...
Bundling build...
Creating package build...
Uploading build...
Publishing package build...
Published rubaxa:sortable, version 1.0.0_1
```

https://atmospherejs.com/rubaxa/sortable shill shows 1.0.0.

The new README should mention "Supports Meteor and AngularJS" - see [the README in the repo](https://github.com/RubaXa/Sortable/blob/dev/README.md).

**Comment by domyen** [comment]
Hey Dan thank you for reporting this! We're aware of the issue and are working with MDG to sort out the API change that was causing Atmosphere's importer to break today.

**Comment by zol** [comment]
Fixed.

**Comment by dandv** [comment]
@zol, can you verify if the latest READMEs are pulled? At the rubaxa link above, I do see the latest version, but the README is from the previous one.

**Comment by zol** [comment]
hey @dandv I'm afk for a few days. @tmeasday could you please check my fix next time you're on.

**Comment by tmeasday** [comment]
It seems good to me? At least it mentions Meteor and Angular on the atmosphere page's readme...
