### ISSUE TITLE
shields.io badge

### ISSUE THREAD

**Issue by cvrebert** [percolatestudio/atmosphere#321]
Have you considered adding an Atmosphere/Meteor package badge to http://shields.io/ ?

**Comment by domyen** [comment]
This just came up in conversation yesterday! We were wondering about how many people in the community use shields. How would you like shields to be integrated?

**Comment by cvrebert** [comment]
(I'm not actually a member of the community.)
Presumably a "[meteor | v1.2.3]" (or "atmosphere" instead of "meteor") badge, just like the other package managers listed on http://shields.io/
Some package managers additionally support a "downloads per time-period" badge.

**Comment by cryptoquick** [comment]
This would be super cool, especially if it checked your package versions like David does (for applications), and maybe another for displaying your package.js version (for packages).

**Comment by ncoden** [comment]
Bump 👋

**Comment by domyen** [comment]
Hey, one of the Atmosphere creators here, the folks at [Meteor](https://github.com/meteor/) now maintain this project. Not sure what the status of development is.
