### ISSUE TITLE
Package Install Count: large number shorthand

### ISSUE THREAD

**Issue by domyen** [percolatestudio/atmosphere#325]
Proposal: Limit the number of characters we display for install counts and instead use shorthand when possible. Not only is the difference between singular installs less impactful on packages with high install counts, internalizing very large numbers like 21,432 [as a user] is difficult for the brain to process. 

Feature: Use shorthand for numbers > 1000. Allowances for 1 decimal point only.

Examples:
- 1000 == 1k
- 1100 == 1.1k
- 20,000 == 20k
- 20,100 == 20.1k
- 20,150 == 20.1k
- 210,150 == 210.1k
- 1,030,000 = 1m

**Comment by splendido** [comment]
To be a bit fussy, the International Measurement Systems requires capital K and capital M to be used for kilo and mega respectively ;-)

k -> kelvin
m -> meter

**Comment by zol** [comment]
Deployed.

**Comment by dburles** [comment]
Hmm I think this needs a revisit, https://atmospherejs.com/packages/most-used

**Comment by zol** [comment]
Yep, it kind of defeats the purpose of having it. Could you please fix.

**Comment by zol** [comment]
Looking good.
