### ISSUE TITLE
Publishing instructions: need to set env var

### ISSUE THREAD

**Issue by lorensr** [percolatestudio/atmosphere#327]
https://atmospherejs.com/i/publishing 

This doesn't work for me:

```
mkdir -p packages
ln -s /path/to/my:package packages/my:package
meteor add my:package
```

`meteor add` can't find the package. It can find the package when I do this, instead of symlinking:

Environment

You will need to tell meteor where to find the local packages on your system. Simply add an environment variable called PACKAGE_DIRS which points to the root package directory. Just edit your ~/.bashrc, ~/.profile, (or whatever is appropriate for your OS) with the following:

export PACKAGE_DIRS="$HOME/path/to/packages"
All subdirectories under that path will be recursively searched first whenever you run meteor or meteor add. Remember to source this file or start a new console window so the variable it set.

(from @dweldon, https://dweldon.silvrback.com/local-packages)

**Comment by dburles** [comment]
hey @lorensr that's odd, might I ask what system you're on?

**Comment by lorensr** [comment]
OS X 10.10.1

```
$ m create --package foo
$ m create bar
$ cd bar
$ mkdir packages
$ ln -s ../foo packages/foo
$ m add foo
 => Errors while parsing arguments:           

While adding package foo:
error: no such package
$ m --version
Meteor 1.0.2.1
```

**Comment by dburles** [comment]
Make sure that the path to the package directory is absolute

**Comment by lorensr** [comment]
That worked, thanks! Maybe add that note to the page?

**Comment by dburles** [comment]
Added! Will come next release :)
