### ISSUE TITLE
Meteor.call on Atmosphere

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#328]
Besides the [DDP API](https://github.com/percolatestudio/atmosphere/issues/299), is there a way to execute Meteor calls to update an organization's profile? (I have many I want to update).

I tried

``` js
Meteor.call('updateProfile', Meteor.user()._id, {profile: {
  name: 'AVAILABLE - contact @dandv',
  description: '',
  website: '',
  twitter: '',
  github: ''
}}, function callback(e, t) {console.log(e, t)});
```

Validation passes, but all I get is `undefined` and the data isn't updated.

**Comment by dburles** [comment]
That looks perfectly fine to me.

**Comment by dandv** [comment]
Right - it was updating my own profile. How do I update the profile of the organization I'm visiting? I'd like to do a batch update for a bunch of orgs I own and set their name to "AVAILABLE" if there isn't one.

**Comment by dburles** [comment]
You should be able to pass in the organization `_id`, should be easy enough to reveal that by running `Meteor.users.find().fetch()`

**Comment by dandv** [comment]
Great, I have 136 (!) orgs in `Meteor.users.find().fetch()[0].organizations`, with `name` and `id`, but I need to check the "name" from the org profile. Is there a subscription to the organizations collection?

**Comment by dburles** [comment]
There's a publication called `user` that takes a username.

**Comment by dandv** [comment]
Thanks! Worked wonders:

``` js
Meteor.users.find().fetch()[0].organizations.forEach(function (org) {
  Meteor.subscribe('user', org.name)
})

Meteor.users.find().forEach(function (user) {
  if (user.isOrganization && !('name' in user.profile))
    Meteor.call('updateProfile', user._id, {profile: {
      name: 'AVAILABLE - contact @dandv',
      description: user.profile.description || '',
      twitter: user.profile.twitter || '',
      website: user.profile.website || '',
      github: user.profile.github || ''
    }})
})
```

**Comment by dburles** [comment]
Great!

**Comment by dandv** [comment]
Thanks - made a [tutorial](http://wiki.dandascalescu.com/howtos/Automating_any_Meteor_app_you_find_on_the_web#Putting_it_all_together) out of it :)
