### ISSUE TITLE
Odd display for some orgs

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#329]
https://atmospherejs.com/jadejs looks like most orgs, but https://atmospherejs.com/jsplumb looks different.

**Comment by dandv** [comment]
https://atmospherejs.com/livestamp is 404 even though I'm a member of the `livestamp` org.

**Comment by dburles** [comment]
jsplumb is a normal user. How recently did you create livestamp? An [onLogin](http://docs.meteor.com/#/full/accounts_onlogin) hook must be fired before the org will be stored.

**Comment by dandv** [comment]
`jsplumb` is an org I'm a member of. Don't quite recall but it's possible that I created it as a user initially, then asked someone at MDG to convert it to an org.

`livestamp` was created weeks ago.

**Comment by dburles** [comment]
Thanks I'll have to have a dig into that

**Comment by dburles** [comment]
hey @dandv can you check if the `livestamp` org is listed under your organizations on your atmosphere user?

**Comment by dandv** [comment]
It is:

`Meteor.users.find().fetch()[0].organizations.map(function (org) { return org.name }).join(' ')` ->

`"rubaxa semantic selectize pym heatmap ion meteorpackaging createjs sound momentjs highstock bounce flyer vis prezi appjs visjs voice audio gremlins jwerty gridster chartist shine blast bootstrapjs echojs raction scrollreveal highlightjs keyboard impulse slickgrid toastr title titlenotifier ani semanticorg aviary paymill keypress mousetrap gridlist audiolet audio5 rulersguide arangodb couchdb sortable zeroclipboard jcrop howler metru draggabilly typerenderingmix voix keymaster mixpanel pdf phaser fastclick progressjs gridlistjs fezvrasta wow telerik pace metro soundmanager2 syntax keyboardjs mdc scrollmagic osm lightbox tagsinput highlight seen intenseimages hubspot datatables metafizzy leaflet polymerpaper metroui fattable annyang c3js tween d3js flakes rateit summernote skeleton sperslides refills kendo hallo winjs buzz contour webix jadejs pageres stripejs polymer polymerjs shepherd packaging soundmanager semanticui reveal cut tingodb modios sticker ionic famousjs fortawesome isotope timesheet hackerwins timbre collection obelisk switchery mongodb rethinkdb twbs mongo hammer livestamp jsplumb codemirror react remix"`

**Comment by dandv** [comment]
It's a bit strange that `Meteor.users.find().fetch()[0].organizations` has 136 items but if I subscribe to all those orgs, I only get 133 objects in `Meteor.users` (of which one is myself). So four organizations aren't subscribed to.

``` js
Meteor.users.find().fetch()[0].organizations.forEach(function (org) {
  Meteor.subscribe('user', org.name)
})
Meteor.users.find().fetch()
-> Array[133]
```

The last item of that array is jsplumb, and it's different:

![image](https://cloud.githubusercontent.com/assets/33569/5639739/76695ccc-95d0-11e4-9c6c-f383cd7b0404.png)

**Comment by dandv** [comment]
To try and find those 4 missing orgs, I compared the `Meteor.users.find().fetch()[0].organizations` -> `id` with the `_id`s of the `Meteor.users.find().fetch()` but they are completely different.

What role do the ids in a user's organizations objects serve?

**Comment by dburles** [comment]
I've corrected the issue with the user -> org not becoming an org for next release.

**Comment by dburles** [comment]
Those id's are upstream from MDG's end, we don't use them for relationships on atmosphere

**Comment by dandv** [comment]
Should those ids not be published then?

**Comment by dburles** [comment]
No biggie, technically no. We can correct that. edit: fixed for next release

**Comment by tmeasday** [comment]
LGTM.

**Comment by zol** [comment]
Deployed
