### ISSUE TITLE
UI expectation

### ISSUE THREAD

**Issue by jadeqwang** [percolatestudio/atmosphere#33]
When I hover over anywhere on the box (e.g. the graph) of a package on the atmosphere frontpage, my mouse is a hand, which implies I can click on it. However, only clicking on the title will actually bring me there. Can you make clickable everywhere in the box?

By the way, what does the graph represent? Is it usage over time or commits over time?

**Comment by zol** [comment]
Thanks Jade, it looks like the graph is swallowing clicks - we'll fix this.

The graph represents 'atmosphere rating'. In fact, everywhere we show a graph or metric it's going to be the atmosphere rating unless we explicitly say otherwise.

**Comment by tmeasday** [comment]
We'll be elaborating on exactly what "Atmosphere Rating" is soon too...

**Comment by domyen** [comment]
Fixed with the next deploy.
