### ISSUE TITLE
Package not displayed on Atmosphere

### ISSUE THREAD

**Issue by d4nyll** [percolatestudio/atmosphere#330]
I published my Meteor package named [`d4nyll:epic`](https://github.com/d4nyll/epic) last night using `meteor publish --create`, and this morning I still cannot find it on [Atmosphere](https://atmospherejs.com/?q=epic). Is there some sort of a moderation process or I did something wrong?

**Comment by dburles** [comment]
hey thanks @d4nyll we're just working on a fix

**Comment by d4nyll** [comment]
I can see my [package](https://atmospherejs.com/d4nyll/epic) now. Thanks @dburles for the fix!

**Comment by bharath-cchmc** [comment]
Hey I don't see my package `bharath90:meteorgeo` not in the atmosphere. Is there a way to access my package? Some personalised link or something like that? Thanks
