### ISSUE TITLE
Github README.md not showing in Atmosphere

### ISSUE THREAD

**Issue by loredanacirstea** [percolatestudio/atmosphere#332]
Hi,

I have published a package on Atmosphere, but there is no README on the Atmosphere page, even though my package.js has a git url:

```
Package.describe({
 name: 'loredanacirstea:meteor-tabular-filter',
 summary: 'Collection filter based on aldeed:simple-schema structure.Output: Mongo Selector.',
 version: '0.1.1',
 git: 'https://github.com/loredanacirstea/meteor-tabular-filter.git'
});
```

I have also tried:

```
 meteor admin change-git loredanacirstea:meteor-tabular-filter 0.1.1 https://github.com/loredanacirstea/meteor-tabular-filter.git
 // I got:
'admin change-git' is not a Meteor command. See 'meteor --help'.

// but for:
meteor admin change-homepage loredanacirstea:meteor-tabular-filter https://github.com/loredanacirstea/meteor-tabular-filter
// I got:
Changing homepage on loredanacirstea:meteor-tabular-filter to https://github.com/loredanacirstea/meteor-tabular-filter... done
```

And still no readme showing on Atmosphere, even though when I do a `meteor show` , it now says:

```
Git repository at: https://github.com/loredanacirstea/meteor-tabular-filter.git
More information at: https://github.com/loredanacirstea/meteor-tabular-filter
```

I read about an undocumented [readme field in package.js](https://github.com/percolatestudio/atmosphere/issues/307), so I even tried:

```
meteor admin change-readme loredanacirstea:meteor-tabular-filter https://raw.githubusercontent.com/loredanacirstea/meteor-tabular-filter/master/README.md
// I got:
'admin change-readme' is not a Meteor command. See 'meteor --help'.
```

Package: https://atmospherejs.com/loredanacirstea/meteor-tabular-filter
GitHub: https://github.com/loredanacirstea/meteor-tabular-filter
- they are in-sync, except for the examples folder (github repo has it, atmosphere does not)

**Comment by zol** [comment]
Hi @loredanacirstea. Thanks for reporting this. Indeed your git url looks correct. We're looking into the problem and will report back.

**Comment by mitar** [comment]
Mine also does not show up: https://atmospherejs.com/peerlibrary/server-autorun (GitHub: https://github.com/peerlibrary/meteor-server-autorun)

**Comment by tmeasday** [comment]
The issue is

```
I20150118-20:09:24.136(11)? Exception while invoking method 'syncPackages' MongoError: not okForStorage
```

Due to updating a version (specifically `jonperl:paper@0.1.0`) with:

```
{
  ...
  dependencies: {
    "stevezhu:velocity.js": ...
    ...
  }
}
```

Googling around I think the issue is that you can `insert` such invalid docs (note the period in the field name) but you can't update them. 

Kind of an annoying problem.

**Comment by tmeasday** [comment]
OK, this is fixed.
