### ISSUE TITLE
Section about integrating 3rd party packages

### ISSUE THREAD

**Issue by tmeasday** [percolatestudio/atmosphere#334]
Probably condensing http://www.meteorpedia.com/read/Packaging_existing_Libraries

See https://github.com/percolatestudio/atmosphere/issues/297#issuecomment-68961378

**Comment by splendido** [comment]
What would you guys think about mentioning [autopublish.meteor.com](https://autopublish.meteor.com) among the possible strategies?

...it's probably in its early days, and it's not an official tool (although we had some little support from MDG, see [this](https://github.com/MeteorPackaging/autopublish.meteor.com/issues/3) and [this](https://github.com/MeteorPackaging/autopublish.meteor.com/issues/6) issues) but it might be a good solution to pursue.

**Comment by zol** [comment]
@tmeasday - we should discuss this. Would like to get it resolved but not sure on what exactly you were thinking.

**Comment by tmeasday** [comment]
I don't have any solid thoughts, I just think it makes sense to have a section in our publishing section about 3rd party packages. I'm not completely on top of it but resources that are worth mentioning are:
- http://www.meteorpedia.com/read/Packaging_existing_Libraries
- https://github.com/MeteorCommunity/discussions/issues/14
- https://autopublish.meteor.com

I guess I'll put something together for consideration. The publishing section is a bit messy anyway so I probably won't make it worse :/

**Comment by zol** [comment]
Nice, I can help clean it up too. We're almost done with this round!

**Comment by tmeasday** [comment]
Take a look.

**Comment by zol** [comment]
Looks great, thanks.

**Comment by zol** [comment]
Deployed.
