### ISSUE TITLE
Use GitHub Flavored Markdown for rendering READMEs

### ISSUE THREAD

**Issue by jonjamz** [percolatestudio/atmosphere#336]
There's quite a distinct difference between my package's README here:

https://atmospherejs.com/templates/tabs

...and here:

https://github.com/meteortemplates/tabs/

I had to publish an update just to make my docs look better on Atmosphere.

Since using GitHub repositories is standard, it seems to follow that GFM should be rendered correctly on Atmosphere.

I've had this issue with other packages as well--where I spent a good amount of time syncing what looked good on GitHub with what looked good on Atmosphere, and I'd rather spend that time working on actual coding!

**Comment by dandv** [comment]
The headings under "Features" aren't bolded on Atmosphere, e.g. "Sticky state."

**Comment by dburles** [comment]
@dominicnguyen you may have some input on this

**Comment by zol** [comment]
@jonjamz we'll be sorting out these discrepancies in the next week or so. Thanks for reporting it and sorry about the time and energy you've spent on syncing up the appearance in the past.

**Comment by zol** [comment]
This is fixed in #339 it will be deployed soon.

**Comment by dandv** [comment]
Maybe my comment from [#339](https://github.com/percolatestudio/atmosphere/issues/339#issuecomment-75012087) belongs here better.

**Comment by zol** [comment]
Its actually a separate issue, thanks @dandv .
