### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by erasaur** [percolatestudio/atmosphere#338]
![screen shot 2015-01-29 at 4 45 55 pm](https://cloud.githubusercontent.com/assets/8746334/5969297/c3496bbe-a7d6-11e4-9884-60901e50b600.png)

**Comment by dburles** [comment]
Thanks @erasaur I thought we had squashed this bug @dominicnguyen

**Comment by domyen** [comment]
We squashed it for long descriptions but have only now encountered a title of this length :)

**Comment by zol** [comment]
Confirmed and deployed.
