### ISSUE TITLE
Fix README support

### ISSUE THREAD

**Issue by zol** [percolatestudio/atmosphere#339]
First class readme support including proper handling of relative links and syntax highlighting, etc.

**Comment by zol** [comment]
Check: 
- [x] 1. `https://atmospherejs.com/meteorhacks/search-source` -> warehouse readme differs from GH readme. In warehouse "not-shift tilde" are replaced with `~`
- [x] 2. `https://atmospherejs.com/ongoworks/google-spreadsheets` -> warehouse & GH readme identical but coffeescript not parsed properly.
- [x] 3. `https://atmospherejs.com/mizzao/partitioner`, `https://atmospherejs.com/mizzao/tutorials` relative images and urls broken.
- [x] 4. `https://atmospherejs.com/raix/push` formatting broken.

**Comment by zol** [comment]
There are a number of issues here:

1 - It seems like the warehouse is serving us something different from GH (Edit: it turns out this is ok when github flavored markup is used to parse it).
2 - Coffeescript directive is not parsed properly.
3 - Relative images+links are screwed up.
4 - Formatting for checked lists is broken.

**Comment by zol** [comment]
It appears the using https://developer.github.com/v3/markdown/ to format our readmes will fix 2 & 4. Edit: it turns out 1. is also fixed.

**Comment by zol** [comment]
1. Is fixed by parsing/rewriting urls to be absolute. @tmeasday fixes are in f29668b, please review.

**Comment by tmeasday** [comment]
Code looks good but there is a minor bug that prevents it working with GH readmes. Will point out the line # where I get an error.

**Comment by zol** [comment]
Fixed in `07d2de0`

**Comment by tmeasday** [comment]
Works great. GJ.

**Comment by zol** [comment]
Deployed.

**Comment by dandv** [comment]
There's another bug. Single line endings are rendered literally, while any Markdown flavor suppresses them. At https://atmospherejs.com/webix/webix,

![image](https://cloud.githubusercontent.com/assets/33569/6263348/07cfe6f6-b7cb-11e4-8111-af43d6d77a1f.png)

**Comment by zol** [comment]
I don't get it, what's the bug? We use github's gfm API to parse readme markdowns. The markup on https://atmospherejs.com/webix/webix is the same as on https://github.com/dandv/meteor-webix/

**Comment by dandv** [comment]
The markup may be the same, but the rendering on GitHub is different:

![image](https://cloud.githubusercontent.com/assets/33569/6273986/af453ea6-b828-11e4-8152-c4bfaee06c2e.png)

**Comment by zol** [comment]
@dandv , my apologies. On closer examination, the markup _is_ different. I've opened #345 to track this. We'll narrow this down to a repro and if it is indeed GH's fault we'll raise an issue with them. Thanks for writing it up.
