### ISSUE TITLE
Back button should return to search results when applicable.

### ISSUE THREAD

**Issue by cmalven** [percolatestudio/atmosphere#34]
Steps to Reproduce:
- Search for "admin"
- Click the first result
- Click the browser's _Back_ button

Expected Result:
I see search results for the search "admin"

Actual Result:
I see the Atmosphere home page

**Comment by hellogerard** [comment]
Pro workaround: instead of hitting the `Back` button, hit the `s` key to bring up your last search w/ results. (Hitting `s` anywhere will bring up search.)

**Comment by domyen** [comment]
This is interesting. Perhaps we need a way to easily get back to the search results overlay via the back button.

@tmeasday What do you think about enabling this in the router and mapping it to a URL parameter only when the search is active. e.g., /package/search?q=jquery

A simple flow might be: 
1. Home (/)
2. Search (/search?q=jquery) 
3. Package (/jquery-ui)

If a user is on the site we keep context with whatever they were viewing previously.
If a user navigates to the search page from a new tab, we show them the search page overlaid atop the home screen.

One execution is to update the URL in realtime, another is to update _after_ a user clicks on a package from search.

**Comment by tmeasday** [comment]
This is a tricky one but I think it's a good idea.

**Comment by tmeasday** [comment]
Ok, I worked at this for a while but it really runs counter to the design of the Iron Router to try and have a page rendered on the screen (what's under the overlay) that's not encapsulated in the URL.

So the only way I can see to do it would be to work in some kind of hash approach, like `/packages/iron-router#search=foo`, but I'd be worried that that would cause problems in conflicting with _real_ hashes that may be used (such as the hashes on the IR readme). 

We could also try something vaguely similar using `history.replaceState()` directly, which would mean that the URLs aren't shareable, and there'd be no visible change to the address bar as you use the overlay. I'm not sure if this is a very good idea.

My thoughts right now are that it's just swimming upstream too much to try and have an _overlay_ (which is supposed to be transient) that has it's own URL (which is of course permanent).

**Comment by tmeasday** [comment]
Ok. Did this via method 2 in there (using `replaceState`).

Still not entirely sure it's not janky, but it's kinda cool. Please test @dominicnguyen

**Comment by domyen** [comment]
This is quite cool @tmeasday. The Atmosphere situation is a bit non-standard but one that we've run into in the past and I expect one that we'll run into in the future as well. I think it satisfies a lot of interaction that's been requested. However, I think we should try to shoot for a URL update to make page-to-page changes transparent to the end user. 

For consideration:
![pushstate-02-02](https://f.cloud.github.com/assets/263385/2412793/d8b3c196-aad6-11e3-89d9-64bdeb458513.png)

Re: animation/transition on back button
Currently we preserve the state of both the overlay & the page when a user goes back and thus  show two transitions (search overlay and page change). I propose that back triggers only the search overlay above the _current page_. Check out the diagram.

![searchoverlay-ia-03](https://f.cloud.github.com/assets/263385/2412884/014c4078-aad8-11e3-9f43-6a6f0f0005c3.png)

**Comment by tmeasday** [comment]
1. Regarding your first point (what URL to use).
   
   As I vaguely outlined above, it's not possible to not include the underlying page URL in the "search overlay URL". I see two options:
    a. `/packages/foo?q=bar`
    b. `/packages/foo#q=bar`
   
   Both have potential "overlaps" with existing query strings or hashes, but I guess a. we can control by just not using the parameter `q` anywhere else. I'll look at doing it this way.
2. Regarding the second point (not changing the underly page as you hit back):
   
   Considering 1. I don't think it's possible. 
   
   I'm also not sure it makes sense either. In your scenario, what if you hit "X" or "esc" as the last step? Do you end up at "package bar"? I feel like I'd expect to end up at "foo". 
3. Regarding the "double transition" -- I don't think you've really avoided it anyway.
   
   a. It happens when you "click on bar" (step 2.) anyway.
   b. In your proposed interaction, it'll happen when you go back a second time (step 4.) instead of step 3.
   
   OTOH, I think we can definitely take steps to make it a nicer interaction when IT is in place and we have more control over re-rendering.

**Comment by domyen** [comment]
So the decision is 
1. update url format to /packages/foo?q=bar
2. keep double transition with the intent to delay page load from bar to foo until _after_ the overlay animation finishes (pending iron-transitioner)

**Comment by tmeasday** [comment]
OK. Done. Please test.

**Comment by domyen** [comment]
It's working pretty well. 

I found a bug where a users search session doesn't persist. 
Repro: 
1. Open localhost:3000 in a private window
2. Bring up search using 's' key or 'search' link and type in 'fa'
3. Click on a package from search results 
4. Land on the intended page
5. Bug: notice that the search text in the menu isn't updated to read 'fa'
6. Bug: open up the search again and notice that the query isn't there

**Comment by tmeasday** [comment]
Fixed. Are we good to deploy this?

**Comment by domyen** [comment]
This is good. I'm going to close and open up the Iron-Transitioner issue to sequence animations for browser back & browser forward.
