### ISSUE TITLE
Jankyness on user profile page

### ISSUE THREAD

**Issue by zol** [percolatestudio/atmosphere#340]
Goto: https://atmospherejs.com/zoltan/~starred

Notice:
1. Switching between 'X Packages' and 'Y Starred' scrolls the page to the top. This makes sense as the route changes but is unexpected on this particular page as the perception is that you're toggling between tabs on the page.
2. When you switch to 'Y Starred' and the packages come down the wire the page reflow/layout is pretty janky. Not sure what the easy fix is for this one :-/

**Comment by tmeasday** [comment]
Not sure what the solution is here. Do we have a list of pages that when routing between you don't scroll to top? Seems a bit janky but I guess it'd work.

**Comment by dburles** [comment]
+1 on the above

**Comment by tmeasday** [comment]
1. is fixed.
2. Is tricker because the way that the starred package subscription works (via a client side join) kinda breaks the package-list model. In short, what happens is, when the stars subscription is _finished_ (and the second `package` subscription _starts_), the package list thinks it's ready, and renders, but there are no packages.
   
   So it renders empty. Thus, jankiness.
   
   The solution is a) server-side join (uggh) b) refactor package list to handle this case. Neither is simple but probably b) is the answer?

**Comment by tmeasday** [comment]
Take a look at 1. and hand back to me to do 2. unless you think it's not worth it at this point.

**Comment by zol** [comment]
@tmeasday Fix for 1. looks good. For 2., whats the downside of doing a server-side join in a non-reactive pub?

**Comment by dburles** [comment]
Dom and I intended for the list to be reactive as there's a very clear user action that modifies it, (starring a package) it may be unexpected for a user to star a package and not see their list update, what do you think?

**Comment by zol** [comment]
But... you can't star a package from this page, or am I missing something?

**Comment by dburles** [comment]
No you're right you can't, but you may have more than one browser/tab open. It feels bad (sad?) un-realtiming a Meteor app, especially a high profile one! :)

**Comment by zol** [comment]
@tmeasday - what are your plans on this ticket? I'm easy either way, happy with a fix now or we could park it for the meantime.

**Comment by tmeasday** [comment]
I guess the easy solutions are:

a) leave as is with jankiness
b) change to SS join / no reactivity. With downsides as mentioned by @dburles.

I'm leaning slightly towards b) -- you?

**Comment by zol** [comment]
Yeah, would prefer b) too.

**Comment by zol** [comment]
Code looks good but I'm not sure this is working. On localhost:
1. Goto `tmeasday`.
2. Star a couple of packages.
3. They don't show up on the 'starred' page even after a reload.

**Comment by tmeasday** [comment]
Hmm. Works for me. I'm confused about your step one ?

**Comment by tmeasday** [comment]
For 3. -- does the # of starred packages change? Because that _should_ be reactive.

**Comment by zol** [comment]
Sorry, that's a dodgy description. Attaching some screenshots (made starting with a refresh of that page):

![screen shot 2015-02-10 at 6 24 33 pm](https://cloud.githubusercontent.com/assets/81672/6140841/384142c8-b152-11e4-9fad-95b9ff85341b.png)

**Comment by zol** [comment]
![screen shot 2015-02-10 at 6 25 09 pm](https://cloud.githubusercontent.com/assets/81672/6140860/58fae122-b152-11e4-9cd2-3e0c18f96e0d.png)

**Comment by zol** [comment]
My bad, I got confused with how that page is supposed to work :) Test pass.

**Comment by zol** [comment]
Deployed.
