### ISSUE TITLE
READ.md not show up.

### ISSUE THREAD

**Issue by codylindley** [percolatestudio/atmosphere#342]
I used the meteor CLI to create a package.

It of course put a README.md in the directory. and the Package.describe contains:

documentation: 'README.md'

But the read me file does not show up. What am I missing here?

https://atmospherejs.com/telerik/kendo-ui-core-default-theme

**Comment by codylindley** [comment]
Ah, so the generated readme.md is not use by default by atmosphere. It's suppose to be served from a git endpoint. Is that right? The readme is not show up on the atmosphere page just beause it's part of the package.

**Comment by zol** [comment]
It looks like you've figured this out.
