### ISSUE TITLE
cannot edit profile

### ISSUE THREAD

**Issue by wstucco** [percolatestudio/atmosphere#343]
On the profile page, if I click edit then change something and click Save, nothing happens.  
No errors, no messages, it just doesn't save anything.  
tested on Chrome 40.0.2214.111 (64-bit) and Safari 8.0.3 (10600.3.18) on OS X 10.10 (Yosemite)  in both normal and incognito mode, with all the extensions and plugins disabled.

**Comment by zol** [comment]
Thanks for reporting @wstucco. This is a regression from our release earlier this week and will be fixed today.

**Comment by zol** [comment]
Fixed.
