### ISSUE TITLE
Unable to update organization I belong to 

### ISSUE THREAD

**Issue by bobiblazeski** [percolatestudio/atmosphere#344]
I want to update organization info for https://atmospherejs.com/nvd3 say add a website http://nvd3.org/ Why I'm unauthorized, though I belong to it.

Exception while simulating the effect of invoking 'updateProfile' r {error: 403, reason: "Unauthorized", details: undefined, message: "Unauthorized [403]", errorType: "Meteor.Error"…} Error: Unauthorized [403]

![image](https://cloud.githubusercontent.com/assets/2140890/6229809/c6f79f90-b6ba-11e4-8751-30086028901e.png)

**Comment by zol** [comment]
Thanks for reporting this @bobiblazeski . Its due to a regression caused by a recent hotfix. I've just pushed out a fix so please go ahead and try your change again.

**Comment by bobiblazeski** [comment]
Works well, thank you.
