### ISSUE TITLE
Some styling gone? Borders around buttons, meteor add

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#348]
There used to be borders here:

![image](https://cloud.githubusercontent.com/assets/33569/6313647/6d1076a0-b96c-11e4-8f25-a653469e4c54.png)

**Comment by dburles** [comment]
@dandv still there for me, what browser are you on?

**Comment by dandv** [comment]
Dug more into it - it happens only at 90% or less zoom in Chrome.

https://atmospherejs.com/nothingisdead/elasticity

**Comment by zol** [comment]
Thanks for reporting @dandv

**Comment by tmeasday** [comment]
I think this is a Chrome bug if anything, no @zol?

**Comment by zol** [comment]
@dominicnguyen would be the best person to weigh in on it. It's likely some high tech styling that we use that triggers an edge case in chrome. The same behavior is present in FF albeit at a much smaller zoom level.

**Comment by cvrebert** [comment]
FWIW, [in many cases, there's no good way to deal with (non-pinch) page zooming problems.](http://getbootstrap.com/getting-started/#support-browser-zooming)

**Comment by domyen** [comment]
Thanks @cvrebert, you're spot on. It's due to artifacting. When a stroke is set to 1px, zooming out results in subpixels that a browser will choose to render –or not. Cheers for the report! Closing.
