### ISSUE TITLE
Install counts seem to update infrequently

### ISSUE THREAD

**Issue by zol** [percolatestudio/atmosphere#349]
Raised by @msavin in #286.

If I go to a frequently used package, e.g https://atmospherejs.com/meteor/meteor-platform , I would expect the app installs to go up relatively often. Currently, they're sitting on 171,674. I've checked the worker logs and usage appears to be syncing without errors.

**Comment by zol** [comment]
@tmeasday could you please investigate this one.

**Comment by tmeasday** [comment]
Ok, somewhere along the line we started using `package['installs-per-year']` (a daily-denormed number that we use for sorting and displaying on the package lockup) on the show page.

Probably when we turned off the count publication temporarily. I guess we never switched it back when we turned it back on.

**Comment by zol** [comment]
Deployed and tested OK.
