### ISSUE TITLE
Organization logos/icons/avatars?

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#352]
https://atmospherejs.com/dandv shows a few of my collaborators being organizations for the 3rd party libraries I helped integrate. Is there a way to add logos to the profiles of those organizations?

**Comment by cvrebert** [comment]
:+1:

**Comment by splendido** [comment]
:+1:

**Comment by cvrebert** [comment]
Semi-duplicate of #319.

**Comment by tmeasday** [comment]
I'm going to close this as it's covered by #319
