### ISSUE TITLE
atmosphere is slow

### ISSUE THREAD

**Issue by KristerV** [percolatestudio/atmosphere#354]
I love what you guys are doing but wtf.. searching for packages is a pain.
1. when I go to atmospherejs.com I obviously want to search. I don't want to use my damn mouse to go get the "search" button wtf...
2. When searching the response takes ages. How about instead of reacting to each letter I type, you actually get the result I want when pressing enter and do it fast.
3. When going back from a package to the search view, please don't rerun the search.. it's slow enough already I don't want to wait unless I actually change the search, please.

Currently I've been waiting 2 minutes for a package to show up, this is intolerable (not always this bad, but it's still bad). Remove the animations, remove tha fancy letter-by-letter-reactivity and just make a simple environment that works! This has been pissing me off from the start and it's still here. I see you have no problem with this. No issues have been opened, am I the only one with this problem?

**Comment by timbrandin** [comment]
Something is not working as it should, I've also noticed. How about adding a search engine like Elastic or Solr? I might be able to help out settings those things up.. and then you could use Search Source by Meteorhacks and make awesome search!!

**Comment by ssteinerx** [comment]
It's not just searching, the whole pre-search page is dog-ass slow.

Also, I agree about especially the first stupid animation.  I go there to search, why not just leave the search field alone and use it.  Opening a pop-over to do that is just silly at best.

**Comment by zol** [comment]
Our apologies for this slow behavior, the app was undergoing some issues and this is not normal behavior. We've been experimenting with using a fleet of micro instances for the app servers and several of them had been unexpectedly throttled by AWS causing terrible performance throughout. We've increased the instance sizes and added cloudwatch alarms for low CPU credits to prevent this from happening again.

@timbrandin We use solr as our search backend. If you do a search and 'inspect element' on the total package count ('XXX' packages) just below the search field you'll see an attribute called `data-qtime`. This is the time the query took on the search backend, its usually < 10ms. Let us know if its ever substantially higher.

@KristerV -
1. You can use the '/' or 's' hotkeys for search.
2. This should take in the order of ms when the site is operating correctly.
3. We don't rerun the search when you go back, search results are cached in the client.

Regarding the search experience - we've had only positive feedback on it so far. I'm sorry to hear its not working out for you. We'll take your complaints into consideration when working on the next UI refresh.

**Comment by KristerV** [comment]
thank you for the clarification.
