### ISSUE TITLE
Duplicate account

### ISSUE THREAD

**Issue by kalepail** [percolatestudio/atmosphere#362]
I published two packages before logging into my meteor account. They ended up here.. https://atmospherejs.com/tyvdh My actual account is https://atmospherejs.com/tyler. Is it possible to trash the bad anonymous account?

**Comment by tmeasday** [comment]
Hi @tyvdh. Unfortunately you'd have to speak to the Meteor development group about that. Your best bet for now would just be to mark those packages unmigrated and they won't show up on atmosphere.
