### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by mitar** [percolatestudio/atmosphere#364]
My package is missing documentation on Atmosphere: https://atmospherejs.com/peerlibrary/blaze-components :-(

**Comment by tmeasday** [comment]
@zol seems like a bug in the URL rewriting:

```
Exception in defer callback: TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:107:11)
    at urlParse (url.js:101:5)
    at Url.resolve (url.js:408:29)
    at Object.urlResolve [as resolve] (url.js:404:40)
    at Object.<anonymous> (app/server/readme.js:115:11)
    at [object Object].exports.each (/home/ubuntu/meteor_app/bundle/programs/server/npm/npm-requires/node_modules/cheerio/lib/api/traversing.js:294:24)
    at Object.Readme._convertRelativeUrls (app/server/readme.js:113:10)
    at Object.Readme.getAndDenorm (app/server/readme.js:155:32)
    at app/server/publications.js:62:12
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
```

**Comment by zol** [comment]
@mitar just fixed this issue, it will go out later today and you won't need to do anything manual to have it begin working. Some of your `a` tags are missing `href`s and it turns out some of our parsing code wasn't careful enough.

**Comment by zol** [comment]
Deployed, @tmeasday check and close.

**Comment by mitar** [comment]
Hm, thanks. But things are still not perfect. :-( It seems like newlines are not ignored. See this example:

```
You can see how to register a component, define a
template, define a life-cycle hook,
event handlers, and a custom helper as a component method.
```

This should be all one line.

Also `*...*` makes it bold, not italics.

Also clicking on any link in the TOC redirects you to the GitHub, to a 404 page, and not move you around the README.

BTW, why don't you use GitHub API to render READMEs? I think that would be the best. See here for an example how a program is doing this: https://github.com/joeyespo/grip

**Comment by zol** [comment]
We do use github's api but it's inconsistent with the way they display
readmes on their site. One option would be to just grab the markup directly
from the site.

**Comment by mitar** [comment]
Interesting. Grip does a pretty good job with it. I have not found any discrepancy yet between what I get from it and what I then see on GitHub. Maybe you should check into it?

**Comment by zol** [comment]
Thanks, we'll look into it. We only noticed the issues once thousands of
people were hammering on the site :)

**Comment by tmeasday** [comment]
LGTM
