### ISSUE TITLE
How does README content get refreshed?

### ISSUE THREAD

**Issue by SamHatoum** [percolatestudio/atmosphere#369]
I have a package with a ton of [docs on GitHub](https://github.com/xolvio/meteor-cucumber), and on Atmosphere it has a [super old version of the docs](https://atmospherejs.com/xolvio/cucumber)

Same is true for another package I recently published. The [docs no GitHub](https://github.com/xolvio/meteor-inspectlet/) are out of sync with the docs [on Atmosphere](https://atmospherejs.com/xolvio/inspectlet)

Could someone please explain this voodoo to me? :) What do I need to do to ensure the docs stay in sync?

**Comment by dburles** [comment]
Hey @samhatoum I believe you're looking for `meteor publish --update` this will update your package metadata. See `meteor publish --help`

**Comment by zol** [comment]
@samhatoum we pull and cache the readme from github (unless there is one provided in your package). Updating the readme on github will have no effect until you publish a new version or update your package's metadata (as @dburles pointed out). Let us know if this fixes your problem.

**Comment by dandv** [comment]
> we pull and cache the readme from github (unless there is one provided in your package)

@zol, how are the two alternatives different? A README provided by the package means `documentation: 'README.md'` in `Package.describe`, but the README file itself is stored on GitHub.

> Updating the readme on github will have no effect until you publish a new version or update your package's metadata

Correct. `meteor publish --update` is sufficient.

**Comment by SamHatoum** [comment]
Thank you, this has sorted my whole life out, I've now achieved a state of Zen! :)

**Comment by tmeasday** [comment]
Hmm. @zol - I thought we used etags for GH so you didn't need to republish if you changed the readme? It doesn't appear to be working however..

**Comment by zol** [comment]
@tmeasday we don't anymore. I think perhaps when the package server started supplying readme our original logic changed. We should revisit this as looking closer at the code I don't think the current logic is right (the etag will basically have no effect).

Opened #377
