### ISSUE TITLE
I miss cmd-clicking

### ISSUE THREAD

**Issue by cmalven** [percolatestudio/atmosphere#37]
A pretty common use-pattern for me with package managers (and the web in general) is to do a search, then cmd-click (on a Mac) each package I'm interested in to open it in a new tab for later review/comparison. It'd be nice to have cmd-clicking back.

**Comment by domyen** [comment]
@cmalven I can confirm that this is very high on our todo list.

**Comment by cmalven** [comment]
@dominicnguyen That's great!
