### ISSUE TITLE
Doesn't show document without git url.

### ISSUE THREAD

**Issue by laosb** [percolatestudio/atmosphere#370]
If you try `meteor show lyuyea:select-doc`, the document is OK but there's no document on Atmosphere. I don't want to publish it on Github as a separated repo(Fact is I'm lazy to do that), and the doc should be shown even without a git url I guess?

**Comment by zol** [comment]
Thanks for reporting. A fix for this will go out for this today. You don't have to do anything, the fix will apply automatically.

**Comment by zol** [comment]
Deployed, @tmeasday check and close.

**Comment by tmeasday** [comment]
LGTM.
