### ISSUE TITLE
Please publish your search modal code as a meteor package

### ISSUE THREAD

**Issue by dcworldwide** [percolatestudio/atmosphere#372]
Not sure if this is the correct place. But the atmosphere package search modal is amazing. It would be great for the community if you packaged the code as a modal. Happy to help if you point me in the right direction.

**Comment by tmeasday** [comment]
Hey @dcworldwide, thanks for the kind words!

It's tricky with UI components like this to publish as a package because there are some many interrelated parts that require a lot of polish to get right and aren't necessarily easily re-applicable to another project. 

Having said that, I'm interested in which part of the modal specifically you are interested in:

1) The visuals/UX -- i.e the CSS animations / layout + hotkeys
2) The way that it drives the URL changes as you type in it and open/close it
3) The actual search functionality
4) Something else?

Let me know

**Comment by dcworldwide** [comment]
You're welcome :) The more i learn about the web the more i appreciate that packaging ux components is never as simple as it seems. 

Points 1 to 2 are of key interest to me. Is the app meteor? If so, do you mind sharing some details on your front end stack? I.e. Do you use IR? For transitions between the main page and the search modal, do you use percolate studio IR / animation packages? I'm also really interested which package you used to do point 2?

Creating an app like yours is something i'm still trying to figure out. My app will have a lot of page transitions and i'd like to make each state of the app represented by a route. I've started using IR and IR transitioner to achieve this. However i'm finding the page transition experience is not as smooth as i'd like :( At this point, I'm under the impression that i'll need to move away from these technologies and build something custom.

**Comment by tmeasday** [comment]
Hi @dcworldwide,

So a couple of things.
1. Yes it is a Meteor app.
2. We do use IR. When you open the search overlay, we change the current route with code like this (which basically appends `?q=text` onto the route):
   
   ```
   var current = Router.current();
   Router.go(current.route.getName(), current.params, {query: {q: this.text()}});
   ```
3. We do something very similar (with `replaceState: true`) on each keystroke as you type in the search field. This is all wired up manually, although perhaps it'd be a good package.
4. We implement the overlay via an element that is always on screen that is brought into and out of view via a simple CSS class (which drives the CSS animation also). I think we do a very similar technique in Meteor's local market example application.

What do you mean by "IR transitioner"? Which package is that? We use https://atmospherejs.com/percolate/momentum-iron-router, although honestly it's very fiddly and you need to spend a while on it to make it nice. But it does work.

**Comment by dcworldwide** [comment]
Hi @tmeasday, appreciate your feedback. Thanks. 

I'll run with a design very similar to yours. I wasn't aware of replaceState. Thats a great tip. 

The package I was referring to is https://github.com/ccorcos/meteor-transitioner. The package couples uihooks and velocity.js quite nicely. It works great for route transitions but I found it too limiting for my use case (i.e. I need to animate multiple elements during a transition). To achieve a UX affect like yours i've decided to limit my use of routed pages (instead using the same route with different parameters/hashes to define the active view).  Cheers
