### ISSUE TITLE
Local atmospherejs

### ISSUE THREAD

**Issue by sebakerckhof** [percolatestudio/atmosphere#373]
Hey,

I'd like to set up a local atmospherejs installation for my custom packages that are not really of value to publicize. I can modify meteor so it could first search my atmosphere install and if no results are found, it could then continue searching on the official atmosphere.js. But of course therefore I'd need to be able to run a local atmosphere. 

The only atmosphere related code I've found was the old one by oortcloud and I don't know if this still works with the new meteor package manager?

**Comment by zol** [comment]
Hey, Sorry @sebakerckhof you won't be able to run a local copy of the atmosphere web app.
