### ISSUE TITLE
Line wrapping mid-word

### ISSUE THREAD

**Issue by tysonclugg** [percolatestudio/atmosphere#381]
Package descriptions show with lines wrapping within words, due to use of `word-break: break-all;` -- looks ugly and breaks correctly formed words into garbage.

**Comment by tmeasday** [comment]
Hey @tysonclugg is there a particular package that is bothering you?

**Comment by tysonclugg** [comment]
Hi @tmeasday - see the highlighting below:

![Broken line wrapping](http://i.imgur.com/Ralxu0c.png)

**Comment by tmeasday** [comment]
Wow, crazy. What browser is that? Chrome / Linux?

**Comment by tysonclugg** [comment]
Ubuntu 14.04 / Firefox 37.0.2

**Comment by tmeasday** [comment]
Ahh. It does this on FF/OSX too. Heads up @dominicnguyen

**Comment by tysonclugg** [comment]
This got fixed at some point, package descriptions now have `word-break: break-word` applied instead of `break-all`.
