### ISSUE TITLE
I just can't satisfied with the search way of the site.

### ISSUE THREAD

**Issue by smileboywtu** [percolatestudio/atmosphere#383]
there are more than 5000 packages in the site of atmosphere, the the package with the same category is also so much, when we want to find some package we need, we need to read text, read text again and again. I just go tied of this way. some of the package with more and more docs, but without a simple example letting user have a preview, so I take much time finding the packages wanted. why don't you just let the contributor give a preview picture when he or she wants their package getting more popular within the developers? this also make the work easier and It will benefit you if you want to make some of the packages commercial. No one wants to pay for heavy work. People always happy using money to make things easier. Meteor is a technology for future, developer should pay more works on creative ideas but for learn and find tools again and again.

**Comment by tmeasday** [comment]
Hi @smileboywtu, did you know that packages can include a picture in their readmes? (For instance: https://atmospherejs.com/msavin/jetsetter).

We do our best to try and bring the best packages to the top of the list when you search, based on the metrics that we have available (although we aim to do better in the future).

I think at the end of the day choosing a library to rely on is something that takes time.

**Comment by smileboywtu** [comment]
I hope batter features coming soon. Thanks for your reply.
