### ISSUE TITLE
Question about front-end copy

### ISSUE THREAD

**Issue by sebakerckhof** [percolatestudio/atmosphere#384]
Hello,

Since working with private packages inside a team is kind of annoying in meteor (especially if you need to maintain multiple versions etc.)
Therefore I'm currently implementing a meteor package server,  API compatible with the official Meteor package server. When it's done I want to open source the package server, since other Meteor users seem to also have this problem. But I'd like to add a front-end to it where you can browse your private packages.
It'd be nice if it could look similar to atmospherejs. Therefore this question: can I copy the style of atmosphereJS for this front-end?

**Comment by tmeasday** [comment]
Hi @sebakerckhof,

I think we'd prefer it if atmosphere's brand remained distinct for now. 

Good luck with the project though. Let me know if you want to borrow any package syncing code ;)

**Comment by sebakerckhof** [comment]
Yeah, I've just based the front-end of microscope for now. Usually you wont have too many private packages, so this should be sufficient.

You can find the WIP here: https://github.com/sebakerckhof/stratosphere

The idea is to merge private packages with the public packages in one database and when there is a name collision (e.g. you want to have a custom DDP implementation), it will rename the upstream one and use the private one instead.

Currently I can import packages from the official package server and allow meteor-tool to sync with a stratosphere server. It works, but it's probably not very bulletproof yet, mainly because I have to make some assumptions by analyzing ddp traffic and looking into the meteor-tool code. So seeing the code from the official package server would be highly beneficial.

Most code to publish packages is also in place, but I'm struggling with the fact that meteor-tool wants to have logged in connection and it's quite complex and undocumented code (e.g. I have to do something to comply with getAccountsConfiguration in auth.js of the meteor tool and so on). Any help in this area would also be highly appreciated.

**Comment by tmeasday** [comment]
Hi @sebakerckhof, 

I don't have the code for the official package server implementation, but the syncing part is documented here: https://github.com/meteor/meteor/wiki/Meteor-Package-Server-API. I can share some code with how atmosphere does the syncing if it helps.

As for publishing, I can't help you with that -- no idea how it works!

**Comment by sebakerckhof** [comment]
Thanks. Knowing that earlier could have saved me a lot of work.
Just one question. I guess you also have a mongodb backend in which you import the package data.
How do you guys handle dots in dependency key names?

For example. A version record had a dependencies nested object. This dependencies object again has sub-objects for each dependency. The key being the same as the package name of the dependencies.
So for example:

```
"dependencies":
{
 "meteor":{...},
 "velocity.js":{...}
}
```

The problem is, that mongodb will error when a key name has a dot (e.g. velocity.js in the example above), as it clashes with their query syntax.

I guess you guys must also have encountered this problem?

**Comment by tmeasday** [comment]
Hey @sebakerckhof, we sure did. Our solution (which I'm not a huge fan of. A temporary solution... that's still here):

```
  // XXX: We can't store object keys with `.` in them in mongo. #332.
  // temporary solution is to map them to '\uFFOE'
  var deps = {}
  _.each(versionObj.metadata.dependencies, function(val, key) {
    deps[key.replace('.', '\uFF0E')] = val;
  });
  versionObj.metadata.dependencies = deps;
```
