### ISSUE TITLE
Local Atmosphere for testing?

### ISSUE THREAD

**Issue by trusktr** [percolatestudio/atmosphere#390]
Can I run Atmosphere locally, then tell Meteor to use the local Atmosphere (falling back to the official one when packages aren't found) so I can test how packages work without posting non-working junk on Atmospherejs.com?

**Comment by tmeasday** [comment]
Hey @trusktr,

Sorry to keep batting you around but Atmosphere is just a front end, you'd really need to speak to MDG (i.e. open an issue at github.com/meteor/meteor) about running a custom backend.

You may be interested in this: https://github.com/percolatestudio/atmosphere/issues/384

**Comment by trusktr** [comment]
Ah, that's so cool. Thanks!!

On Friday, May 29, 2015, Tom Coleman notifications@github.com wrote:

> Hey @trusktr https://github.com/trusktr,
> 
> Sorry to keep batting you around but Atmosphere is just a front end, you'd
> really need to speak to MDG (i.e. open an issue at
> github.com/meteor/meteor) about running a custom backend.
> 
> You may be interested in this: #384
> https://github.com/percolatestudio/atmosphere/issues/384
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/percolatestudio/atmosphere/issues/390#issuecomment-106974054
> .

## 

/#!/JoePea
