### ISSUE TITLE
How do I enable the GitHub / ReportBugs button?

### ISSUE THREAD

**Issue by SamHatoum** [percolatestudio/atmosphere#392]
Hey ho

I've tried to do `meteor publish --update` but that doesn't seem to work. I think I have the right stuff in my `package.js` [here](https://github.com/xolvio/meteor-cucumber/blob/develop/package.js#L9)

Am I missing something?

**Comment by tmeasday** [comment]
That URL looks malformed to me. Should it be: `https://github.com/xolvio/meteor-cucumber.git` ?

**Comment by SamHatoum** [comment]
that'll be why! Thanks Tom :)
