### ISSUE TITLE
semantic:ui-css isn't updated to the latest version

### ISSUE THREAD

**Issue by avalanche1** [percolatestudio/atmosphere#395]
Why https://github.com/Semantic-Org/Semantic-UI-CSS/ has ver 2.0.3 and https://atmospherejs.com/semantic/ui-css ver 2.0.**2**? Aren't they kept in sync automatically?

**Comment by zol** [comment]
No, they're not. The author has to do a `meteor publish` which it looks like they haven't done yet.

**Comment by jlukic** [comment]
We're using https://autopublish.meteor.com/ and it looks like the build has errored. I'll take a look
