### ISSUE TITLE
[CRITICAL] Atmosphere extremely slow

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#397]
Starting ~12 hours ago, Atmosphere has been slower and slower. Now I can't even load pages.

https://atmospherejs.com/wylio/mandrill has been frozen at the spinner for minutes.

Here's a GTMetrix. I think they timed out at 20 seconds:

https://gtmetrix.com/reports/atmospherejs.com/eo8MEQTI

DareBoost gave up after 30 seconds:

https://www.dareboost.com/en/report/55ac50670cf21c4782338889

In my browser:

![image](https://cloud.githubusercontent.com/assets/33569/8768920/101c89b8-2e45-11e5-93f0-736f5483c663.png)

**Comment by tmeasday** [comment]
Hi @dandv - thanks for the report. One of our web machines had run out of CPU credit. Is it better for you now?

**Comment by dandv** [comment]
Yes, thanks for the quick fix.
