### ISSUE TITLE
Unable to create organization

### ISSUE THREAD

**Issue by ghost** [percolatestudio/atmosphere#398]
I recently created the `ixorg` organization on Meteor Developer Accounts. I even published a package under its namespace, and everything went fine, but I cannot find either the org or the package on Atmosphere?

**Comment by tmeasday** [comment]
Thanks @schisma - this was a syncing issue at our end. I appreciate the report, very helpful.

I think it's fixed now? Let me know if not.

**Comment by ghost** [comment]
Yeah, thanks!
