### ISSUE TITLE
Beta site doesn't load on iPhone Safari

### ISSUE THREAD

**Issue by aldeed** [percolatestudio/atmosphere#41]
In Safari on iPhone 4S running latest OS, the site won't load. Seems to continually refresh or something.

(On desktop, it's everything I wanted and more. Thanks!)

**Comment by Slava** [comment]
It might be related to the bug in Meteor which should be fixed in the next Meteor release.

**Comment by zol** [comment]
Thanks @aldeed - it's working fine for me and others. I'm having the same issue with docs.meteor.com on my desktop safari right now - sounds like it's a known issue with Meteor that's currently being resolved.

**Comment by tmeasday** [comment]
Going to close this one and hope it goes away for you @aldeed
