### ISSUE TITLE
Atmoshpere is not refreshing package data, now lagging behind more than 24 hours

### ISSUE THREAD

**Issue by serkandurusoy** [percolatestudio/atmosphere#411]
Take a look at https://atmospherejs.com/packages/recent to see that the most recent package seems to have been published more than 24 hours ago.

Also, there is an ongoing discussion over at https://forums.meteor.com/t/atmospherejs-com-metadata-is-not-being-picked-up/9338/10 that seems related.

**Comment by tmeasday** [comment]
Ok, I think this is sorted out. Thanks for the report @serkandurusoy.

**Comment by serkandurusoy** [comment]
:+1:
