### ISSUE TITLE
Scrolling down is impossible while the "feedback" button is hovered

### ISSUE THREAD

**Issue by Slava** [percolatestudio/atmosphere#42]
The orange button in the right top corner appears on the scroll down. Once it appeared, if your mouse pointer happened to be located in the area of the button, you can't scroll down. You can scroll up however.

Mac OS X Mountain Lion, Google Chrome 32. Super low priority, just letting you know :)

**Comment by tmeasday** [comment]
Hmm. That's a funny one.

Not sure there's much we can do about it. @dominicnguyen ?

**Comment by domyen** [comment]
There isn't much we can do about it without changing the structure of our app (which is optimized for iron-transitioner). Let's wait till we get there and reassess.

**Comment by domyen** [comment]
Closing until there's a solution that doesn't require hacking.
