### ISSUE TITLE
Is app installs counter broken?

### ISSUE THREAD

**Issue by barbatus** [percolatestudio/atmosphere#420]
I noticed that counters for some new packages are zero for a week or so already (e.g. https://atmospherejs.com/kadira/graphql)

**Comment by dburles** [comment]
+1

**Comment by selaias** [comment]
+1

**Comment by dufia** [comment]
+1

**Comment by tmeasday** [comment]
Hi all, yes it is broken, fix coming very soon, thanks for the reports.

**Comment by barbatus** [comment]
@tmeasday how does it work? It seems failing to count properly again...

**Comment by tmeasday** [comment]
Hi @barbatus - I think the problem is fixed now. Are you still seeing problems? Can you post a specific example?

**Comment by barbatus** [comment]
@tmeasday I am sure this pkg https://atmospherejs.com/barbatus/ionic2-meteor was installed multiple times while the counter shows zero.

**Comment by dufia** [comment]
I think Top Searches section is broken too but I am not 100% sure :)
