### ISSUE TITLE
"meteor publish --create" fails with "Error: socket hang up"

### ISSUE THREAD

**Issue by philipmjohnson** [percolatestudio/atmosphere#424]
It is not possible to publish a new package to Atmosphere.  A variety of users have experienced this problem in the past 24 hours:

https://forums.meteor.com/t/cant-publish-new-package-error-socket-hang-up/15949

Could you please provide information on when this problem will be fixed?

**Comment by tmeasday** [comment]
Closing this, as pointed out on the other issue, that was the correct spot to post this.
