### ISSUE TITLE
README.md didn't load up for some reason?

### ISSUE THREAD

**Issue by javascriptlove** [percolatestudio/atmosphere#425]
I just published a package, and still don't see a readme after an hour or so. I've also tried updating the version, removing/adding the 'documentation' field, but still nothing.
It would be good to see what's going on with the meta data on the package page (if you are logged in as creator). Btw there's no GIT field in this package, could it be the issue? The other package has docs, but it was published a couple months ago

the package in question is
https://atmospherejs.com/linguahouse/i18n-generator

**Comment by tmeasday** [comment]
Hi @javascriptlove, thanks for the report. I've fixed the issue, the fix should go out soon.

**Comment by zol** [comment]
:+1:

**Comment by tmeasday** [comment]
Ok, this issue appears to be solved, let me know if not @javascriptlove
