### ISSUE TITLE
Cannot publish meteor module

### ISSUE THREAD

**Issue by desaiuditd** [percolatestudio/atmosphere#436]
When I'm trying to update my meteor module with meteor publish command, following error occurs:

```
=> Errors while publishing:                   

While uploading documentation:
error: Error: 140735189155840:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:782:


```

Any idea what could be wrong ?

**Comment by tmeasday** [comment]
What platform are you publishing from? I've not seen that before.

**Comment by desaiuditd** [comment]
I think this was my bad. I was on a restricted internet network and probably that network was blocking the network packets. I tried this from my home network and it got through.

Thanks for the followup though. Closing this one.
