### ISSUE TITLE
List new packages

### ISSUE THREAD

**Issue by arunoda** [percolatestudio/atmosphere#44]
We need a list of newly added and updated packages as well.

**Comment by ai10** [comment]
yes; freshmeat may be more interesting than trending.

**Comment by Lauricio** [comment]
definitely

**Comment by queso** [comment]
:+1:  I assume there is a freshness built into the package ranking?  I am sure there comes a point where a lack of updates might indicate dead projects...

**Comment by zol** [comment]
Yes there is. We also factor in install count as a lack of updates but a high number of installs may signal a mature, well loved package.

**Comment by tmeasday** [comment]
Going to close this as a dupe of #28
