### ISSUE TITLE
https://atmospherejs.com/ does not work 

### ISSUE THREAD

**Issue by 0xSheff** [percolatestudio/atmosphere#444]
I don't see any packages: http://prntscr.com/c2okva  http://prntscr.com/c2ol0o  http://prntscr.com/c2ol4t

if I try to search - I see endless loading: http://prntscr.com/c2oljl

**Comment by lyquocnam** [comment]
+1

**Comment by abdullah-bl** [comment]
+1

**Comment by fIa5h** [comment]
+1

**Comment by cleandersonlobo** [comment]
+1

**Comment by josiahstapleton** [comment]
I think this is browser specific....does not work on chrome but works on firefox for me.
![image](https://cloud.githubusercontent.com/assets/8466962/17465953/5fc9328e-5cd1-11e6-9662-f370c5d87ed0.png)

**Comment by tmeasday** [comment]
We had a couple of containers with broken Mongo connections (thus the different behavior across browsers). Better now?
