### ISSUE TITLE
Open package in new tab

### ISSUE THREAD

**Issue by sclausen** [percolatestudio/atmosphere#47]
You are not able to right klick on a package and select open in new tab/window, neither does the middle mouse button work.

**Comment by dburles** [comment]
hey @Phosphoros I believe this same issue has been reported https://github.com/percolatestudio/atmosphere-beta/issues/37

**Comment by sclausen** [comment]
Sorry, the issue title didn't meant anything to me, so I didn't noticed the similarity.
