### ISSUE TITLE
Using browser history back from github don't work as expected

### ISSUE THREAD

**Issue by skeetmtp** [percolatestudio/atmosphere#48]
- start from http://beta.atmospherejs.com/
- click on one trending package (for ex collection2)
- click on github link
- click on browser back  button : no bug , we reach collection 2 package page
- click on browser back  button again 

=> see url is not matching currently displayed page

**Comment by tmeasday** [comment]
This is actually a bug in iron-router: https://github.com/EventedMind/iron-router/issues/250

Will be fixed in the next release of IR and soon after here.
