### ISSUE TITLE
Search needs improvement

### ISSUE THREAD

**Issue by nitya** [percolatestudio/atmosphere#49]
Search on "iron router" brings up 1 package (accounts-entry) but not the most intuitive popular result (iron-router)

Search by "iron", "router" or "iron-router" (exact hyphenated match) works as desired. However given search is central to this application, and given most packages are hyphenated names, this issue could become critical.

A simple solution could be to take the search for "iron router" and show combined results from queries for "iron", "router" and "iron router" -- where each result card simply shows the search query tags that correspond to it.

**Comment by tmeasday** [comment]
Also: #38 and #26

**Comment by tmeasday** [comment]
Ok, did a vaguely better search:
- properly splits up terms
- searches author name
1. I don't think there's much we can do about the packages that have github URLs in their descriptions. This is kind of poor metadata on those packages.
2. We could search the readme, but I feel this is going to get a lot of false positives.

I think we can improve this further once MDG is hosting the data and it's a bit cleaner.

**Comment by domyen** [comment]
@tmeasday Perhaps we don't register URLs in search via a regex? Other than that I think we're good for now.

**Comment by tmeasday** [comment]
What do you mean exactly? Do you mean match `term` **as long as it's _not_ in a URL**?

**Comment by domyen** [comment]
e.g., Say we have a description that looks like "this package is a meteor wrapper for bootstrap (http://bootstrap.com)", we'd only register the keywords "this package is a meteor wrapper for bootstrap" and omit the URL. 

From a best practice standpoint, URL's shouldn't be in the description.

**Comment by tmeasday** [comment]
Hmm. I tried to figure out how to avoid matching URLs via a regexp but didn't have an success.

@zol - any ideas? I need a way, given say `"github"` to construct a regexp `RE` such that:

```
"something about github".match(RE) // is true

"something http://gihub.com/foo something else".match(RE) // is false
```

Any thoughts?

**Comment by tmeasday** [comment]
Oh and it also needs to work with any substring of `"github"`.

**Comment by tmeasday** [comment]
Going to move this to future as everything bar URLs is resolved (and I don't know how to fix that).
