### ISSUE TITLE
Most Used not useful?

### ISSUE THREAD

**Issue by hellogerard** [percolatestudio/atmosphere#52]
Hello,

Firstly, great work guys. Best package repo website out there. After looking at this a lot for the past 2 days, the "Most Used" section on the home page doesn't seem to change much, which makes sense. Maybe we could replace it with something more dynamic, like "Most Recently Updated" (#44 and #28)?

Gerard

**Comment by tmeasday** [comment]
Thanks for the report @hellogerard. We're going to stew on this a bit longer but for now I'll close this and cover it under #28
