### ISSUE TITLE
Close button not working on feedback window (on mobile Safari)

### ISSUE THREAD

**Issue by chazbatrouney** [percolatestudio/atmosphere#55]
The X (top right) is unclickable from the feedback screen, although all other functionality is available. Running latest iOS 7 with Safari.

**Comment by zol** [comment]
Try harder Chaz :) agreed its a problem though.

**Comment by chazbatrouney** [comment]
I was tapping like crazy with my finger, in all sorts of awkward positions. 

Just thought I would give my two cents worth - but seriously, it's looking amazing!

Watched the YouTube clip from sanfran dev conference, pretty exciting for percolate. 

Chaz
