### ISSUE TITLE
Use SSL

### ISSUE THREAD

**Issue by Tarang** [percolatestudio/atmosphere#56]
It would be nice if atmosphere used SSL. 

Some ISPs don't have websockets because they use transparent proxies which dont support them but it makes for a bit of a slow experience falling back to XHR

Of note here is that the DDP client would not be able to connect in this case, since there is no support for XHR with the node-ddp-client module. In the event that meteorite used the new atmosphere without SSL some clients in a few countries would not be able to connect to it

**Comment by tmeasday** [comment]
Good point. Thanks @Tarangp .

@zol  - can you sort this when you have a chance?

**Comment by Tarang** [comment]
Atmosphere now using ssl - closing.
