### ISSUE TITLE
Star/favorite a package in Atmosphere

### ISSUE THREAD

**Issue by kylemclaren** [percolatestudio/atmosphere#57]
Will you guys add this functionality? So I don't have to go to the GitHub repo to do so.

**Comment by tmeasday** [comment]
Hey @kylemclaren. Definitely a planned feature. Not sure exactly when it'll appear. :)

**Comment by kylemclaren** [comment]
@tmeasday Good to hear! Possibly have the option of signing in with Meteor developer account and/or GitHub :) Cheers.

**Comment by dandv** [comment]
:star:
