### ISSUE TITLE
jade package has no GitHub repo linked

### ISSUE THREAD

**Issue by Slava** [percolatestudio/atmosphere#58]
The `jade` package has no link to its GitHub repo and its Readme.md. Not sure if it is the fault of the author or the Atmosphere: http://beta.atmospherejs.com/package/jade

**Comment by zol** [comment]
It's because the git url does not end with ".git" and it's currently included in our match for deciding whether the 'git' link is for github. @tmeasday is there any reason for not loosening our regexp here and just relying on the first part of the match (github.com)

**Comment by tmeasday** [comment]
I guess not. I'm not sure the package will actually work if they've mis-specified the URL however.

**Comment by mquandalle** [comment]
I've fixed the git URI in the `smart.json` file. How could I refresh the atmosphere data without releasing a new version of my package? I guess this question is also relevant for a `README.md` modification.

**Comment by zol** [comment]
You have to release a new version to fix this - you should just increment the patch version. It’s good practice to do so whenever you release something that’s changed, even if you think it should make no difference.

**Comment by domyen** [comment]
This seems fixed. Closing.
