### ISSUE TITLE
Serious flaw in *trending/popular* algorithm

### ISSUE THREAD

**Issue by serkandurusoy** [percolatestudio/atmosphere#62]
As I go through which packages are trending/popular, I recognize a few from the Discover Meteor book.

It seems that those packages that are used in the book are almost always close to the top in the popular lists.

I think this points to a flaw that any (although rightfully) successful book or open source app that gets installed/run by many people will immediately render those packages used there as highly popular.

While such situation points to the popularity of the book/app, it does not necessarily point to the popularity of the packages.

Packages like spin, HTML5-history-api, router(!) appear to be very popular although I doubt if they actually are.

This brings me to the opinionated conclusion that I think apps should have some sort of signature so that the exact same app installing some packages from atmosphere can be identified.

In fact, while at it, computers asking for mrt install should have some sort of signature. Elaborating further on this; what happens if I spend an hour everyday doing (or scripting) this for a month?

```
$ mrt create someapp
$ cd someapp
$ mrt install some-silly-package
$ cd ..
$ rm -fr someapp
```

So, there should be some way of identifying the popularity by distinct users (client computer signatures)

The new meteor developer accounts could -help- mitigate parts of this problem.

Elaborating further, we can even segment by geography if IP addresses are stored as well.

Time of day (ie, popularity of a package among night-owls against daytime programmers - which I think is a very valuable piece of information).

Popularity by operating systems! Also valuable information for target platform segmentation.

One can go crazy with this.

**Comment by tmeasday** [comment]
Hey @serkandurusoy, thanks for the detailed thoughts and write up.

Here's our current thinking on all this:
1. Packages from the book:
   - Well I guess they must still be popular. We updated the book to use IR in late november and only started tracking package downloads in late december, so I can only conclude there must be a significant group of people that haven't made the transition yet.
   - It is unfortunate that HTML5-History-API and page-js-ie-support, which are dependencies of it, make the list. But then again would you want to hide them? I'm not sure.
2. App signatures:
   - We have significant plans here. Watch this space! (or the mailing list anyway). Hopefully we'll have more to say in the next couple of weeks.
3. Package download spoofing.
   - Very possible right now. Will be a bit harder when packages are hosted via tarballs on meteor.com and you actually have to download them.
   - I generally take the position that I'll assume people'll do the right thing, and deal with it if/when problems ever happen. It's not like it'd be very hard to figure out which are the spurious installs.
   - Most importantly: Download count isn't the be-all and end-all of the "Atmosphere Score". We plan to take a lot of other more difficult to game metrics into account. Again, watch this space.
4. Segmenting popularity
   - Interesting idea. Will mull on it.

**Comment by serkandurusoy** [comment]
1) I'd want them hidden/shown by preference. I, for one, believe that the popularity of an app translating to inevitable popularity of a package is kind of unhealthy in terms of data meaning.

2) I'm intrigued :)

3) Does not matter if full downloads are required. Packages are mere kilobytes and one can very easily download packages multiple times over some time and bias the whole popularity rankings and when you rank something, you inevitably take on the responsibility to overlook the whole domain as the defacto trusted source.

4) Let me know if I can help in any way

Overall, great job! Is there room for improvement? Yes. As is the case for all projects at all times :)

**Comment by serkandurusoy** [comment]
Please take a look at http://crater.io/posts/CL2QWTTv4B7GjKf66/ voicing a similar concern that revolves around default example apps.
