### ISSUE TITLE
Where is the github link for a package?

### ISSUE THREAD

**Issue by teknomath** [percolatestudio/atmosphere#63]
I don't see the github link for a package (in this case, bootstrap-themes)...I have some questions that the github page for the package can answer (like, the age of last update and the collection of themes included).  The old Atmosphere had a github link for every package, just like NPMjs.org does.

**Comment by zol** [comment]
Most likely the git url doesn't end with .git, as in issue #58. We'll be fixing this by making the regexp less strict soon.
