### ISSUE TITLE
Suggestion - ability to rate packages

### ISSUE THREAD

**Issue by Art1Sec8** [percolatestudio/atmosphere#68]
Have you thought about allowing users to rate packages? It might help to weed out the buggy packages.

**Comment by jacksondc** [comment]
+1

**Comment by dandv** [comment]
There's a similar suggestion for starring packages (#57), but I think rating would let users express a more nuanced opinion. Feel free to use my [jquery-rateit](http://beta.atmospherejs.com/package/jquery-rateit) package :)

@Art1Sec8: can you please edit the title of the issue and change "Suggestion" to something more precise? Thanks!

**Comment by tmeasday** [comment]
Next version of Atmosphere will have stars and flags which is a semi-nuanced rating scheme at what we thing is just the right level :)

**Comment by Art1Sec8** [comment]
@tmeasday awesome! Looking forward to it!

**Comment by Art1Sec8** [comment]
@tmeasday did you want me to close this down, or leave it open for now?

**Comment by zol** [comment]
@Art1Sec8 - Please leave it open so we can track the feature. Thanks.
