### ISSUE TITLE
"This package doesn't have a readme yet" on houston

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#69]
That error shows up at http://beta.atmospherejs.com/package/houston, but its GitHub does show a `README.md`. I remember the occasional "README not found" was a problem with the old atmosphere too.

**Comment by tmeasday** [comment]
Github is returning a 404. I guess it's because @gterrono moved the package.

I guess the answer here is to ask him to kindly update his package's metadata with the correct info.

**Comment by gterrono** [comment]
Should be fixed now. Thanks for letting me know.
