### ISSUE TITLE
Anyone else not enthusiastic about the search overlay?

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#72]
Maybe it's just me, or the novelty of it, but I find the interaction with the search overlay popping up and covering everything else, a bit... unwieldy?

**Comment by serkandurusoy** [comment]
It kind of has not grown on me yet, either.

**Comment by zol** [comment]
Perhaps it's too undiscoverable but the design underpinnings of the search overlay are:
- Your search results are preserved when you close the overlay. (allowing you to come back to your last search)
- You can use the 's' hotkey to bring up the search.

Did you guys find those features?

This allows for a user flow that's similar to cmd+s for spotlight search on a mac. The risk is that this interaction is too uncommon for the web.

**Comment by serkandurusoy** [comment]
I just realized I've been hitting the `esc` key to hide the overlay intuitively, nice! But in general, I'm still feeling a little bit awkward when using search, with no tangible reason whatsoever. Also, my complaint about the site being not so use friendly for lo-band connections apply to search as well. I'm writing this from a boat, there is heavy rain and storm, the connection is quite bad, and I cannot tell if atmosphere is working or not unless I'm really patient and faithful in it to work ;)

**Comment by dandv** [comment]
I did notice that search results were preserved... maybe it would be more discoverable if the overlay was a bit smaller, so it doesn't look like it replaced the page? Something like a pull-down console thing maybe, like in Unity or old-school games like Quake? (I think ` activated it there)

**Comment by domyen** [comment]
We've taken this feedback on board and further refined the search experience:
- Back button on search now available
- 'Searching' spinner for slower connections
- Open packages in new tabs
- Better query matching

I'll close this issue for now. If there are specific improvements feel free to make a new issue. Thanks folks. :)
