### ISSUE TITLE
Search-Result fades away if one opens package in search-Result with 'cmd' + 'left mouse click'

### ISSUE THREAD

**Issue by pmuens** [percolatestudio/atmosphere#75]
This might be related to #71:

If I've searched for packages and get the search-Result back, I can open the displayed packages in a new tab by pressing 'cmd' + 'left mouse click' on my MAC.

However, if I do so, the search popup will fade away. The detailed information for the package opens up in a new tab but it would be great if the search-Result won't fade away.

BTW: Awesome work guys!

**Comment by domyen** [comment]
Cheers, added this issue to the next milestone. Should be out shortly.

**Comment by pmuens** [comment]
Awesome! Thanks!
