### ISSUE TITLE
Links within Readme.md are hijacked and converted to relative URL rather than going to absolute URL

### ISSUE THREAD

**Issue by Dsyko** [percolatestudio/atmosphere#76]
When you are looking at a packages Readme.md within Atmosphere and it has a link which points to an external resource, clicking the link takes you to a http://beta.atmospherejs.com/ link rather than the intended url.

For example in the package http://beta.atmospherejs.com/package/entypo clicking on the link to the icon map takes you to http://beta.atmospherejs.com/meteor-entypo/ rather than the proper url http://dsyko.github.io/meteor-entypo/

**Comment by tmeasday** [comment]
Did those links use to work directly from Github (https://github.com/Dsyko/meteor-entypo/) ? I see you’ve changed them to absolute URLs now..

**Comment by Dsyko** [comment]
Yeah they seem to work on github just fine. I'm not sure what you mean by change them to absolute URLs, I haven't made any changes, I don't think I ever had them as relative URLs.

 The same problem comes up with other packages as well. See the Font-Awesome package: http://beta.atmospherejs.com/package/font-awesome and try to click on any of the links there.

Maybe this is only happening on my machine?

**Comment by tmeasday** [comment]
No, sorry you are right! 

I assumed that the URLs must have been relative and that's why it didn't work, but I see now that we are hijacking absolute URLs somehow. It's most likely an Iron Router bug. 

I'll look into it.

**Comment by Dsyko** [comment]
Ahh ok, good to know my browser isn't going crazy :)

Thanks for looking into it!

**Comment by dandv** [comment]
+1 - same problem at http://beta.atmospherejs.com/package/observatory-apollo. Link does look absolute when inspecting the element.

A different problem with the "documentation" link at http://beta.atmospherejs.com/package/winston - it yields a 404.

**Comment by emgee3** [comment]
Oh man, I thought I was going nuts... temporary workaround is to open links in new tab.

**Comment by tmeasday** [comment]
It was a bug I introduced in the new-location branch. Thanks for the report.
