### ISSUE TITLE
Add tooltip for "100" and other download markers

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#77]
What does the "100" mean in the [history of a package](http://beta.atmospherejs.com/package/winston)? For some reason (maybe because my eyes came there after seeing the GitHub link, and because the history mentioned **releases**), I thought it meant that the project had reached the 100 commits milestone, but I think it means 100 downloads.

"100" is also a bit of a false activity indicator... e.g. [this package](http://beta.atmospherejs.com/package/accounts-linkedin) hasn't seen an update in 6 months, but the most recent event appears to be this very week (the "100"), so I first assumed it was actively maintained.

**Comment by domyen** [comment]
Cheers @dandv, tooltips will be going out with the next release. 

**Re: activity indicator**
I'm curious to see if this remains the case as the scale of downloads in the ecosystem increases. e.g., What download milestone can the community expect a 'well-used' package to have in the future  (Iron-router is at 5k).
