### ISSUE TITLE
Safari Only: Tab opens twice when clicking on the package-Name with CMD + 'Left mouse'

### ISSUE THREAD

**Issue by pmuens** [percolatestudio/atmosphere#79]
If one opens the detail-Page of a package by clicking CMD + 'Left Mouse' on the Package-Name (e.g. in the trending section) the tab will open up twice.

I face this issue on a Mac with the Safari web browser.
The strange thing is that this issue only occurs when operating with Safari.

Thanks in advance!

**Comment by tmeasday** [comment]
Good pickup @pmuens -- actually it just happens if you happen to click the title -- due to us using a `<a>` element _and_ a link handler.
