### ISSUE TITLE
No loading animation for package view

### ISSUE THREAD

**Issue by dburles** [percolatestudio/atmosphere#80]
The package view should load a bit nicer, at the moment the footer will sit at the very top while the page is loading, see screenshot.  [edit: notice the menu, title and feedback button]

![screen shot 2014-03-08 at 12 40 42 pm](https://f.cloud.github.com/assets/319567/2364146/b959531a-a662-11e3-8794-7e3a681b3104.png)

**Comment by domyen** [comment]
Cheers @dburles. @tmeasday and I be looking at this along with page-to-page transitions and animations when there is resolution around iron-router with blaze. Definitely will not be forgotten about.

**Comment by domyen** [comment]
Will be tackled by Iron Transitioner integration in the next week or two. https://github.com/percolatestudio/atmosphere-beta/issues/103

**Comment by tmeasday** [comment]
I think this is already fixed anyway.
