### ISSUE TITLE
Servers, 503's

### ISSUE THREAD

**Issue by dburles** [percolatestudio/atmosphere#81]
Seeing a lot of "503 Service Unavailable, No server is available to handle this request."

**Comment by domyen** [comment]
I've experienced this as well. @zol have you been seeing this as well?

**Comment by zol** [comment]
Yeah, the backend was struggling this weekend (of all weekends) when T and I were both off the air. On hindsight, should have left a secondary node on, which is what T did to combat the problem. We'll investigate this week.
