### ISSUE TITLE
Mixpanel: QA & test

### ISSUE THREAD

**Issue by domyen** [percolatestudio/atmosphere#82]
QA & Test current mixpanel infrastructure.

**Comment by tmeasday** [comment]
Ping @zol

**Comment by zol** [comment]
As a first step I've reset the data points for the production project in mixpanel and emailed their staff to update our quote. As soon as they've done this I will look closer at our events.

To clarify, the issue is that events seem to get tracked multiple times.

**Comment by zol** [comment]
I've disabled mixpanel tracking for now as GA covers the metrics we're interested in for the moment (pageviews).
