### ISSUE TITLE
Search: [Enter] key causes search spinner to endlessly spin

### ISSUE THREAD

**Issue by domyen** [percolatestudio/atmosphere#86]
Repro:
1. Open localhost:3000
2. Activate search
3. Type 'fa' into the input
4. Wait for the results to load and the spinner to be replaced with the magnifying glass icon
5. Bug: press [Enter/Return], the spinner now spins tirelessly despite the fact that all results are accounted for

**Comment by domyen** [comment]
@tmeasday New bug: Opening search for the first time causes the spinner to activate even though the query is blank.

**Comment by tmeasday** [comment]
Fixed. Please check.
