### ISSUE TITLE
scrolling hookup on `rendered` event is wrong

### ISSUE THREAD

**Issue by tmeasday** [percolatestudio/atmosphere#89]
Can still trigger problems. Repro
1. Load a search URL directly: e.g. http://localhost:3000?q=foo
2. Close the search overlay
3. Scroll down.

**Comment by domyen** [comment]
@tmeasday When I load a search page on the home screen, closing the overlay does not take me back to home but rather to the new blank tab/window. Is this what you're describing above?

**Comment by tmeasday** [comment]
Yes! You are right. I should check for this.

**Comment by tmeasday** [comment]
The original problem is a weird one.

For some reason, when the homepage re-renders (due to the overlay closing), the waypoints stop working. Due to the nature of blaze, `rendered` doesn't get called again, so we can't fix it.

I can't figure out why the waypoints stop working (it happens even when there are no CSS changes). I'll need to dig into the waypoints source to try and figure out it.

There isn't a better event to hook into to set the waypoints up though, unfortunately -- nothing is being rendered for the first time, so there's no obvious hook to use. Really, the waypoints should continue to work. It's probably worth figuring out why..

**Comment by tmeasday** [comment]
Closing this as we aren't doing it anymore
