### ISSUE TITLE
List of recent items seems to omit the most recent 24 hours

### ISSUE THREAD

**Issue by serkandurusoy** [percolatestudio/atmosphere#92]
I currently have both sites open side by side and beta's recent items start with phaserio whereas on the v1, there seems to be ~30 packages released/updated after that.

What's outstanding (perhaps just coincidentally) is that v1 shows phaserio as the first package timestamped as "a day ago" while others following are "xx hours ago"

**Comment by tmeasday** [comment]
Yes! I accidentally turned off the syncing. Thanks for the report @serkandurusoy
