### ISSUE TITLE
README not appearing (Chrome)

### ISSUE THREAD

**Issue by kylemclaren** [percolatestudio/atmosphere#93]
For some reason the README doc is not pulling in.

![screen shot 2014-03-19 at 2 27 02 pm](https://f.cloud.github.com/assets/3727384/2459835/1b1bc1e8-af62-11e3-902b-fcd8a2392779.png)

**Comment by domyen** [comment]
If a package is very very new it takes a moment to show the readme. This state usually appears in the interim while we pull the readme from Github. 

@kylemclaren http://beta.atmospherejs.com/package/bootswatch-darkly seems to have a readme.

**Comment by kylemclaren** [comment]
Think it's an issue with Chrome as it works with Safari 100%. I'll disable some extensions and see what could be blocking it..

**Comment by domyen** [comment]
Let me know how it goes. I wasn't able to reproduce on Chrome earlier but
if there's a sequence of steps that triggers this behavior I would like to
get to the bottom of it.

On Thursday, March 20, 2014, Kyle McLaren notifications@github.com wrote:

> Think it's an issue with Chrome as it works with Safari 100%. I'll disable
> some extensions and see what could be blocking it..
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/percolatestudio/atmosphere-beta/issues/93#issuecomment-38140815
> .

## 

_Dominic Nguyen_
Design Lead
http://percolatestudio.com
@domyen
+1 858 335 1680

**Comment by kylemclaren** [comment]
@dominicnguyen Working now. Wondering if it could be an HTTPS issue as discussed [here](https://groups.google.com/forum/#!topic/meteor-talk/OLmn04jiUNo) because looks like you guys have added SSL. May have been related to my ISP or the AVAST! plugin on Chrome. Didn't have a chance to test properly but all good. Thanks for the good work!
