### ISSUE TITLE
Package "keybindings" says that it isn't my package but it is.

### ISSUE THREAD

**Issue by matteodem** [percolatestudio/atmosphere#95]
Hey there

I got this problem nowhere but with "keybindings", can that be fixed? I wanted to push a new release but this got in the way.

**Comment by domyen** [comment]
We'd like to help, can you clarify the problem?

**Comment by tmeasday** [comment]
Hey @matteodem - that's odd. What's your username on atmosphere? It appears to be owned by 'matdem'.

**Comment by matteodem** [comment]
Hello there, that might be my old username. Is there anyway to qualify that I'm the rightful owner of the package and change it to "matteodem"?

**Comment by tmeasday** [comment]
I added matteodem as an owner of the package.
