### ISSUE TITLE
Search: Remove limit on search results displayed

### ISSUE THREAD

**Issue by domyen** [percolatestudio/atmosphere#96]
There is a limit on the number of search results displayed. Find a way to remove the limit while maintaining speed & responsiveness.
1. Search 'f'
2. Notice that it has more than a hundred packages
3. Scroll down and see that it only loads 20 packages

@tmeasday any ideas? Perhaps load the initial 20 and infinite scroll to load the rest?

**Comment by serkandurusoy** [comment]
+1 

I actually got here to see if anyone else has reported this issue. Getting only 20 packages is very limiting. Not just for large-span searches like "f", but for highly critical searches like "collection" as well! This has 65 hits but only 20 results displayed :(

**Comment by dandv** [comment]
+1. Nodezoo has [the same issue](https://github.com/rjrodger/nodezoo/issues/7). Would be nice to learn from their mistake.

**Comment by domyen** [comment]
This will be addressed along with infinite-scroll https://github.com/percolatestudio/atmosphere-beta/issues/106.
