### ISSUE TITLE
Search, more precise query hits less.

### ISSUE THREAD

**Issue by nooitaf** [percolatestudio/atmosphere#98]
![screen shot 2014-03-23 at 16 13 55](https://f.cloud.github.com/assets/1898194/2493626/a8edd1b6-b29e-11e3-8100-27d58befcdeb.jpg)

![screen shot 2014-03-23 at 16 14 08](https://f.cloud.github.com/assets/1898194/2493627/ad81d9ca-b29e-11e3-859f-edabffb485d2.jpg)

**Comment by domyen** [comment]
@nooitaf thanks, should be fixed now!
