### ISSUE TITLE
Readme is not loading

### ISSUE THREAD

**Issue by marcodejongh** [percolatestudio/atmosphere#99]
The notifications repository has a readme.md but for some reason its not loading
http://beta.atmospherejs.com/package/notifications

**Comment by domyen** [comment]
Hey @marcodejongh, we load the readme from Github at the moment so Atmosphere users should add the Github url of their packages to show readmes. This may change in the future to support folks w/o GH or who use other services like Bitbucket. 

For now I'm going to close and link to a similar issue: https://github.com/percolatestudio/atmosphere-beta/issues/88

**Comment by marcodejongh** [comment]
@dominicnguyen Ah found the problem after your comment. I included the github url without the git extension and then it doesn't work. So maybe it should be programmed more defensively or it should be documented that you should include the .git extension

**Comment by domyen** [comment]
@tmeasday any reason why we require the .git extension? This may be resolved with MDG sorts out the packaging backend.

**Comment by domyen** [comment]
@marcodejongh thanks for the suggestion. Packages should now work without .git extension.
